/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEpisodeRequest,
  EpisodeListResponse,
  EpisodeResponse,
  EpisodeStatus,
  HTTPValidationError,
  ReorderEpisodesRequest,
  UpdateEpisodeRequest,
  UpdateEpisodeSettingsRequest,
} from '../models/index';
import {
    CreateEpisodeRequestFromJSON,
    CreateEpisodeRequestToJSON,
    EpisodeListResponseFromJSON,
    EpisodeListResponseToJSON,
    EpisodeResponseFromJSON,
    EpisodeResponseToJSON,
    EpisodeStatusFromJSON,
    EpisodeStatusToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ReorderEpisodesRequestFromJSON,
    ReorderEpisodesRequestToJSON,
    UpdateEpisodeRequestFromJSON,
    UpdateEpisodeRequestToJSON,
    UpdateEpisodeSettingsRequestFromJSON,
    UpdateEpisodeSettingsRequestToJSON,
} from '../models/index';

export interface CreateEpisodeEpisodesPostRequest {
    createEpisodeRequest: CreateEpisodeRequest;
}

export interface DeleteEpisodeEpisodesEpisodeIdDeleteRequest {
    episodeId: string;
}

export interface GetEpisodeEpisodesEpisodeIdGetRequest {
    episodeId: string;
}

export interface ListEpisodesEpisodesGetRequest {
    storyId?: string | null;
    characterIds?: string | null;
    status?: EpisodeStatus | null;
    includePanels?: boolean;
    limit?: number;
    paginationToken?: string | null;
}

export interface ReorderEpisodesEpisodesReorderPatchRequest {
    reorderEpisodesRequest: ReorderEpisodesRequest;
}

export interface UpdateEpisodeEpisodesEpisodeIdPatchRequest {
    episodeId: string;
    updateEpisodeRequest: UpdateEpisodeRequest;
}

export interface UpdateEpisodeSettingsEpisodesEpisodeIdSettingsPatchRequest {
    episodeId: string;
    updateEpisodeSettingsRequest: UpdateEpisodeSettingsRequest;
}

/**
 * 
 */
export class EpisodesApi extends runtime.BaseAPI {

    /**
     * Create Episode
     */
    async createEpisodeEpisodesPostRaw(requestParameters: CreateEpisodeEpisodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EpisodeResponse>> {
        if (requestParameters['createEpisodeRequest'] == null) {
            throw new runtime.RequiredError(
                'createEpisodeRequest',
                'Required parameter "createEpisodeRequest" was null or undefined when calling createEpisodeEpisodesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/episodes/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEpisodeRequestToJSON(requestParameters['createEpisodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EpisodeResponseFromJSON(jsonValue));
    }

    /**
     * Create Episode
     */
    async createEpisodeEpisodesPost(requestParameters: CreateEpisodeEpisodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EpisodeResponse> {
        const response = await this.createEpisodeEpisodesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Episode
     */
    async deleteEpisodeEpisodesEpisodeIdDeleteRaw(requestParameters: DeleteEpisodeEpisodesEpisodeIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling deleteEpisodeEpisodesEpisodeIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/episodes/{episode_id}`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Episode
     */
    async deleteEpisodeEpisodesEpisodeIdDelete(requestParameters: DeleteEpisodeEpisodesEpisodeIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEpisodeEpisodesEpisodeIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Episode
     */
    async getEpisodeEpisodesEpisodeIdGetRaw(requestParameters: GetEpisodeEpisodesEpisodeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EpisodeResponse>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling getEpisodeEpisodesEpisodeIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/episodes/{episode_id}`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EpisodeResponseFromJSON(jsonValue));
    }

    /**
     * Get Episode
     */
    async getEpisodeEpisodesEpisodeIdGet(requestParameters: GetEpisodeEpisodesEpisodeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EpisodeResponse> {
        const response = await this.getEpisodeEpisodesEpisodeIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Episodes
     */
    async listEpisodesEpisodesGetRaw(requestParameters: ListEpisodesEpisodesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EpisodeListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['storyId'] != null) {
            queryParameters['storyId'] = requestParameters['storyId'];
        }

        if (requestParameters['characterIds'] != null) {
            queryParameters['characterIds'] = requestParameters['characterIds'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['includePanels'] != null) {
            queryParameters['includePanels'] = requestParameters['includePanels'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['paginationToken'] != null) {
            queryParameters['paginationToken'] = requestParameters['paginationToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/episodes/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EpisodeListResponseFromJSON(jsonValue));
    }

    /**
     * List Episodes
     */
    async listEpisodesEpisodesGet(requestParameters: ListEpisodesEpisodesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EpisodeListResponse> {
        const response = await this.listEpisodesEpisodesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reorder Episodes
     */
    async reorderEpisodesEpisodesReorderPatchRaw(requestParameters: ReorderEpisodesEpisodesReorderPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['reorderEpisodesRequest'] == null) {
            throw new runtime.RequiredError(
                'reorderEpisodesRequest',
                'Required parameter "reorderEpisodesRequest" was null or undefined when calling reorderEpisodesEpisodesReorderPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/episodes/reorder`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ReorderEpisodesRequestToJSON(requestParameters['reorderEpisodesRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Reorder Episodes
     */
    async reorderEpisodesEpisodesReorderPatch(requestParameters: ReorderEpisodesEpisodesReorderPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.reorderEpisodesEpisodesReorderPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Episode
     */
    async updateEpisodeEpisodesEpisodeIdPatchRaw(requestParameters: UpdateEpisodeEpisodesEpisodeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EpisodeResponse>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling updateEpisodeEpisodesEpisodeIdPatch().'
            );
        }

        if (requestParameters['updateEpisodeRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEpisodeRequest',
                'Required parameter "updateEpisodeRequest" was null or undefined when calling updateEpisodeEpisodesEpisodeIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/episodes/{episode_id}`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEpisodeRequestToJSON(requestParameters['updateEpisodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EpisodeResponseFromJSON(jsonValue));
    }

    /**
     * Update Episode
     */
    async updateEpisodeEpisodesEpisodeIdPatch(requestParameters: UpdateEpisodeEpisodesEpisodeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EpisodeResponse> {
        const response = await this.updateEpisodeEpisodesEpisodeIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Episode Settings
     */
    async updateEpisodeSettingsEpisodesEpisodeIdSettingsPatchRaw(requestParameters: UpdateEpisodeSettingsEpisodesEpisodeIdSettingsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling updateEpisodeSettingsEpisodesEpisodeIdSettingsPatch().'
            );
        }

        if (requestParameters['updateEpisodeSettingsRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEpisodeSettingsRequest',
                'Required parameter "updateEpisodeSettingsRequest" was null or undefined when calling updateEpisodeSettingsEpisodesEpisodeIdSettingsPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/episodes/{episode_id}/settings`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEpisodeSettingsRequestToJSON(requestParameters['updateEpisodeSettingsRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Episode Settings
     */
    async updateEpisodeSettingsEpisodesEpisodeIdSettingsPatch(requestParameters: UpdateEpisodeSettingsEpisodesEpisodeIdSettingsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateEpisodeSettingsEpisodesEpisodeIdSettingsPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
