/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetDetailedPostsResponse,
  GetPostsResponse,
  HTTPValidationError,
  PatchPostTitleRequest,
  PostCategoryValues,
  PostPublishResponse,
  PostReportRequest,
  PostSearchRequest,
  PostShareGetTagsRequest,
  PostSharePublishRequest,
  PostShareTagsResponse,
  PostType,
} from '../models/index';
import {
    GetDetailedPostsResponseFromJSON,
    GetDetailedPostsResponseToJSON,
    GetPostsResponseFromJSON,
    GetPostsResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PatchPostTitleRequestFromJSON,
    PatchPostTitleRequestToJSON,
    PostCategoryValuesFromJSON,
    PostCategoryValuesToJSON,
    PostPublishResponseFromJSON,
    PostPublishResponseToJSON,
    PostReportRequestFromJSON,
    PostReportRequestToJSON,
    PostSearchRequestFromJSON,
    PostSearchRequestToJSON,
    PostShareGetTagsRequestFromJSON,
    PostShareGetTagsRequestToJSON,
    PostSharePublishRequestFromJSON,
    PostSharePublishRequestToJSON,
    PostShareTagsResponseFromJSON,
    PostShareTagsResponseToJSON,
    PostTypeFromJSON,
    PostTypeToJSON,
} from '../models/index';

export interface BlacklistPostPostBlacklistPostIdPatchRequest {
    postId: string;
}

export interface BoostPostPostLikeBoostPostIdPostRequest {
    postId: string;
    likesCount: number;
}

export interface BoostTrendingPostsPostLikeBoostPostRequest {
    likesPerPost?: number;
    likesThreshold?: number;
    ageHoursThreshold?: number;
    boostAlreadyBoosted?: boolean;
}

export interface CategoriesPostCategoriesGetRequest {
    postType?: PostType | null;
}

export interface DeletePostPostIdDeleteRequest {
    postId: string;
}

export interface GetPostPostPostIdGetRequest {
    postId: string;
}

export interface GetTagsPostShareContentIdTagsPostRequest {
    contentId: string;
    postShareGetTagsRequest: PostShareGetTagsRequest;
}

export interface LikePostPostIdLikePutRequest {
    postId: string;
}

export interface LikeRandomNewPostsPostLikeRandomPostRequest {
    botsCount?: number;
    likesPerBot?: number;
    ageHoursThreshold?: number;
}

export interface PatchPostTitlePostPostIdTitlePatchRequest {
    postId: string;
    patchPostTitleRequest: PatchPostTitleRequest;
}

export interface ReportPostPostPostIdReportPostRequest {
    postId: string;
    postReportRequest: PostReportRequest;
}

export interface SearchPostsPostSearchPostRequest {
    postSearchRequest: PostSearchRequest;
}

export interface SharePostShareContentIdPublishPostRequest {
    contentId: string;
    postSharePublishRequest: PostSharePublishRequest;
}

/**
 * 
 */
export class PostApi extends runtime.BaseAPI {

    /**
     * Blacklist Post
     */
    async blacklistPostPostBlacklistPostIdPatchRaw(requestParameters: BlacklistPostPostBlacklistPostIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling blacklistPostPostBlacklistPostIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/post/blacklist/{post_id}/`.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Blacklist Post
     */
    async blacklistPostPostBlacklistPostIdPatch(requestParameters: BlacklistPostPostBlacklistPostIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.blacklistPostPostBlacklistPostIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Adds bot likes from accounts that have not liked it yet.**
     * Boost a specific post with bot likes
     */
    async boostPostPostLikeBoostPostIdPostRaw(requestParameters: BoostPostPostLikeBoostPostIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling boostPostPostLikeBoostPostIdPost().'
            );
        }

        if (requestParameters['likesCount'] == null) {
            throw new runtime.RequiredError(
                'likesCount',
                'Required parameter "likesCount" was null or undefined when calling boostPostPostLikeBoostPostIdPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['likesCount'] != null) {
            queryParameters['likes_count'] = requestParameters['likesCount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/post/like/boost/{post_id}`.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Adds bot likes from accounts that have not liked it yet.**
     * Boost a specific post with bot likes
     */
    async boostPostPostLikeBoostPostIdPost(requestParameters: BoostPostPostLikeBoostPostIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.boostPostPostLikeBoostPostIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Adds bot likes to trending non-blacklisted posts that pass the configured age and likes thresholds.**
     * Boost trending posts with bot likes
     */
    async boostTrendingPostsPostLikeBoostPostRaw(requestParameters: BoostTrendingPostsPostLikeBoostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['likesPerPost'] != null) {
            queryParameters['likes_per_post'] = requestParameters['likesPerPost'];
        }

        if (requestParameters['likesThreshold'] != null) {
            queryParameters['likes_threshold'] = requestParameters['likesThreshold'];
        }

        if (requestParameters['ageHoursThreshold'] != null) {
            queryParameters['age_hours_threshold'] = requestParameters['ageHoursThreshold'];
        }

        if (requestParameters['boostAlreadyBoosted'] != null) {
            queryParameters['boost_already_boosted'] = requestParameters['boostAlreadyBoosted'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/post/like/boost`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Adds bot likes to trending non-blacklisted posts that pass the configured age and likes thresholds.**
     * Boost trending posts with bot likes
     */
    async boostTrendingPostsPostLikeBoostPost(requestParameters: BoostTrendingPostsPostLikeBoostPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.boostTrendingPostsPostLikeBoostPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Categories
     */
    async categoriesPostCategoriesGetRaw(requestParameters: CategoriesPostCategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostCategoryValues>> {
        const queryParameters: any = {};

        if (requestParameters['postType'] != null) {
            queryParameters['post_type'] = requestParameters['postType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/post/categories/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostCategoryValuesFromJSON(jsonValue));
    }

    /**
     * Categories
     */
    async categoriesPostCategoriesGet(requestParameters: CategoriesPostCategoriesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostCategoryValues> {
        const response = await this.categoriesPostCategoriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete
     */
    async deletePostPostIdDeleteRaw(requestParameters: DeletePostPostIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling deletePostPostIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/post/{post_id}/`.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete
     */
    async deletePostPostIdDelete(requestParameters: DeletePostPostIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deletePostPostIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Post
     */
    async getPostPostPostIdGetRaw(requestParameters: GetPostPostPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDetailedPostsResponse>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getPostPostPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/post/{post_id}`.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDetailedPostsResponseFromJSON(jsonValue));
    }

    /**
     * Get Post
     */
    async getPostPostPostIdGet(requestParameters: GetPostPostPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDetailedPostsResponse> {
        const response = await this.getPostPostPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Tags
     */
    async getTagsPostShareContentIdTagsPostRaw(requestParameters: GetTagsPostShareContentIdTagsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostShareTagsResponse>> {
        if (requestParameters['contentId'] == null) {
            throw new runtime.RequiredError(
                'contentId',
                'Required parameter "contentId" was null or undefined when calling getTagsPostShareContentIdTagsPost().'
            );
        }

        if (requestParameters['postShareGetTagsRequest'] == null) {
            throw new runtime.RequiredError(
                'postShareGetTagsRequest',
                'Required parameter "postShareGetTagsRequest" was null or undefined when calling getTagsPostShareContentIdTagsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/post/share/{content_id}/tags`.replace(`{${"content_id"}}`, encodeURIComponent(String(requestParameters['contentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostShareGetTagsRequestToJSON(requestParameters['postShareGetTagsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostShareTagsResponseFromJSON(jsonValue));
    }

    /**
     * Get Tags
     */
    async getTagsPostShareContentIdTagsPost(requestParameters: GetTagsPostShareContentIdTagsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostShareTagsResponse> {
        const response = await this.getTagsPostShareContentIdTagsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Like
     */
    async likePostPostIdLikePutRaw(requestParameters: LikePostPostIdLikePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling likePostPostIdLikePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/post/{post_id}/like`.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Like
     */
    async likePostPostIdLikePut(requestParameters: LikePostPostIdLikePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.likePostPostIdLikePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Uses bot accounts to like recently created, non-blackliested posts that the selected bots have not liked yet. Dynamically creates additional bot accounts if needed.**
     * Add random bot likes to new posts
     */
    async likeRandomNewPostsPostLikeRandomPostRaw(requestParameters: LikeRandomNewPostsPostLikeRandomPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['botsCount'] != null) {
            queryParameters['bots_count'] = requestParameters['botsCount'];
        }

        if (requestParameters['likesPerBot'] != null) {
            queryParameters['likes_per_bot'] = requestParameters['likesPerBot'];
        }

        if (requestParameters['ageHoursThreshold'] != null) {
            queryParameters['age_hours_threshold'] = requestParameters['ageHoursThreshold'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/post/like/random`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * **Uses bot accounts to like recently created, non-blackliested posts that the selected bots have not liked yet. Dynamically creates additional bot accounts if needed.**
     * Add random bot likes to new posts
     */
    async likeRandomNewPostsPostLikeRandomPost(requestParameters: LikeRandomNewPostsPostLikeRandomPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.likeRandomNewPostsPostLikeRandomPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Patch Post Title
     */
    async patchPostTitlePostPostIdTitlePatchRaw(requestParameters: PatchPostTitlePostPostIdTitlePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling patchPostTitlePostPostIdTitlePatch().'
            );
        }

        if (requestParameters['patchPostTitleRequest'] == null) {
            throw new runtime.RequiredError(
                'patchPostTitleRequest',
                'Required parameter "patchPostTitleRequest" was null or undefined when calling patchPostTitlePostPostIdTitlePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/post/{post_id}/title`.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchPostTitleRequestToJSON(requestParameters['patchPostTitleRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Patch Post Title
     */
    async patchPostTitlePostPostIdTitlePatch(requestParameters: PatchPostTitlePostPostIdTitlePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.patchPostTitlePostPostIdTitlePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Report Post
     */
    async reportPostPostPostIdReportPostRaw(requestParameters: ReportPostPostPostIdReportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling reportPostPostPostIdReportPost().'
            );
        }

        if (requestParameters['postReportRequest'] == null) {
            throw new runtime.RequiredError(
                'postReportRequest',
                'Required parameter "postReportRequest" was null or undefined when calling reportPostPostPostIdReportPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/post/{post_id}/report`.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostReportRequestToJSON(requestParameters['postReportRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Report Post
     */
    async reportPostPostPostIdReportPost(requestParameters: ReportPostPostPostIdReportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.reportPostPostPostIdReportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search Posts
     */
    async searchPostsPostSearchPostRaw(requestParameters: SearchPostsPostSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPostsResponse>> {
        if (requestParameters['postSearchRequest'] == null) {
            throw new runtime.RequiredError(
                'postSearchRequest',
                'Required parameter "postSearchRequest" was null or undefined when calling searchPostsPostSearchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/post/search/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostSearchRequestToJSON(requestParameters['postSearchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPostsResponseFromJSON(jsonValue));
    }

    /**
     * Search Posts
     */
    async searchPostsPostSearchPost(requestParameters: SearchPostsPostSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPostsResponse> {
        const response = await this.searchPostsPostSearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Share
     */
    async sharePostShareContentIdPublishPostRaw(requestParameters: SharePostShareContentIdPublishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostPublishResponse>> {
        if (requestParameters['contentId'] == null) {
            throw new runtime.RequiredError(
                'contentId',
                'Required parameter "contentId" was null or undefined when calling sharePostShareContentIdPublishPost().'
            );
        }

        if (requestParameters['postSharePublishRequest'] == null) {
            throw new runtime.RequiredError(
                'postSharePublishRequest',
                'Required parameter "postSharePublishRequest" was null or undefined when calling sharePostShareContentIdPublishPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/post/share/{content_id}/publish`.replace(`{${"content_id"}}`, encodeURIComponent(String(requestParameters['contentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostSharePublishRequestToJSON(requestParameters['postSharePublishRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostPublishResponseFromJSON(jsonValue));
    }

    /**
     * Share
     */
    async sharePostShareContentIdPublishPost(requestParameters: SharePostShareContentIdPublishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostPublishResponse> {
        const response = await this.sharePostShareContentIdPublishPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
