/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  PostImagenResponse,
  StoryCreatorActorListResponse,
  StoryCreatorActorResponse,
  StoryCreatorCreateActorRequest,
  StoryCreatorCreateEpisodeRequest,
  StoryCreatorCreateStoryRequest,
  StoryCreatorCreateStoryResponse,
  StoryCreatorEpisodeListResponse,
  StoryCreatorEpisodeResponse,
  StoryCreatorEpisodeWithPanelsResponse,
  StoryCreatorEpisodeWithStoryAndPanelsResponse,
  StoryCreatorGenerateAvatarRequest,
  StoryCreatorImportActorRequest,
  StoryCreatorLockEpisodeRequest,
  StoryCreatorPurchaseEpisodeRequest,
  StoryCreatorPurchaseEpisodeResponse,
  StoryCreatorRateEpisodeRequest,
  StoryCreatorSaveEpisodeRequest,
  StoryCreatorStoryListResponse,
  StoryCreatorStoryResponse,
  StoryCreatorUpdateActorRequest,
  StoryCreatorUpdateEpisodeRequest,
  StoryCreatorUpdateEpisodeVisibilityRequest,
  StoryCreatorUpdateStoryRequest,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PostImagenResponseFromJSON,
    PostImagenResponseToJSON,
    StoryCreatorActorListResponseFromJSON,
    StoryCreatorActorListResponseToJSON,
    StoryCreatorActorResponseFromJSON,
    StoryCreatorActorResponseToJSON,
    StoryCreatorCreateActorRequestFromJSON,
    StoryCreatorCreateActorRequestToJSON,
    StoryCreatorCreateEpisodeRequestFromJSON,
    StoryCreatorCreateEpisodeRequestToJSON,
    StoryCreatorCreateStoryRequestFromJSON,
    StoryCreatorCreateStoryRequestToJSON,
    StoryCreatorCreateStoryResponseFromJSON,
    StoryCreatorCreateStoryResponseToJSON,
    StoryCreatorEpisodeListResponseFromJSON,
    StoryCreatorEpisodeListResponseToJSON,
    StoryCreatorEpisodeResponseFromJSON,
    StoryCreatorEpisodeResponseToJSON,
    StoryCreatorEpisodeWithPanelsResponseFromJSON,
    StoryCreatorEpisodeWithPanelsResponseToJSON,
    StoryCreatorEpisodeWithStoryAndPanelsResponseFromJSON,
    StoryCreatorEpisodeWithStoryAndPanelsResponseToJSON,
    StoryCreatorGenerateAvatarRequestFromJSON,
    StoryCreatorGenerateAvatarRequestToJSON,
    StoryCreatorImportActorRequestFromJSON,
    StoryCreatorImportActorRequestToJSON,
    StoryCreatorLockEpisodeRequestFromJSON,
    StoryCreatorLockEpisodeRequestToJSON,
    StoryCreatorPurchaseEpisodeRequestFromJSON,
    StoryCreatorPurchaseEpisodeRequestToJSON,
    StoryCreatorPurchaseEpisodeResponseFromJSON,
    StoryCreatorPurchaseEpisodeResponseToJSON,
    StoryCreatorRateEpisodeRequestFromJSON,
    StoryCreatorRateEpisodeRequestToJSON,
    StoryCreatorSaveEpisodeRequestFromJSON,
    StoryCreatorSaveEpisodeRequestToJSON,
    StoryCreatorStoryListResponseFromJSON,
    StoryCreatorStoryListResponseToJSON,
    StoryCreatorStoryResponseFromJSON,
    StoryCreatorStoryResponseToJSON,
    StoryCreatorUpdateActorRequestFromJSON,
    StoryCreatorUpdateActorRequestToJSON,
    StoryCreatorUpdateEpisodeRequestFromJSON,
    StoryCreatorUpdateEpisodeRequestToJSON,
    StoryCreatorUpdateEpisodeVisibilityRequestFromJSON,
    StoryCreatorUpdateEpisodeVisibilityRequestToJSON,
    StoryCreatorUpdateStoryRequestFromJSON,
    StoryCreatorUpdateStoryRequestToJSON,
} from '../models/index';

export interface CreateEpisodeStoryCreatorStoriesStoryIdEpisodesPostRequest {
    storyId: string;
    storyCreatorCreateEpisodeRequest: StoryCreatorCreateEpisodeRequest;
}

export interface CreateNewActorStoryCreatorStoriesStoryIdActorNewPostRequest {
    storyId: string;
    storyCreatorCreateActorRequest: StoryCreatorCreateActorRequest;
}

export interface CreateStoryStoryCreatorStoriesPostRequest {
    storyCreatorCreateStoryRequest: StoryCreatorCreateStoryRequest;
}

export interface DeleteActorStoryCreatorActorsActorIdDeleteRequest {
    actorId: string;
}

export interface DeleteEpisodeStoryCreatorEpisodesEpisodeIdDeleteRequest {
    episodeId: string;
}

export interface DeleteStoryStoryCreatorStoriesStoryIdDeleteRequest {
    storyId: string;
}

export interface FinishEpisodeStoryCreatorEpisodesEpisodeIdFinishPostRequest {
    episodeId: string;
}

export interface GenerateAvatarStoryCreatorStoriesStoryIdActorAvatarPostRequest {
    storyId: string;
    storyCreatorGenerateAvatarRequest: StoryCreatorGenerateAvatarRequest;
}

export interface GetCurrentEpisodeVersionStoryCreatorEpisodesEpisodeIdCurrentGetRequest {
    episodeId: string;
}

export interface GetEpisodeStoryCreatorEpisodesEpisodeIdGetRequest {
    episodeId: string;
}

export interface ImportActorStoryCreatorStoriesStoryIdActorImportPostRequest {
    storyId: string;
    storyCreatorImportActorRequest: StoryCreatorImportActorRequest;
}

export interface ListActorsStoryCreatorStoriesStoryIdActorsGetRequest {
    storyId: string;
}

export interface ListEpisodesStoryCreatorStoriesStoryIdEpisodesGetRequest {
    storyId: string;
}

export interface LockEpisodeStoryCreatorEpisodesEpisodeIdLockPatchRequest {
    episodeId: string;
    storyCreatorLockEpisodeRequest: StoryCreatorLockEpisodeRequest;
}

export interface PurchaseEpisodeStoryCreatorEpisodesEpisodeIdPurchasePostRequest {
    episodeId: string;
    storyCreatorPurchaseEpisodeRequest: StoryCreatorPurchaseEpisodeRequest;
}

export interface RateEpisodeStoryCreatorEpisodesEpisodeIdRatingPostRequest {
    episodeId: string;
    storyCreatorRateEpisodeRequest: StoryCreatorRateEpisodeRequest;
}

export interface SaveEpisodeStoryCreatorEpisodesEpisodeIdPutRequest {
    episodeId: string;
    storyCreatorSaveEpisodeRequest: StoryCreatorSaveEpisodeRequest;
}

export interface UnlockEpisodeStoryCreatorEpisodesEpisodeIdLockDeleteRequest {
    episodeId: string;
}

export interface UpdateActorStoryCreatorActorsActorIdPatchRequest {
    actorId: string;
    storyCreatorUpdateActorRequest: StoryCreatorUpdateActorRequest;
}

export interface UpdateEpisodeStoryCreatorEpisodesEpisodeIdPatchRequest {
    episodeId: string;
    storyCreatorUpdateEpisodeRequest: StoryCreatorUpdateEpisodeRequest;
}

export interface UpdateEpisodeVisibilityStoryCreatorEpisodesEpisodeIdVisibilityPatchRequest {
    episodeId: string;
    storyCreatorUpdateEpisodeVisibilityRequest: StoryCreatorUpdateEpisodeVisibilityRequest;
}

export interface UpdateStoryStoryCreatorStoriesStoryIdPatchRequest {
    storyId: string;
    storyCreatorUpdateStoryRequest: StoryCreatorUpdateStoryRequest;
}

/**
 * 
 */
export class StoryCreatorApi extends runtime.BaseAPI {

    /**
     * Create Episode
     */
    async createEpisodeStoryCreatorStoriesStoryIdEpisodesPostRaw(requestParameters: CreateEpisodeStoryCreatorStoriesStoryIdEpisodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorEpisodeResponse>> {
        if (requestParameters['storyId'] == null) {
            throw new runtime.RequiredError(
                'storyId',
                'Required parameter "storyId" was null or undefined when calling createEpisodeStoryCreatorStoriesStoryIdEpisodesPost().'
            );
        }

        if (requestParameters['storyCreatorCreateEpisodeRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorCreateEpisodeRequest',
                'Required parameter "storyCreatorCreateEpisodeRequest" was null or undefined when calling createEpisodeStoryCreatorStoriesStoryIdEpisodesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/stories/{story_id}/episodes`.replace(`{${"story_id"}}`, encodeURIComponent(String(requestParameters['storyId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorCreateEpisodeRequestToJSON(requestParameters['storyCreatorCreateEpisodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorEpisodeResponseFromJSON(jsonValue));
    }

    /**
     * Create Episode
     */
    async createEpisodeStoryCreatorStoriesStoryIdEpisodesPost(requestParameters: CreateEpisodeStoryCreatorStoriesStoryIdEpisodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorEpisodeResponse> {
        const response = await this.createEpisodeStoryCreatorStoriesStoryIdEpisodesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create New Actor
     */
    async createNewActorStoryCreatorStoriesStoryIdActorNewPostRaw(requestParameters: CreateNewActorStoryCreatorStoriesStoryIdActorNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorActorResponse>> {
        if (requestParameters['storyId'] == null) {
            throw new runtime.RequiredError(
                'storyId',
                'Required parameter "storyId" was null or undefined when calling createNewActorStoryCreatorStoriesStoryIdActorNewPost().'
            );
        }

        if (requestParameters['storyCreatorCreateActorRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorCreateActorRequest',
                'Required parameter "storyCreatorCreateActorRequest" was null or undefined when calling createNewActorStoryCreatorStoriesStoryIdActorNewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/stories/{story_id}/actor/new`.replace(`{${"story_id"}}`, encodeURIComponent(String(requestParameters['storyId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorCreateActorRequestToJSON(requestParameters['storyCreatorCreateActorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorActorResponseFromJSON(jsonValue));
    }

    /**
     * Create New Actor
     */
    async createNewActorStoryCreatorStoriesStoryIdActorNewPost(requestParameters: CreateNewActorStoryCreatorStoriesStoryIdActorNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorActorResponse> {
        const response = await this.createNewActorStoryCreatorStoriesStoryIdActorNewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * **Creates new story with first episode and adds default Cast to the story consisting of 3 actors: \'main-character\' created from a chatbot, \'user\' and \'narrator\'**
     * Create new story
     */
    async createStoryStoryCreatorStoriesPostRaw(requestParameters: CreateStoryStoryCreatorStoriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorCreateStoryResponse>> {
        if (requestParameters['storyCreatorCreateStoryRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorCreateStoryRequest',
                'Required parameter "storyCreatorCreateStoryRequest" was null or undefined when calling createStoryStoryCreatorStoriesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/stories`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorCreateStoryRequestToJSON(requestParameters['storyCreatorCreateStoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorCreateStoryResponseFromJSON(jsonValue));
    }

    /**
     * **Creates new story with first episode and adds default Cast to the story consisting of 3 actors: \'main-character\' created from a chatbot, \'user\' and \'narrator\'**
     * Create new story
     */
    async createStoryStoryCreatorStoriesPost(requestParameters: CreateStoryStoryCreatorStoriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorCreateStoryResponse> {
        const response = await this.createStoryStoryCreatorStoriesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Actor
     */
    async deleteActorStoryCreatorActorsActorIdDeleteRaw(requestParameters: DeleteActorStoryCreatorActorsActorIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['actorId'] == null) {
            throw new runtime.RequiredError(
                'actorId',
                'Required parameter "actorId" was null or undefined when calling deleteActorStoryCreatorActorsActorIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/actors/{actor_id}`.replace(`{${"actor_id"}}`, encodeURIComponent(String(requestParameters['actorId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Actor
     */
    async deleteActorStoryCreatorActorsActorIdDelete(requestParameters: DeleteActorStoryCreatorActorsActorIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteActorStoryCreatorActorsActorIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Delete Episode
     */
    async deleteEpisodeStoryCreatorEpisodesEpisodeIdDeleteRaw(requestParameters: DeleteEpisodeStoryCreatorEpisodesEpisodeIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling deleteEpisodeStoryCreatorEpisodesEpisodeIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Episode
     */
    async deleteEpisodeStoryCreatorEpisodesEpisodeIdDelete(requestParameters: DeleteEpisodeStoryCreatorEpisodesEpisodeIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEpisodeStoryCreatorEpisodesEpisodeIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Delete Story
     */
    async deleteStoryStoryCreatorStoriesStoryIdDeleteRaw(requestParameters: DeleteStoryStoryCreatorStoriesStoryIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['storyId'] == null) {
            throw new runtime.RequiredError(
                'storyId',
                'Required parameter "storyId" was null or undefined when calling deleteStoryStoryCreatorStoriesStoryIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/stories/{story_id}`.replace(`{${"story_id"}}`, encodeURIComponent(String(requestParameters['storyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Story
     */
    async deleteStoryStoryCreatorStoriesStoryIdDelete(requestParameters: DeleteStoryStoryCreatorStoriesStoryIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteStoryStoryCreatorStoriesStoryIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Finish Episode
     */
    async finishEpisodeStoryCreatorEpisodesEpisodeIdFinishPostRaw(requestParameters: FinishEpisodeStoryCreatorEpisodesEpisodeIdFinishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling finishEpisodeStoryCreatorEpisodesEpisodeIdFinishPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}/finish`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Finish Episode
     */
    async finishEpisodeStoryCreatorEpisodesEpisodeIdFinishPost(requestParameters: FinishEpisodeStoryCreatorEpisodesEpisodeIdFinishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.finishEpisodeStoryCreatorEpisodesEpisodeIdFinishPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Avatar
     */
    async generateAvatarStoryCreatorStoriesStoryIdActorAvatarPostRaw(requestParameters: GenerateAvatarStoryCreatorStoriesStoryIdActorAvatarPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostImagenResponse>> {
        if (requestParameters['storyId'] == null) {
            throw new runtime.RequiredError(
                'storyId',
                'Required parameter "storyId" was null or undefined when calling generateAvatarStoryCreatorStoriesStoryIdActorAvatarPost().'
            );
        }

        if (requestParameters['storyCreatorGenerateAvatarRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorGenerateAvatarRequest',
                'Required parameter "storyCreatorGenerateAvatarRequest" was null or undefined when calling generateAvatarStoryCreatorStoriesStoryIdActorAvatarPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/stories/{story_id}/actor/avatar`.replace(`{${"story_id"}}`, encodeURIComponent(String(requestParameters['storyId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorGenerateAvatarRequestToJSON(requestParameters['storyCreatorGenerateAvatarRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostImagenResponseFromJSON(jsonValue));
    }

    /**
     * Generate Avatar
     */
    async generateAvatarStoryCreatorStoriesStoryIdActorAvatarPost(requestParameters: GenerateAvatarStoryCreatorStoriesStoryIdActorAvatarPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostImagenResponse> {
        const response = await this.generateAvatarStoryCreatorStoriesStoryIdActorAvatarPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Current Episode Version
     */
    async getCurrentEpisodeVersionStoryCreatorEpisodesEpisodeIdCurrentGetRaw(requestParameters: GetCurrentEpisodeVersionStoryCreatorEpisodesEpisodeIdCurrentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorEpisodeWithStoryAndPanelsResponse>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling getCurrentEpisodeVersionStoryCreatorEpisodesEpisodeIdCurrentGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}/current`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorEpisodeWithStoryAndPanelsResponseFromJSON(jsonValue));
    }

    /**
     * Get Current Episode Version
     */
    async getCurrentEpisodeVersionStoryCreatorEpisodesEpisodeIdCurrentGet(requestParameters: GetCurrentEpisodeVersionStoryCreatorEpisodesEpisodeIdCurrentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorEpisodeWithStoryAndPanelsResponse> {
        const response = await this.getCurrentEpisodeVersionStoryCreatorEpisodesEpisodeIdCurrentGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Episode
     */
    async getEpisodeStoryCreatorEpisodesEpisodeIdGetRaw(requestParameters: GetEpisodeStoryCreatorEpisodesEpisodeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorEpisodeWithStoryAndPanelsResponse>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling getEpisodeStoryCreatorEpisodesEpisodeIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorEpisodeWithStoryAndPanelsResponseFromJSON(jsonValue));
    }

    /**
     * Get Episode
     */
    async getEpisodeStoryCreatorEpisodesEpisodeIdGet(requestParameters: GetEpisodeStoryCreatorEpisodesEpisodeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorEpisodeWithStoryAndPanelsResponse> {
        const response = await this.getEpisodeStoryCreatorEpisodesEpisodeIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import Actor
     */
    async importActorStoryCreatorStoriesStoryIdActorImportPostRaw(requestParameters: ImportActorStoryCreatorStoriesStoryIdActorImportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorActorResponse>> {
        if (requestParameters['storyId'] == null) {
            throw new runtime.RequiredError(
                'storyId',
                'Required parameter "storyId" was null or undefined when calling importActorStoryCreatorStoriesStoryIdActorImportPost().'
            );
        }

        if (requestParameters['storyCreatorImportActorRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorImportActorRequest',
                'Required parameter "storyCreatorImportActorRequest" was null or undefined when calling importActorStoryCreatorStoriesStoryIdActorImportPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/stories/{story_id}/actor/import`.replace(`{${"story_id"}}`, encodeURIComponent(String(requestParameters['storyId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorImportActorRequestToJSON(requestParameters['storyCreatorImportActorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorActorResponseFromJSON(jsonValue));
    }

    /**
     * Import Actor
     */
    async importActorStoryCreatorStoriesStoryIdActorImportPost(requestParameters: ImportActorStoryCreatorStoriesStoryIdActorImportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorActorResponse> {
        const response = await this.importActorStoryCreatorStoriesStoryIdActorImportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Actors
     */
    async listActorsStoryCreatorStoriesStoryIdActorsGetRaw(requestParameters: ListActorsStoryCreatorStoriesStoryIdActorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorActorListResponse>> {
        if (requestParameters['storyId'] == null) {
            throw new runtime.RequiredError(
                'storyId',
                'Required parameter "storyId" was null or undefined when calling listActorsStoryCreatorStoriesStoryIdActorsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/stories/{story_id}/actors`.replace(`{${"story_id"}}`, encodeURIComponent(String(requestParameters['storyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorActorListResponseFromJSON(jsonValue));
    }

    /**
     * List Actors
     */
    async listActorsStoryCreatorStoriesStoryIdActorsGet(requestParameters: ListActorsStoryCreatorStoriesStoryIdActorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorActorListResponse> {
        const response = await this.listActorsStoryCreatorStoriesStoryIdActorsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Episodes
     */
    async listEpisodesStoryCreatorStoriesStoryIdEpisodesGetRaw(requestParameters: ListEpisodesStoryCreatorStoriesStoryIdEpisodesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorEpisodeListResponse>> {
        if (requestParameters['storyId'] == null) {
            throw new runtime.RequiredError(
                'storyId',
                'Required parameter "storyId" was null or undefined when calling listEpisodesStoryCreatorStoriesStoryIdEpisodesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/stories/{story_id}/episodes`.replace(`{${"story_id"}}`, encodeURIComponent(String(requestParameters['storyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorEpisodeListResponseFromJSON(jsonValue));
    }

    /**
     * List Episodes
     */
    async listEpisodesStoryCreatorStoriesStoryIdEpisodesGet(requestParameters: ListEpisodesStoryCreatorStoriesStoryIdEpisodesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorEpisodeListResponse> {
        const response = await this.listEpisodesStoryCreatorStoriesStoryIdEpisodesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Stories
     */
    async listStoriesStoryCreatorStoriesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorStoryListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/stories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorStoryListResponseFromJSON(jsonValue));
    }

    /**
     * List Stories
     */
    async listStoriesStoryCreatorStoriesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorStoryListResponse> {
        const response = await this.listStoriesStoryCreatorStoriesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Lock Episode
     */
    async lockEpisodeStoryCreatorEpisodesEpisodeIdLockPatchRaw(requestParameters: LockEpisodeStoryCreatorEpisodesEpisodeIdLockPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling lockEpisodeStoryCreatorEpisodesEpisodeIdLockPatch().'
            );
        }

        if (requestParameters['storyCreatorLockEpisodeRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorLockEpisodeRequest',
                'Required parameter "storyCreatorLockEpisodeRequest" was null or undefined when calling lockEpisodeStoryCreatorEpisodesEpisodeIdLockPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}/lock`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorLockEpisodeRequestToJSON(requestParameters['storyCreatorLockEpisodeRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Lock Episode
     */
    async lockEpisodeStoryCreatorEpisodesEpisodeIdLockPatch(requestParameters: LockEpisodeStoryCreatorEpisodesEpisodeIdLockPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.lockEpisodeStoryCreatorEpisodesEpisodeIdLockPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Purchase Episode
     */
    async purchaseEpisodeStoryCreatorEpisodesEpisodeIdPurchasePostRaw(requestParameters: PurchaseEpisodeStoryCreatorEpisodesEpisodeIdPurchasePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorPurchaseEpisodeResponse>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling purchaseEpisodeStoryCreatorEpisodesEpisodeIdPurchasePost().'
            );
        }

        if (requestParameters['storyCreatorPurchaseEpisodeRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorPurchaseEpisodeRequest',
                'Required parameter "storyCreatorPurchaseEpisodeRequest" was null or undefined when calling purchaseEpisodeStoryCreatorEpisodesEpisodeIdPurchasePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}/purchase`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorPurchaseEpisodeRequestToJSON(requestParameters['storyCreatorPurchaseEpisodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorPurchaseEpisodeResponseFromJSON(jsonValue));
    }

    /**
     * Purchase Episode
     */
    async purchaseEpisodeStoryCreatorEpisodesEpisodeIdPurchasePost(requestParameters: PurchaseEpisodeStoryCreatorEpisodesEpisodeIdPurchasePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorPurchaseEpisodeResponse> {
        const response = await this.purchaseEpisodeStoryCreatorEpisodesEpisodeIdPurchasePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rate Episode
     */
    async rateEpisodeStoryCreatorEpisodesEpisodeIdRatingPostRaw(requestParameters: RateEpisodeStoryCreatorEpisodesEpisodeIdRatingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorEpisodeResponse>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling rateEpisodeStoryCreatorEpisodesEpisodeIdRatingPost().'
            );
        }

        if (requestParameters['storyCreatorRateEpisodeRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorRateEpisodeRequest',
                'Required parameter "storyCreatorRateEpisodeRequest" was null or undefined when calling rateEpisodeStoryCreatorEpisodesEpisodeIdRatingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}/rating`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorRateEpisodeRequestToJSON(requestParameters['storyCreatorRateEpisodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorEpisodeResponseFromJSON(jsonValue));
    }

    /**
     * Rate Episode
     */
    async rateEpisodeStoryCreatorEpisodesEpisodeIdRatingPost(requestParameters: RateEpisodeStoryCreatorEpisodesEpisodeIdRatingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorEpisodeResponse> {
        const response = await this.rateEpisodeStoryCreatorEpisodesEpisodeIdRatingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save Episode
     */
    async saveEpisodeStoryCreatorEpisodesEpisodeIdPutRaw(requestParameters: SaveEpisodeStoryCreatorEpisodesEpisodeIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorEpisodeWithPanelsResponse>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling saveEpisodeStoryCreatorEpisodesEpisodeIdPut().'
            );
        }

        if (requestParameters['storyCreatorSaveEpisodeRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorSaveEpisodeRequest',
                'Required parameter "storyCreatorSaveEpisodeRequest" was null or undefined when calling saveEpisodeStoryCreatorEpisodesEpisodeIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorSaveEpisodeRequestToJSON(requestParameters['storyCreatorSaveEpisodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorEpisodeWithPanelsResponseFromJSON(jsonValue));
    }

    /**
     * Save Episode
     */
    async saveEpisodeStoryCreatorEpisodesEpisodeIdPut(requestParameters: SaveEpisodeStoryCreatorEpisodesEpisodeIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorEpisodeWithPanelsResponse> {
        const response = await this.saveEpisodeStoryCreatorEpisodesEpisodeIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlock Episode
     */
    async unlockEpisodeStoryCreatorEpisodesEpisodeIdLockDeleteRaw(requestParameters: UnlockEpisodeStoryCreatorEpisodesEpisodeIdLockDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling unlockEpisodeStoryCreatorEpisodesEpisodeIdLockDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}/lock`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Unlock Episode
     */
    async unlockEpisodeStoryCreatorEpisodesEpisodeIdLockDelete(requestParameters: UnlockEpisodeStoryCreatorEpisodesEpisodeIdLockDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.unlockEpisodeStoryCreatorEpisodesEpisodeIdLockDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Actor
     */
    async updateActorStoryCreatorActorsActorIdPatchRaw(requestParameters: UpdateActorStoryCreatorActorsActorIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorActorResponse>> {
        if (requestParameters['actorId'] == null) {
            throw new runtime.RequiredError(
                'actorId',
                'Required parameter "actorId" was null or undefined when calling updateActorStoryCreatorActorsActorIdPatch().'
            );
        }

        if (requestParameters['storyCreatorUpdateActorRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorUpdateActorRequest',
                'Required parameter "storyCreatorUpdateActorRequest" was null or undefined when calling updateActorStoryCreatorActorsActorIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/actors/{actor_id}`.replace(`{${"actor_id"}}`, encodeURIComponent(String(requestParameters['actorId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorUpdateActorRequestToJSON(requestParameters['storyCreatorUpdateActorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorActorResponseFromJSON(jsonValue));
    }

    /**
     * Update Actor
     */
    async updateActorStoryCreatorActorsActorIdPatch(requestParameters: UpdateActorStoryCreatorActorsActorIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorActorResponse> {
        const response = await this.updateActorStoryCreatorActorsActorIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Episode
     */
    async updateEpisodeStoryCreatorEpisodesEpisodeIdPatchRaw(requestParameters: UpdateEpisodeStoryCreatorEpisodesEpisodeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorEpisodeResponse>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling updateEpisodeStoryCreatorEpisodesEpisodeIdPatch().'
            );
        }

        if (requestParameters['storyCreatorUpdateEpisodeRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorUpdateEpisodeRequest',
                'Required parameter "storyCreatorUpdateEpisodeRequest" was null or undefined when calling updateEpisodeStoryCreatorEpisodesEpisodeIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorUpdateEpisodeRequestToJSON(requestParameters['storyCreatorUpdateEpisodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorEpisodeResponseFromJSON(jsonValue));
    }

    /**
     * Update Episode
     */
    async updateEpisodeStoryCreatorEpisodesEpisodeIdPatch(requestParameters: UpdateEpisodeStoryCreatorEpisodesEpisodeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorEpisodeResponse> {
        const response = await this.updateEpisodeStoryCreatorEpisodesEpisodeIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Episode Visibility
     */
    async updateEpisodeVisibilityStoryCreatorEpisodesEpisodeIdVisibilityPatchRaw(requestParameters: UpdateEpisodeVisibilityStoryCreatorEpisodesEpisodeIdVisibilityPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['episodeId'] == null) {
            throw new runtime.RequiredError(
                'episodeId',
                'Required parameter "episodeId" was null or undefined when calling updateEpisodeVisibilityStoryCreatorEpisodesEpisodeIdVisibilityPatch().'
            );
        }

        if (requestParameters['storyCreatorUpdateEpisodeVisibilityRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorUpdateEpisodeVisibilityRequest',
                'Required parameter "storyCreatorUpdateEpisodeVisibilityRequest" was null or undefined when calling updateEpisodeVisibilityStoryCreatorEpisodesEpisodeIdVisibilityPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/episodes/{episode_id}/visibility`.replace(`{${"episode_id"}}`, encodeURIComponent(String(requestParameters['episodeId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorUpdateEpisodeVisibilityRequestToJSON(requestParameters['storyCreatorUpdateEpisodeVisibilityRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Episode Visibility
     */
    async updateEpisodeVisibilityStoryCreatorEpisodesEpisodeIdVisibilityPatch(requestParameters: UpdateEpisodeVisibilityStoryCreatorEpisodesEpisodeIdVisibilityPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateEpisodeVisibilityStoryCreatorEpisodesEpisodeIdVisibilityPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Story
     */
    async updateStoryStoryCreatorStoriesStoryIdPatchRaw(requestParameters: UpdateStoryStoryCreatorStoriesStoryIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoryCreatorStoryResponse>> {
        if (requestParameters['storyId'] == null) {
            throw new runtime.RequiredError(
                'storyId',
                'Required parameter "storyId" was null or undefined when calling updateStoryStoryCreatorStoriesStoryIdPatch().'
            );
        }

        if (requestParameters['storyCreatorUpdateStoryRequest'] == null) {
            throw new runtime.RequiredError(
                'storyCreatorUpdateStoryRequest',
                'Required parameter "storyCreatorUpdateStoryRequest" was null or undefined when calling updateStoryStoryCreatorStoriesStoryIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/story-creator/stories/{story_id}`.replace(`{${"story_id"}}`, encodeURIComponent(String(requestParameters['storyId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: StoryCreatorUpdateStoryRequestToJSON(requestParameters['storyCreatorUpdateStoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoryCreatorStoryResponseFromJSON(jsonValue));
    }

    /**
     * Update Story
     */
    async updateStoryStoryCreatorStoriesStoryIdPatch(requestParameters: UpdateStoryStoryCreatorStoriesStoryIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoryCreatorStoryResponse> {
        const response = await this.updateStoryStoryCreatorStoriesStoryIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
