/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExtendVideoPayload,
  GetVideoGenerationTagsResponse,
  HTTPValidationError,
  ImageToVideoFromChatPayload,
  ImageToVideoRecommendationPayload,
  ImageToVideoRequest,
  LastVideoFrameResponse,
  ResponseGetWanTaskStatusVideoWanTaskTaskIdGet,
  VideoConfigResponse,
  VideoFromChatResponse,
  VideoResolution,
  WanExtendVideoCompletionPayload,
  WanImageToVideoCompletionPayload,
  WanImageToVideoResponse,
} from '../models/index';
import {
    ExtendVideoPayloadFromJSON,
    ExtendVideoPayloadToJSON,
    GetVideoGenerationTagsResponseFromJSON,
    GetVideoGenerationTagsResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ImageToVideoFromChatPayloadFromJSON,
    ImageToVideoFromChatPayloadToJSON,
    ImageToVideoRecommendationPayloadFromJSON,
    ImageToVideoRecommendationPayloadToJSON,
    ImageToVideoRequestFromJSON,
    ImageToVideoRequestToJSON,
    LastVideoFrameResponseFromJSON,
    LastVideoFrameResponseToJSON,
    ResponseGetWanTaskStatusVideoWanTaskTaskIdGetFromJSON,
    ResponseGetWanTaskStatusVideoWanTaskTaskIdGetToJSON,
    VideoConfigResponseFromJSON,
    VideoConfigResponseToJSON,
    VideoFromChatResponseFromJSON,
    VideoFromChatResponseToJSON,
    VideoResolutionFromJSON,
    VideoResolutionToJSON,
    WanExtendVideoCompletionPayloadFromJSON,
    WanExtendVideoCompletionPayloadToJSON,
    WanImageToVideoCompletionPayloadFromJSON,
    WanImageToVideoCompletionPayloadToJSON,
    WanImageToVideoResponseFromJSON,
    WanImageToVideoResponseToJSON,
} from '../models/index';

export interface AttachmentVideoVideoIdAttachmentGetRequest {
    videoId: string;
    videoName: string;
}

export interface CallbackVideoCallbackGenerationIdPostRequest {
    generationId: string;
    status: CallbackVideoCallbackGenerationIdPostStatusEnum;
    errorMessage?: string | null;
}

export interface ChatCallbackVideoCallbackChatGenerationIdPostRequest {
    generationId: string;
    status: ChatCallbackVideoCallbackChatGenerationIdPostStatusEnum;
    errorMessage?: string | null;
}

export interface CompleteWanExtendVideoVideoWanExtendCompletePostRequest {
    wanExtendVideoCompletionPayload: WanExtendVideoCompletionPayload;
}

export interface CompleteWanVideoVideoWanCompletePostRequest {
    wanImageToVideoCompletionPayload: WanImageToVideoCompletionPayload;
}

export interface DeleteVideoVideoVideoIdDeleteRequest {
    videoId: string;
}

export interface ExtendCallbackVideoExtendCallbackGenerationIdPostRequest {
    generationId: string;
    status: ExtendCallbackVideoExtendCallbackGenerationIdPostStatusEnum;
    errorMessage?: string | null;
}

export interface ExtendVideoVideoExtendPostRequest {
    extendVideoPayload: ExtendVideoPayload;
}

export interface GenerateVideoDescriptionVideoRecommendationPostRequest {
    imageToVideoRecommendationPayload: ImageToVideoRecommendationPayload;
}

export interface GenerateVideoFromChatVideoChatPostRequest {
    imageToVideoFromChatPayload: ImageToVideoFromChatPayload;
}

export interface GenerateVideoVideoPostRequest {
    imageToVideoRequest: ImageToVideoRequest;
}

export interface GenerateWanVideoDirectVideoWanGeneratePostRequest {
    image: Blob;
    prompt: string;
    audio?: Blob | null;
    negativePrompt?: string | null;
    provider?: GenerateWanVideoDirectVideoWanGeneratePostProviderEnum;
    modelName?: string | null;
    resolution?: VideoResolution;
    duration?: number;
    seed?: number | null;
    audioGeneration?: boolean;
}

export interface GenerationTagsVideoVideoIdTagsGetRequest {
    videoId: string;
}

export interface GetWanTaskStatusVideoWanTaskTaskIdGetRequest {
    taskId: string;
    provider?: GetWanTaskStatusVideoWanTaskTaskIdGetProviderEnum;
}

export interface VideoLastFrameVideoVideoIdLastFrameGetRequest {
    videoId: string;
}

/**
 * 
 */
export class VideoApi extends runtime.BaseAPI {

    /**
     * Attachment
     */
    async attachmentVideoVideoIdAttachmentGetRaw(requestParameters: AttachmentVideoVideoIdAttachmentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling attachmentVideoVideoIdAttachmentGet().'
            );
        }

        if (requestParameters['videoName'] == null) {
            throw new runtime.RequiredError(
                'videoName',
                'Required parameter "videoName" was null or undefined when calling attachmentVideoVideoIdAttachmentGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['videoName'] != null) {
            queryParameters['video_name'] = requestParameters['videoName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/video/{video_id}/attachment`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Attachment
     */
    async attachmentVideoVideoIdAttachmentGet(requestParameters: AttachmentVideoVideoIdAttachmentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.attachmentVideoVideoIdAttachmentGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Callback
     */
    async callbackVideoCallbackGenerationIdPostRaw(requestParameters: CallbackVideoCallbackGenerationIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['generationId'] == null) {
            throw new runtime.RequiredError(
                'generationId',
                'Required parameter "generationId" was null or undefined when calling callbackVideoCallbackGenerationIdPost().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling callbackVideoCallbackGenerationIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }

        if (requestParameters['errorMessage'] != null) {
            formParams.append('error_message', requestParameters['errorMessage'] as any);
        }

        const response = await this.request({
            path: `/video/callback/{generation_id}`.replace(`{${"generation_id"}}`, encodeURIComponent(String(requestParameters['generationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Callback
     */
    async callbackVideoCallbackGenerationIdPost(requestParameters: CallbackVideoCallbackGenerationIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.callbackVideoCallbackGenerationIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Chat Callback
     */
    async chatCallbackVideoCallbackChatGenerationIdPostRaw(requestParameters: ChatCallbackVideoCallbackChatGenerationIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['generationId'] == null) {
            throw new runtime.RequiredError(
                'generationId',
                'Required parameter "generationId" was null or undefined when calling chatCallbackVideoCallbackChatGenerationIdPost().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling chatCallbackVideoCallbackChatGenerationIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }

        if (requestParameters['errorMessage'] != null) {
            formParams.append('error_message', requestParameters['errorMessage'] as any);
        }

        const response = await this.request({
            path: `/video/callback/chat/{generation_id}`.replace(`{${"generation_id"}}`, encodeURIComponent(String(requestParameters['generationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Chat Callback
     */
    async chatCallbackVideoCallbackChatGenerationIdPost(requestParameters: ChatCallbackVideoCallbackChatGenerationIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.chatCallbackVideoCallbackChatGenerationIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Complete Wan Extend Video
     */
    async completeWanExtendVideoVideoWanExtendCompletePostRaw(requestParameters: CompleteWanExtendVideoVideoWanExtendCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['wanExtendVideoCompletionPayload'] == null) {
            throw new runtime.RequiredError(
                'wanExtendVideoCompletionPayload',
                'Required parameter "wanExtendVideoCompletionPayload" was null or undefined when calling completeWanExtendVideoVideoWanExtendCompletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/video/wan/extend/complete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WanExtendVideoCompletionPayloadToJSON(requestParameters['wanExtendVideoCompletionPayload']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Complete Wan Extend Video
     */
    async completeWanExtendVideoVideoWanExtendCompletePost(requestParameters: CompleteWanExtendVideoVideoWanExtendCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.completeWanExtendVideoVideoWanExtendCompletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Complete Wan Video
     */
    async completeWanVideoVideoWanCompletePostRaw(requestParameters: CompleteWanVideoVideoWanCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['wanImageToVideoCompletionPayload'] == null) {
            throw new runtime.RequiredError(
                'wanImageToVideoCompletionPayload',
                'Required parameter "wanImageToVideoCompletionPayload" was null or undefined when calling completeWanVideoVideoWanCompletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/video/wan/complete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WanImageToVideoCompletionPayloadToJSON(requestParameters['wanImageToVideoCompletionPayload']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Complete Wan Video
     */
    async completeWanVideoVideoWanCompletePost(requestParameters: CompleteWanVideoVideoWanCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.completeWanVideoVideoWanCompletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Video
     */
    async deleteVideoVideoVideoIdDeleteRaw(requestParameters: DeleteVideoVideoVideoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideoVideoVideoIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/video/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Video
     */
    async deleteVideoVideoVideoIdDelete(requestParameters: DeleteVideoVideoVideoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteVideoVideoVideoIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Extend Callback
     */
    async extendCallbackVideoExtendCallbackGenerationIdPostRaw(requestParameters: ExtendCallbackVideoExtendCallbackGenerationIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['generationId'] == null) {
            throw new runtime.RequiredError(
                'generationId',
                'Required parameter "generationId" was null or undefined when calling extendCallbackVideoExtendCallbackGenerationIdPost().'
            );
        }

        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling extendCallbackVideoExtendCallbackGenerationIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['status'] != null) {
            formParams.append('status', requestParameters['status'] as any);
        }

        if (requestParameters['errorMessage'] != null) {
            formParams.append('error_message', requestParameters['errorMessage'] as any);
        }

        const response = await this.request({
            path: `/video/extend/callback/{generation_id}`.replace(`{${"generation_id"}}`, encodeURIComponent(String(requestParameters['generationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Extend Callback
     */
    async extendCallbackVideoExtendCallbackGenerationIdPost(requestParameters: ExtendCallbackVideoExtendCallbackGenerationIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.extendCallbackVideoExtendCallbackGenerationIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Extend Video
     */
    async extendVideoVideoExtendPostRaw(requestParameters: ExtendVideoVideoExtendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['extendVideoPayload'] == null) {
            throw new runtime.RequiredError(
                'extendVideoPayload',
                'Required parameter "extendVideoPayload" was null or undefined when calling extendVideoVideoExtendPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/video/extend`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExtendVideoPayloadToJSON(requestParameters['extendVideoPayload']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Extend Video
     */
    async extendVideoVideoExtendPost(requestParameters: ExtendVideoVideoExtendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.extendVideoVideoExtendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Video Description
     */
    async generateVideoDescriptionVideoRecommendationPostRaw(requestParameters: GenerateVideoDescriptionVideoRecommendationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['imageToVideoRecommendationPayload'] == null) {
            throw new runtime.RequiredError(
                'imageToVideoRecommendationPayload',
                'Required parameter "imageToVideoRecommendationPayload" was null or undefined when calling generateVideoDescriptionVideoRecommendationPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/video/recommendation`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageToVideoRecommendationPayloadToJSON(requestParameters['imageToVideoRecommendationPayload']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate Video Description
     */
    async generateVideoDescriptionVideoRecommendationPost(requestParameters: GenerateVideoDescriptionVideoRecommendationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateVideoDescriptionVideoRecommendationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Video From Chat
     */
    async generateVideoFromChatVideoChatPostRaw(requestParameters: GenerateVideoFromChatVideoChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoFromChatResponse>> {
        if (requestParameters['imageToVideoFromChatPayload'] == null) {
            throw new runtime.RequiredError(
                'imageToVideoFromChatPayload',
                'Required parameter "imageToVideoFromChatPayload" was null or undefined when calling generateVideoFromChatVideoChatPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/video/chat`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageToVideoFromChatPayloadToJSON(requestParameters['imageToVideoFromChatPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromChatResponseFromJSON(jsonValue));
    }

    /**
     * Generate Video From Chat
     */
    async generateVideoFromChatVideoChatPost(requestParameters: GenerateVideoFromChatVideoChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoFromChatResponse> {
        const response = await this.generateVideoFromChatVideoChatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Video
     */
    async generateVideoVideoPostRaw(requestParameters: GenerateVideoVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['imageToVideoRequest'] == null) {
            throw new runtime.RequiredError(
                'imageToVideoRequest',
                'Required parameter "imageToVideoRequest" was null or undefined when calling generateVideoVideoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/video`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageToVideoRequestToJSON(requestParameters['imageToVideoRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate Video
     */
    async generateVideoVideoPost(requestParameters: GenerateVideoVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateVideoVideoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Wan Video Direct
     */
    async generateWanVideoDirectVideoWanGeneratePostRaw(requestParameters: GenerateWanVideoDirectVideoWanGeneratePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WanImageToVideoResponse>> {
        if (requestParameters['image'] == null) {
            throw new runtime.RequiredError(
                'image',
                'Required parameter "image" was null or undefined when calling generateWanVideoDirectVideoWanGeneratePost().'
            );
        }

        if (requestParameters['prompt'] == null) {
            throw new runtime.RequiredError(
                'prompt',
                'Required parameter "prompt" was null or undefined when calling generateWanVideoDirectVideoWanGeneratePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['image'] != null) {
            formParams.append('image', requestParameters['image'] as any);
        }

        if (requestParameters['audio'] != null) {
            formParams.append('audio', requestParameters['audio'] as any);
        }

        if (requestParameters['prompt'] != null) {
            formParams.append('prompt', requestParameters['prompt'] as any);
        }

        if (requestParameters['negativePrompt'] != null) {
            formParams.append('negative_prompt', requestParameters['negativePrompt'] as any);
        }

        if (requestParameters['provider'] != null) {
            formParams.append('provider', requestParameters['provider'] as any);
        }

        if (requestParameters['modelName'] != null) {
            formParams.append('model_name', requestParameters['modelName'] as any);
        }

        if (requestParameters['resolution'] != null) {
            formParams.append('resolution', requestParameters['resolution'] as any);
        }

        if (requestParameters['duration'] != null) {
            formParams.append('duration', requestParameters['duration'] as any);
        }

        if (requestParameters['seed'] != null) {
            formParams.append('seed', requestParameters['seed'] as any);
        }

        if (requestParameters['audioGeneration'] != null) {
            formParams.append('audio_generation', requestParameters['audioGeneration'] as any);
        }

        const response = await this.request({
            path: `/video/wan/generate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WanImageToVideoResponseFromJSON(jsonValue));
    }

    /**
     * Generate Wan Video Direct
     */
    async generateWanVideoDirectVideoWanGeneratePost(requestParameters: GenerateWanVideoDirectVideoWanGeneratePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WanImageToVideoResponse> {
        const response = await this.generateWanVideoDirectVideoWanGeneratePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generation Tags
     */
    async generationTagsVideoVideoIdTagsGetRaw(requestParameters: GenerationTagsVideoVideoIdTagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVideoGenerationTagsResponse>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generationTagsVideoVideoIdTagsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/video/{video_id}/tags`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetVideoGenerationTagsResponseFromJSON(jsonValue));
    }

    /**
     * Generation Tags
     */
    async generationTagsVideoVideoIdTagsGet(requestParameters: GenerationTagsVideoVideoIdTagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVideoGenerationTagsResponse> {
        const response = await this.generationTagsVideoVideoIdTagsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Video Config
     */
    async getVideoConfigVideoConfigGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoConfigResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/video/config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get Video Config
     */
    async getVideoConfigVideoConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoConfigResponse> {
        const response = await this.getVideoConfigVideoConfigGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Wan Task Status
     */
    async getWanTaskStatusVideoWanTaskTaskIdGetRaw(requestParameters: GetWanTaskStatusVideoWanTaskTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseGetWanTaskStatusVideoWanTaskTaskIdGet>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getWanTaskStatusVideoWanTaskTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/video/wan/task/{task_id}`.replace(`{${"task_id"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseGetWanTaskStatusVideoWanTaskTaskIdGetFromJSON(jsonValue));
    }

    /**
     * Get Wan Task Status
     */
    async getWanTaskStatusVideoWanTaskTaskIdGet(requestParameters: GetWanTaskStatusVideoWanTaskTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseGetWanTaskStatusVideoWanTaskTaskIdGet> {
        const response = await this.getWanTaskStatusVideoWanTaskTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Video Last Frame
     */
    async videoLastFrameVideoVideoIdLastFrameGetRaw(requestParameters: VideoLastFrameVideoVideoIdLastFrameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LastVideoFrameResponse>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videoLastFrameVideoVideoIdLastFrameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/video/{video_id}/last_frame`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LastVideoFrameResponseFromJSON(jsonValue));
    }

    /**
     * Video Last Frame
     */
    async videoLastFrameVideoVideoIdLastFrameGet(requestParameters: VideoLastFrameVideoVideoIdLastFrameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LastVideoFrameResponse> {
        const response = await this.videoLastFrameVideoVideoIdLastFrameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CallbackVideoCallbackGenerationIdPostStatusEnum = {
    Finished: 'finished',
    Failed: 'failed'
} as const;
export type CallbackVideoCallbackGenerationIdPostStatusEnum = typeof CallbackVideoCallbackGenerationIdPostStatusEnum[keyof typeof CallbackVideoCallbackGenerationIdPostStatusEnum];
/**
 * @export
 */
export const ChatCallbackVideoCallbackChatGenerationIdPostStatusEnum = {
    Finished: 'finished',
    Failed: 'failed'
} as const;
export type ChatCallbackVideoCallbackChatGenerationIdPostStatusEnum = typeof ChatCallbackVideoCallbackChatGenerationIdPostStatusEnum[keyof typeof ChatCallbackVideoCallbackChatGenerationIdPostStatusEnum];
/**
 * @export
 */
export const ExtendCallbackVideoExtendCallbackGenerationIdPostStatusEnum = {
    Finished: 'finished',
    Failed: 'failed'
} as const;
export type ExtendCallbackVideoExtendCallbackGenerationIdPostStatusEnum = typeof ExtendCallbackVideoExtendCallbackGenerationIdPostStatusEnum[keyof typeof ExtendCallbackVideoExtendCallbackGenerationIdPostStatusEnum];
/**
 * @export
 */
export const GenerateWanVideoDirectVideoWanGeneratePostProviderEnum = {
    Mulerouter: 'mulerouter',
    Wan: 'wan',
    Kling: 'kling'
} as const;
export type GenerateWanVideoDirectVideoWanGeneratePostProviderEnum = typeof GenerateWanVideoDirectVideoWanGeneratePostProviderEnum[keyof typeof GenerateWanVideoDirectVideoWanGeneratePostProviderEnum];
/**
 * @export
 */
export const GetWanTaskStatusVideoWanTaskTaskIdGetProviderEnum = {
    Mulerouter: 'mulerouter',
    Wancloud: 'wancloud'
} as const;
export type GetWanTaskStatusVideoWanTaskTaskIdGetProviderEnum = typeof GetWanTaskStatusVideoWanTaskTaskIdGetProviderEnum[keyof typeof GetWanTaskStatusVideoWanTaskTaskIdGetProviderEnum];
