/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Language,
  TextToSpeechRequest,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LanguageFromJSON,
    LanguageToJSON,
    TextToSpeechRequestFromJSON,
    TextToSpeechRequestToJSON,
} from '../models/index';

export interface CreateReferenceVoiceReferencesPostRequest {
    name: string;
    audio: Blob;
    sampleAudio: Blob;
    referenceText: string;
    locale: Language;
    description?: string;
}

export interface GenerateTextToSpeechVoiceTextToSpeechPostRequest {
    textToSpeechRequest: TextToSpeechRequest;
}

export interface GenerateVoiceChatVoiceMessageMessageIdPostRequest {
    messageId: string;
}

export interface StreamVoiceStreamAudioIdGetRequest {
    audioId: string;
    serverUrl: string;
}

/**
 * 
 */
export class VoiceApi extends runtime.BaseAPI {

    /**
     * Create Reference
     */
    async createReferenceVoiceReferencesPostRaw(requestParameters: CreateReferenceVoiceReferencesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createReferenceVoiceReferencesPost().'
            );
        }

        if (requestParameters['audio'] == null) {
            throw new runtime.RequiredError(
                'audio',
                'Required parameter "audio" was null or undefined when calling createReferenceVoiceReferencesPost().'
            );
        }

        if (requestParameters['sampleAudio'] == null) {
            throw new runtime.RequiredError(
                'sampleAudio',
                'Required parameter "sampleAudio" was null or undefined when calling createReferenceVoiceReferencesPost().'
            );
        }

        if (requestParameters['referenceText'] == null) {
            throw new runtime.RequiredError(
                'referenceText',
                'Required parameter "referenceText" was null or undefined when calling createReferenceVoiceReferencesPost().'
            );
        }

        if (requestParameters['locale'] == null) {
            throw new runtime.RequiredError(
                'locale',
                'Required parameter "locale" was null or undefined when calling createReferenceVoiceReferencesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['audio'] != null) {
            formParams.append('audio', requestParameters['audio'] as any);
        }

        if (requestParameters['sampleAudio'] != null) {
            formParams.append('sample_audio', requestParameters['sampleAudio'] as any);
        }

        if (requestParameters['referenceText'] != null) {
            formParams.append('reference_text', requestParameters['referenceText'] as any);
        }

        if (requestParameters['locale'] != null) {
            formParams.append('locale', requestParameters['locale'] as any);
        }

        if (requestParameters['description'] != null) {
            formParams.append('description', requestParameters['description'] as any);
        }

        const response = await this.request({
            path: `/voice/references`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Reference
     */
    async createReferenceVoiceReferencesPost(requestParameters: CreateReferenceVoiceReferencesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createReferenceVoiceReferencesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Text To Speech
     */
    async generateTextToSpeechVoiceTextToSpeechPostRaw(requestParameters: GenerateTextToSpeechVoiceTextToSpeechPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['textToSpeechRequest'] == null) {
            throw new runtime.RequiredError(
                'textToSpeechRequest',
                'Required parameter "textToSpeechRequest" was null or undefined when calling generateTextToSpeechVoiceTextToSpeechPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/voice/text-to-speech`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TextToSpeechRequestToJSON(requestParameters['textToSpeechRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate Text To Speech
     */
    async generateTextToSpeechVoiceTextToSpeechPost(requestParameters: GenerateTextToSpeechVoiceTextToSpeechPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateTextToSpeechVoiceTextToSpeechPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Voice Chat
     */
    async generateVoiceChatVoiceMessageMessageIdPostRaw(requestParameters: GenerateVoiceChatVoiceMessageMessageIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling generateVoiceChatVoiceMessageMessageIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/voice/message/{message_id}`.replace(`{${"message_id"}}`, encodeURIComponent(String(requestParameters['messageId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate Voice Chat
     */
    async generateVoiceChatVoiceMessageMessageIdPost(requestParameters: GenerateVoiceChatVoiceMessageMessageIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateVoiceChatVoiceMessageMessageIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List References
     */
    async listReferencesVoiceReferencesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/voice/references`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List References
     */
    async listReferencesVoiceReferencesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listReferencesVoiceReferencesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Stream Text To Speech
     */
    async streamTextToSpeechVoiceStreamTextToSpeechGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/voice/stream-text-to-speech`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Stream Text To Speech
     */
    async streamTextToSpeechVoiceStreamTextToSpeechGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.streamTextToSpeechVoiceStreamTextToSpeechGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Stream
     */
    async streamVoiceStreamAudioIdGetRaw(requestParameters: StreamVoiceStreamAudioIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['audioId'] == null) {
            throw new runtime.RequiredError(
                'audioId',
                'Required parameter "audioId" was null or undefined when calling streamVoiceStreamAudioIdGet().'
            );
        }

        if (requestParameters['serverUrl'] == null) {
            throw new runtime.RequiredError(
                'serverUrl',
                'Required parameter "serverUrl" was null or undefined when calling streamVoiceStreamAudioIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['serverUrl'] != null) {
            queryParameters['server_url'] = requestParameters['serverUrl'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/voice/stream/{audio_id}`.replace(`{${"audio_id"}}`, encodeURIComponent(String(requestParameters['audioId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stream
     */
    async streamVoiceStreamAudioIdGet(requestParameters: StreamVoiceStreamAudioIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.streamVoiceStreamAudioIdGetRaw(requestParameters, initOverrides);
    }

    /**
     * Voice Mock
     */
    async voiceMockVoiceVoiceMockGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/voice/voice-mock`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Voice Mock
     */
    async voiceMockVoiceVoiceMockGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.voiceMockVoiceVoiceMockGetRaw(initOverrides);
        return await response.value();
    }

}
