/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AccessType = {
    Owner: 'owner',
    Free: 'free',
    Purchased: 'purchased',
    Locked: 'locked'
} as const;
export type AccessType = typeof AccessType[keyof typeof AccessType];


export function instanceOfAccessType(value: any): boolean {
    for (const key in AccessType) {
        if (Object.prototype.hasOwnProperty.call(AccessType, key)) {
            if (AccessType[key as keyof typeof AccessType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccessTypeFromJSON(json: any): AccessType {
    return AccessTypeFromJSONTyped(json, false);
}

export function AccessTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessType {
    return json as AccessType;
}

export function AccessTypeToJSON(value?: AccessType | null): any {
    return value as any;
}

export function AccessTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AccessType {
    return value as AccessType;
}

