/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BodyType } from './BodyType';
import {
    BodyTypeFromJSON,
    BodyTypeFromJSONTyped,
    BodyTypeToJSON,
    BodyTypeToJSONTyped,
} from './BodyType';
import type { HairColor } from './HairColor';
import {
    HairColorFromJSON,
    HairColorFromJSONTyped,
    HairColorToJSON,
    HairColorToJSONTyped,
} from './HairColor';

/**
 * 
 * @export
 * @interface AvatarLooksV2
 */
export interface AvatarLooksV2 {
    /**
     * 
     * @type {BodyType}
     * @memberof AvatarLooksV2
     */
    bodyType: BodyType;
    /**
     * 
     * @type {HairColor}
     * @memberof AvatarLooksV2
     */
    hairColor: HairColor;
}



/**
 * Check if a given object implements the AvatarLooksV2 interface.
 */
export function instanceOfAvatarLooksV2(value: object): value is AvatarLooksV2 {
    if (!('bodyType' in value) || value['bodyType'] === undefined) return false;
    if (!('hairColor' in value) || value['hairColor'] === undefined) return false;
    return true;
}

export function AvatarLooksV2FromJSON(json: any): AvatarLooksV2 {
    return AvatarLooksV2FromJSONTyped(json, false);
}

export function AvatarLooksV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarLooksV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'bodyType': BodyTypeFromJSON(json['body_type']),
        'hairColor': HairColorFromJSON(json['hair_color']),
    };
}

  export function AvatarLooksV2ToJSON(json: any): AvatarLooksV2 {
      return AvatarLooksV2ToJSONTyped(json, false);
  }

  export function AvatarLooksV2ToJSONTyped(value?: AvatarLooksV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body_type': BodyTypeToJSON(value['bodyType']),
        'hair_color': HairColorToJSON(value['hairColor']),
    };
}

