/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicUserPreview } from './PublicUserPreview';
import {
    PublicUserPreviewFromJSON,
    PublicUserPreviewFromJSONTyped,
    PublicUserPreviewToJSON,
    PublicUserPreviewToJSONTyped,
} from './PublicUserPreview';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';
import type { BadgeModel } from './BadgeModel';
import {
    BadgeModelFromJSON,
    BadgeModelFromJSONTyped,
    BadgeModelToJSON,
    BadgeModelToJSONTyped,
} from './BadgeModel';

/**
 * 
 * @export
 * @interface BadgeNotification
 */
export interface BadgeNotification {
    /**
     * 
     * @type {NotificationType}
     * @memberof BadgeNotification
     */
    notificationType?: NotificationType;
    /**
     * 
     * @type {boolean}
     * @memberof BadgeNotification
     */
    isRead: boolean;
    /**
     * 
     * @type {Date}
     * @memberof BadgeNotification
     */
    createdAt: Date;
    /**
     * 
     * @type {PublicUserPreview}
     * @memberof BadgeNotification
     */
    sender?: PublicUserPreview | null;
    /**
     * 
     * @type {BadgeModel}
     * @memberof BadgeNotification
     */
    badge: BadgeModel;
}



/**
 * Check if a given object implements the BadgeNotification interface.
 */
export function instanceOfBadgeNotification(value: object): value is BadgeNotification {
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('badge' in value) || value['badge'] === undefined) return false;
    return true;
}

export function BadgeNotificationFromJSON(json: any): BadgeNotification {
    return BadgeNotificationFromJSONTyped(json, false);
}

export function BadgeNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadgeNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationType': json['notification_type'] == null ? undefined : NotificationTypeFromJSON(json['notification_type']),
        'isRead': json['is_read'],
        'createdAt': (new Date(json['created_at'])),
        'sender': json['sender'] == null ? undefined : PublicUserPreviewFromJSON(json['sender']),
        'badge': BadgeModelFromJSON(json['badge']),
    };
}

  export function BadgeNotificationToJSON(json: any): BadgeNotification {
      return BadgeNotificationToJSONTyped(json, false);
  }

  export function BadgeNotificationToJSONTyped(value?: BadgeNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notification_type': NotificationTypeToJSON(value['notificationType']),
        'is_read': value['isRead'],
        'created_at': ((value['createdAt']).toISOString()),
        'sender': PublicUserPreviewToJSON(value['sender']),
        'badge': BadgeModelToJSON(value['badge']),
    };
}

