/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadgeModel
 */
export interface BadgeModel {
    /**
     * 
     * @type {Date}
     * @memberof BadgeModel
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BadgeModel
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof BadgeModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BadgeModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BadgeModel
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BadgeModel
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof BadgeModel
     */
    subcategory?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BadgeModel
     */
    contentType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BadgeModel
     */
    timePeriod?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BadgeModel
     */
    requiredRank?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BadgeModel
     */
    scoreThreshold?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BadgeModel
     */
    tokenPrice?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof BadgeModel
     */
    claimable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BadgeModel
     */
    usable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BadgeModel
     */
    visible?: boolean;
}

/**
 * Check if a given object implements the BadgeModel interface.
 */
export function instanceOfBadgeModel(value: object): value is BadgeModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function BadgeModelFromJSON(json: any): BadgeModel {
    return BadgeModelFromJSONTyped(json, false);
}

export function BadgeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadgeModel {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category_'],
        'subcategory': json['subcategory_'] == null ? undefined : json['subcategory_'],
        'contentType': json['content_type_'] == null ? undefined : json['content_type_'],
        'timePeriod': json['time_period_'] == null ? undefined : json['time_period_'],
        'requiredRank': json['required_rank'] == null ? undefined : json['required_rank'],
        'scoreThreshold': json['score_threshold'] == null ? undefined : json['score_threshold'],
        'tokenPrice': json['token_price'] == null ? undefined : json['token_price'],
        'claimable': json['claimable'] == null ? undefined : json['claimable'],
        'usable': json['usable'] == null ? undefined : json['usable'],
        'visible': json['visible'] == null ? undefined : json['visible'],
    };
}

  export function BadgeModelToJSON(json: any): BadgeModel {
      return BadgeModelToJSONTyped(json, false);
  }

  export function BadgeModelToJSONTyped(value?: BadgeModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'category_': value['category'],
        'subcategory_': value['subcategory'],
        'content_type_': value['contentType'],
        'time_period_': value['timePeriod'],
        'required_rank': value['requiredRank'],
        'score_threshold': value['scoreThreshold'],
        'token_price': value['tokenPrice'],
        'claimable': value['claimable'],
        'usable': value['usable'],
        'visible': value['visible'],
    };
}

