/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BeardStyle = {
    Clean: 'clean',
    Stubble: 'stubble',
    Mustache: 'mustache',
    Full: 'full',
    Vandyke: 'vandyke',
    Circle: 'circle'
} as const;
export type BeardStyle = typeof BeardStyle[keyof typeof BeardStyle];


export function instanceOfBeardStyle(value: any): boolean {
    for (const key in BeardStyle) {
        if (Object.prototype.hasOwnProperty.call(BeardStyle, key)) {
            if (BeardStyle[key as keyof typeof BeardStyle] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BeardStyleFromJSON(json: any): BeardStyle {
    return BeardStyleFromJSONTyped(json, false);
}

export function BeardStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeardStyle {
    return json as BeardStyle;
}

export function BeardStyleToJSON(value?: BeardStyle | null): any {
    return value as any;
}

export function BeardStyleToJSONTyped(value: any, ignoreDiscriminator: boolean): BeardStyle {
    return value as BeardStyle;
}

