/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingReconciliationResponse
 */
export interface BillingReconciliationResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof BillingReconciliationResponse
     */
    reactivated: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BillingReconciliationResponse
     */
    deactivated: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BillingReconciliationResponse
     */
    retry: Array<string>;
}

/**
 * Check if a given object implements the BillingReconciliationResponse interface.
 */
export function instanceOfBillingReconciliationResponse(value: object): value is BillingReconciliationResponse {
    if (!('reactivated' in value) || value['reactivated'] === undefined) return false;
    if (!('deactivated' in value) || value['deactivated'] === undefined) return false;
    if (!('retry' in value) || value['retry'] === undefined) return false;
    return true;
}

export function BillingReconciliationResponseFromJSON(json: any): BillingReconciliationResponse {
    return BillingReconciliationResponseFromJSONTyped(json, false);
}

export function BillingReconciliationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingReconciliationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reactivated': json['reactivated'],
        'deactivated': json['deactivated'],
        'retry': json['retry'],
    };
}

  export function BillingReconciliationResponseToJSON(json: any): BillingReconciliationResponse {
      return BillingReconciliationResponseToJSONTyped(json, false);
  }

  export function BillingReconciliationResponseToJSONTyped(value?: BillingReconciliationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reactivated': value['reactivated'],
        'deactivated': value['deactivated'],
        'retry': value['retry'],
    };
}

