/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvatarOptionalField } from './AvatarOptionalField';
import {
    AvatarOptionalFieldFromJSON,
    AvatarOptionalFieldFromJSONTyped,
    AvatarOptionalFieldToJSON,
    AvatarOptionalFieldToJSONTyped,
} from './AvatarOptionalField';
import type { AvatarRequiredField } from './AvatarRequiredField';
import {
    AvatarRequiredFieldFromJSON,
    AvatarRequiredFieldFromJSONTyped,
    AvatarRequiredFieldToJSON,
    AvatarRequiredFieldToJSONTyped,
} from './AvatarRequiredField';

/**
 * 
 * @export
 * @interface CharacterAboutPageReview
 */
export interface CharacterAboutPageReview {
    /**
     * 
     * @type {AvatarRequiredField}
     * @memberof CharacterAboutPageReview
     */
    characterName?: AvatarRequiredField | null;
    /**
     * 
     * @type {AvatarRequiredField}
     * @memberof CharacterAboutPageReview
     */
    gender?: AvatarRequiredField | null;
    /**
     * 
     * @type {AvatarRequiredField}
     * @memberof CharacterAboutPageReview
     */
    bio?: AvatarRequiredField | null;
    /**
     * 
     * @type {AvatarRequiredField}
     * @memberof CharacterAboutPageReview
     */
    greetings?: AvatarRequiredField | null;
    /**
     * 
     * @type {AvatarRequiredField}
     * @memberof CharacterAboutPageReview
     */
    story?: AvatarRequiredField | null;
    /**
     * 
     * @type {AvatarOptionalField}
     * @memberof CharacterAboutPageReview
     */
    exampleConversation?: AvatarOptionalField | null;
}

/**
 * Check if a given object implements the CharacterAboutPageReview interface.
 */
export function instanceOfCharacterAboutPageReview(value: object): value is CharacterAboutPageReview {
    return true;
}

export function CharacterAboutPageReviewFromJSON(json: any): CharacterAboutPageReview {
    return CharacterAboutPageReviewFromJSONTyped(json, false);
}

export function CharacterAboutPageReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharacterAboutPageReview {
    if (json == null) {
        return json;
    }
    return {
        
        'characterName': json['character_name'] == null ? undefined : AvatarRequiredFieldFromJSON(json['character_name']),
        'gender': json['gender'] == null ? undefined : AvatarRequiredFieldFromJSON(json['gender']),
        'bio': json['bio'] == null ? undefined : AvatarRequiredFieldFromJSON(json['bio']),
        'greetings': json['greetings'] == null ? undefined : AvatarRequiredFieldFromJSON(json['greetings']),
        'story': json['story'] == null ? undefined : AvatarRequiredFieldFromJSON(json['story']),
        'exampleConversation': json['example_conversation'] == null ? undefined : AvatarOptionalFieldFromJSON(json['example_conversation']),
    };
}

  export function CharacterAboutPageReviewToJSON(json: any): CharacterAboutPageReview {
      return CharacterAboutPageReviewToJSONTyped(json, false);
  }

  export function CharacterAboutPageReviewToJSONTyped(value?: CharacterAboutPageReview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'character_name': AvatarRequiredFieldToJSON(value['characterName']),
        'gender': AvatarRequiredFieldToJSON(value['gender']),
        'bio': AvatarRequiredFieldToJSON(value['bio']),
        'greetings': AvatarRequiredFieldToJSON(value['greetings']),
        'story': AvatarRequiredFieldToJSON(value['story']),
        'example_conversation': AvatarOptionalFieldToJSON(value['exampleConversation']),
    };
}

