/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentTypes
 */
export interface ContentTypes {
}

/**
 * Check if a given object implements the ContentTypes interface.
 */
export function instanceOfContentTypes(value: object): value is ContentTypes {
    return true;
}

export function ContentTypesFromJSON(json: any): ContentTypes {
    return ContentTypesFromJSONTyped(json, false);
}

export function ContentTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentTypes {
    return json;
}

  export function ContentTypesToJSON(json: any): ContentTypes {
      return ContentTypesToJSONTyped(json, false);
  }

  export function ContentTypesToJSONTyped(value?: ContentTypes | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

