/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ContentReportReason = {
    UnderageContent: 'UnderageContent',
    Incest: 'Incest',
    GoreOrRape: 'GoreOrRape',
    AdsOrSpam: 'AdsOrSpam',
    Copyright: 'Copyright',
    Other: 'Other'
} as const;
export type ContentReportReason = typeof ContentReportReason[keyof typeof ContentReportReason];


export function instanceOfContentReportReason(value: any): boolean {
    for (const key in ContentReportReason) {
        if (Object.prototype.hasOwnProperty.call(ContentReportReason, key)) {
            if (ContentReportReason[key as keyof typeof ContentReportReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContentReportReasonFromJSON(json: any): ContentReportReason {
    return ContentReportReasonFromJSONTyped(json, false);
}

export function ContentReportReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentReportReason {
    return json as ContentReportReason;
}

export function ContentReportReasonToJSON(value?: ContentReportReason | null): any {
    return value as any;
}

export function ContentReportReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): ContentReportReason {
    return value as ContentReportReason;
}

