/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStoryRequest
 */
export interface CreateStoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateStoryRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoryRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateStoryRequest
     */
    coverImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateStoryRequest
     */
    characterId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateStoryRequest
     */
    userId?: string | null;
}

/**
 * Check if a given object implements the CreateStoryRequest interface.
 */
export function instanceOfCreateStoryRequest(value: object): value is CreateStoryRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateStoryRequestFromJSON(json: any): CreateStoryRequest {
    return CreateStoryRequestFromJSONTyped(json, false);
}

export function CreateStoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'characterId': json['character_id'] == null ? undefined : json['character_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

  export function CreateStoryRequestToJSON(json: any): CreateStoryRequest {
      return CreateStoryRequestToJSONTyped(json, false);
  }

  export function CreateStoryRequestToJSONTyped(value?: CreateStoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'cover_image': value['coverImage'],
        'character_id': value['characterId'],
        'user_id': value['userId'],
    };
}

