/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeMediaType } from './EpisodeMediaType';
import {
    EpisodeMediaTypeFromJSON,
    EpisodeMediaTypeFromJSONTyped,
    EpisodeMediaTypeToJSON,
    EpisodeMediaTypeToJSONTyped,
} from './EpisodeMediaType';

/**
 * 
 * @export
 * @interface EpisodeMediaItem
 */
export interface EpisodeMediaItem {
    /**
     * 
     * @type {string}
     * @memberof EpisodeMediaItem
     */
    id: string;
    /**
     * 
     * @type {EpisodeMediaType}
     * @memberof EpisodeMediaItem
     */
    type: EpisodeMediaType;
    /**
     * 
     * @type {string}
     * @memberof EpisodeMediaItem
     */
    src: string;
    /**
     * 
     * @type {string}
     * @memberof EpisodeMediaItem
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof EpisodeMediaItem
     */
    timestamp?: string | null;
}



/**
 * Check if a given object implements the EpisodeMediaItem interface.
 */
export function instanceOfEpisodeMediaItem(value: object): value is EpisodeMediaItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('src' in value) || value['src'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function EpisodeMediaItemFromJSON(json: any): EpisodeMediaItem {
    return EpisodeMediaItemFromJSONTyped(json, false);
}

export function EpisodeMediaItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpisodeMediaItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': EpisodeMediaTypeFromJSON(json['type']),
        'src': json['src'],
        'prompt': json['prompt'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

  export function EpisodeMediaItemToJSON(json: any): EpisodeMediaItem {
      return EpisodeMediaItemToJSONTyped(json, false);
  }

  export function EpisodeMediaItemToJSONTyped(value?: EpisodeMediaItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': EpisodeMediaTypeToJSON(value['type']),
        'src': value['src'],
        'prompt': value['prompt'],
        'timestamp': value['timestamp'],
    };
}

