/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EpisodeRating
 */
export interface EpisodeRating {
    /**
     * 
     * @type {number}
     * @memberof EpisodeRating
     */
    ratingCount: number;
    /**
     * 
     * @type {number}
     * @memberof EpisodeRating
     */
    ratingAverage: number;
}

/**
 * Check if a given object implements the EpisodeRating interface.
 */
export function instanceOfEpisodeRating(value: object): value is EpisodeRating {
    if (!('ratingCount' in value) || value['ratingCount'] === undefined) return false;
    if (!('ratingAverage' in value) || value['ratingAverage'] === undefined) return false;
    return true;
}

export function EpisodeRatingFromJSON(json: any): EpisodeRating {
    return EpisodeRatingFromJSONTyped(json, false);
}

export function EpisodeRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpisodeRating {
    if (json == null) {
        return json;
    }
    return {
        
        'ratingCount': json['rating_count'],
        'ratingAverage': json['rating_average'],
    };
}

  export function EpisodeRatingToJSON(json: any): EpisodeRating {
      return EpisodeRatingToJSONTyped(json, false);
  }

  export function EpisodeRatingToJSONTyped(value?: EpisodeRating | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating_count': value['ratingCount'],
        'rating_average': value['ratingAverage'],
    };
}

