/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeCastMember } from './EpisodeCastMember';
import {
    EpisodeCastMemberFromJSON,
    EpisodeCastMemberFromJSONTyped,
    EpisodeCastMemberToJSON,
    EpisodeCastMemberToJSONTyped,
} from './EpisodeCastMember';
import type { EpisodeExtraVoiceRole } from './EpisodeExtraVoiceRole';
import {
    EpisodeExtraVoiceRoleFromJSON,
    EpisodeExtraVoiceRoleFromJSONTyped,
    EpisodeExtraVoiceRoleToJSON,
    EpisodeExtraVoiceRoleToJSONTyped,
} from './EpisodeExtraVoiceRole';

/**
 * 
 * @export
 * @interface EpisodeVoiceConfigInput
 */
export interface EpisodeVoiceConfigInput {
    /**
     * 
     * @type {string}
     * @memberof EpisodeVoiceConfigInput
     */
    characterVoice: string;
    /**
     * 
     * @type {string}
     * @memberof EpisodeVoiceConfigInput
     */
    userVoice: string;
    /**
     * 
     * @type {string}
     * @memberof EpisodeVoiceConfigInput
     */
    narratorVoice: string;
    /**
     * 
     * @type {Array<EpisodeExtraVoiceRole>}
     * @memberof EpisodeVoiceConfigInput
     */
    extraVoices?: Array<EpisodeExtraVoiceRole>;
    /**
     * 
     * @type {Array<EpisodeCastMember>}
     * @memberof EpisodeVoiceConfigInput
     */
    cast?: Array<EpisodeCastMember>;
}

/**
 * Check if a given object implements the EpisodeVoiceConfigInput interface.
 */
export function instanceOfEpisodeVoiceConfigInput(value: object): value is EpisodeVoiceConfigInput {
    if (!('characterVoice' in value) || value['characterVoice'] === undefined) return false;
    if (!('userVoice' in value) || value['userVoice'] === undefined) return false;
    if (!('narratorVoice' in value) || value['narratorVoice'] === undefined) return false;
    return true;
}

export function EpisodeVoiceConfigInputFromJSON(json: any): EpisodeVoiceConfigInput {
    return EpisodeVoiceConfigInputFromJSONTyped(json, false);
}

export function EpisodeVoiceConfigInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpisodeVoiceConfigInput {
    if (json == null) {
        return json;
    }
    return {
        
        'characterVoice': json['character_voice'],
        'userVoice': json['user_voice'],
        'narratorVoice': json['narrator_voice'],
        'extraVoices': json['extra_voices'] == null ? undefined : ((json['extra_voices'] as Array<any>).map(EpisodeExtraVoiceRoleFromJSON)),
        'cast': json['cast'] == null ? undefined : ((json['cast'] as Array<any>).map(EpisodeCastMemberFromJSON)),
    };
}

  export function EpisodeVoiceConfigInputToJSON(json: any): EpisodeVoiceConfigInput {
      return EpisodeVoiceConfigInputToJSONTyped(json, false);
  }

  export function EpisodeVoiceConfigInputToJSONTyped(value?: EpisodeVoiceConfigInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'character_voice': value['characterVoice'],
        'user_voice': value['userVoice'],
        'narrator_voice': value['narratorVoice'],
        'extra_voices': value['extraVoices'] == null ? undefined : ((value['extraVoices'] as Array<any>).map(EpisodeExtraVoiceRoleToJSON)),
        'cast': value['cast'] == null ? undefined : ((value['cast'] as Array<any>).map(EpisodeCastMemberToJSON)),
    };
}

