/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EpisodePanelType = {
    Scene: 'scene',
    Tbc: 'tbc',
    End: 'end'
} as const;
export type EpisodePanelType = typeof EpisodePanelType[keyof typeof EpisodePanelType];


export function instanceOfEpisodePanelType(value: any): boolean {
    for (const key in EpisodePanelType) {
        if (Object.prototype.hasOwnProperty.call(EpisodePanelType, key)) {
            if (EpisodePanelType[key as keyof typeof EpisodePanelType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EpisodePanelTypeFromJSON(json: any): EpisodePanelType {
    return EpisodePanelTypeFromJSONTyped(json, false);
}

export function EpisodePanelTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpisodePanelType {
    return json as EpisodePanelType;
}

export function EpisodePanelTypeToJSON(value?: EpisodePanelType | null): any {
    return value as any;
}

export function EpisodePanelTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): EpisodePanelType {
    return value as EpisodePanelType;
}

