/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EffectiveEventStatus } from './EffectiveEventStatus';
import {
    EffectiveEventStatusFromJSON,
    EffectiveEventStatusFromJSONTyped,
    EffectiveEventStatusToJSON,
    EffectiveEventStatusToJSONTyped,
} from './EffectiveEventStatus';

/**
 * 
 * @export
 * @interface EventPreview
 */
export interface EventPreview {
    /**
     * 
     * @type {string}
     * @memberof EventPreview
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventPreview
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EventPreview
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof EventPreview
     */
    timeRemaining: number | null;
    /**
     * 
     * @type {number}
     * @memberof EventPreview
     */
    prizePool: number | null;
    /**
     * 
     * @type {number}
     * @memberof EventPreview
     */
    submissionsCount: number;
    /**
     * 
     * @type {EffectiveEventStatus}
     * @memberof EventPreview
     */
    status: EffectiveEventStatus;
}



/**
 * Check if a given object implements the EventPreview interface.
 */
export function instanceOfEventPreview(value: object): value is EventPreview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('timeRemaining' in value) || value['timeRemaining'] === undefined) return false;
    if (!('prizePool' in value) || value['prizePool'] === undefined) return false;
    if (!('submissionsCount' in value) || value['submissionsCount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EventPreviewFromJSON(json: any): EventPreview {
    return EventPreviewFromJSONTyped(json, false);
}

export function EventPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'timeRemaining': json['time_remaining'],
        'prizePool': json['prize_pool'],
        'submissionsCount': json['submissions_count'],
        'status': EffectiveEventStatusFromJSON(json['status']),
    };
}

  export function EventPreviewToJSON(json: any): EventPreview {
      return EventPreviewToJSONTyped(json, false);
  }

  export function EventPreviewToJSONTyped(value?: EventPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'time_remaining': value['timeRemaining'],
        'prize_pool': value['prizePool'],
        'submissions_count': value['submissionsCount'],
        'status': EffectiveEventStatusToJSON(value['status']),
    };
}

