/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventSubmissionPreview } from './EventSubmissionPreview';
import {
    EventSubmissionPreviewFromJSON,
    EventSubmissionPreviewFromJSONTyped,
    EventSubmissionPreviewToJSON,
    EventSubmissionPreviewToJSONTyped,
} from './EventSubmissionPreview';

/**
 * 
 * @export
 * @interface EventPreview
 */
export interface EventPreview {
    /**
     * 
     * @type {string}
     * @memberof EventPreview
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventPreview
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EventPreview
     */
    description: string;
    /**
     * 
     * @type {EventSubmissionPreview}
     * @memberof EventPreview
     */
    submission: EventSubmissionPreview;
}

/**
 * Check if a given object implements the EventPreview interface.
 */
export function instanceOfEventPreview(value: object): value is EventPreview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('submission' in value) || value['submission'] === undefined) return false;
    return true;
}

export function EventPreviewFromJSON(json: any): EventPreview {
    return EventPreviewFromJSONTyped(json, false);
}

export function EventPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'submission': EventSubmissionPreviewFromJSON(json['submission']),
    };
}

  export function EventPreviewToJSON(json: any): EventPreview {
      return EventPreviewToJSONTyped(json, false);
  }

  export function EventPreviewToJSONTyped(value?: EventPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'submission': EventSubmissionPreviewToJSON(value['submission']),
    };
}

