/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OwnerFilter } from './OwnerFilter';
import {
    OwnerFilterFromJSON,
    OwnerFilterFromJSONTyped,
    OwnerFilterToJSON,
    OwnerFilterToJSONTyped,
} from './OwnerFilter';
import type { PostType } from './PostType';
import {
    PostTypeFromJSON,
    PostTypeFromJSONTyped,
    PostTypeToJSON,
    PostTypeToJSONTyped,
} from './PostType';
import type { SortFilter } from './SortFilter';
import {
    SortFilterFromJSON,
    SortFilterFromJSONTyped,
    SortFilterToJSON,
    SortFilterToJSONTyped,
} from './SortFilter';
import type { CategoryValues } from './CategoryValues';
import {
    CategoryValuesFromJSON,
    CategoryValuesFromJSONTyped,
    CategoryValuesToJSON,
    CategoryValuesToJSONTyped,
} from './CategoryValues';
import type { DateRangeFilter } from './DateRangeFilter';
import {
    DateRangeFilterFromJSON,
    DateRangeFilterFromJSONTyped,
    DateRangeFilterToJSON,
    DateRangeFilterToJSONTyped,
} from './DateRangeFilter';

/**
 * 
 * @export
 * @interface ExploreSearchRequest
 */
export interface ExploreSearchRequest {
    /**
     * 
     * @type {string}
     * @memberof ExploreSearchRequest
     */
    freeTextSearch?: string | null;
    /**
     * 
     * @type {SortFilter}
     * @memberof ExploreSearchRequest
     */
    sortFilter?: SortFilter;
    /**
     * 
     * @type {number}
     * @memberof ExploreSearchRequest
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof ExploreSearchRequest
     */
    paginationToken?: string | null;
    /**
     * 
     * @type {CategoryValues}
     * @memberof ExploreSearchRequest
     */
    tagFilters?: CategoryValues | null;
    /**
     * 
     * @type {DateRangeFilter}
     * @memberof ExploreSearchRequest
     */
    dateFilter?: DateRangeFilter | null;
    /**
     * 
     * @type {OwnerFilter}
     * @memberof ExploreSearchRequest
     */
    ownerFilter?: OwnerFilter | null;
    /**
     * 
     * @type {string}
     * @memberof ExploreSearchRequest
     */
    chatbotId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExploreSearchRequest
     */
    storyId?: string | null;
    /**
     * 
     * @type {PostType}
     * @memberof ExploreSearchRequest
     */
    postType?: PostType;
    /**
     * 
     * @type {string}
     * @memberof ExploreSearchRequest
     */
    creatorUserId?: string | null;
}



/**
 * Check if a given object implements the ExploreSearchRequest interface.
 */
export function instanceOfExploreSearchRequest(value: object): value is ExploreSearchRequest {
    return true;
}

export function ExploreSearchRequestFromJSON(json: any): ExploreSearchRequest {
    return ExploreSearchRequestFromJSONTyped(json, false);
}

export function ExploreSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExploreSearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'freeTextSearch': json['free_text_search'] == null ? undefined : json['free_text_search'],
        'sortFilter': json['sort_filter'] == null ? undefined : SortFilterFromJSON(json['sort_filter']),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'paginationToken': json['pagination_token'] == null ? undefined : json['pagination_token'],
        'tagFilters': json['tag_filters'] == null ? undefined : CategoryValuesFromJSON(json['tag_filters']),
        'dateFilter': json['date_filter'] == null ? undefined : DateRangeFilterFromJSON(json['date_filter']),
        'ownerFilter': json['owner_filter'] == null ? undefined : OwnerFilterFromJSON(json['owner_filter']),
        'chatbotId': json['chatbot_id'] == null ? undefined : json['chatbot_id'],
        'storyId': json['story_id'] == null ? undefined : json['story_id'],
        'postType': json['post_type'] == null ? undefined : PostTypeFromJSON(json['post_type']),
        'creatorUserId': json['creator_user_id'] == null ? undefined : json['creator_user_id'],
    };
}

  export function ExploreSearchRequestToJSON(json: any): ExploreSearchRequest {
      return ExploreSearchRequestToJSONTyped(json, false);
  }

  export function ExploreSearchRequestToJSONTyped(value?: ExploreSearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'free_text_search': value['freeTextSearch'],
        'sort_filter': SortFilterToJSON(value['sortFilter']),
        'limit': value['limit'],
        'pagination_token': value['paginationToken'],
        'tag_filters': CategoryValuesToJSON(value['tagFilters']),
        'date_filter': DateRangeFilterToJSON(value['dateFilter']),
        'owner_filter': OwnerFilterToJSON(value['ownerFilter']),
        'chatbot_id': value['chatbotId'],
        'story_id': value['storyId'],
        'post_type': PostTypeToJSON(value['postType']),
        'creator_user_id': value['creatorUserId'],
    };
}

