/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtStyle } from './ArtStyle';
import {
    ArtStyleFromJSON,
    ArtStyleFromJSONTyped,
    ArtStyleToJSON,
    ArtStyleToJSONTyped,
} from './ArtStyle';
import type { ChatbotPreview } from './ChatbotPreview';
import {
    ChatbotPreviewFromJSON,
    ChatbotPreviewFromJSONTyped,
    ChatbotPreviewToJSON,
    ChatbotPreviewToJSONTyped,
} from './ChatbotPreview';
import type { PostDetails } from './PostDetails';
import {
    PostDetailsFromJSON,
    PostDetailsFromJSONTyped,
    PostDetailsToJSON,
    PostDetailsToJSONTyped,
} from './PostDetails';
import type { ImageGenerationStatus } from './ImageGenerationStatus';
import {
    ImageGenerationStatusFromJSON,
    ImageGenerationStatusFromJSONTyped,
    ImageGenerationStatusToJSON,
    ImageGenerationStatusToJSONTyped,
} from './ImageGenerationStatus';

/**
 * 
 * @export
 * @interface GeneratedImages
 */
export interface GeneratedImages {
    /**
     * 
     * @type {string}
     * @memberof GeneratedImages
     */
    type: GeneratedImagesTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GeneratedImages
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedImages
     */
    url: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GeneratedImages
     */
    createdAt: Date;
    /**
     * 
     * @type {ChatbotPreview}
     * @memberof GeneratedImages
     */
    chatbot: ChatbotPreview | null;
    /**
     * 
     * @type {PostDetails}
     * @memberof GeneratedImages
     */
    postDetails?: PostDetails | null;
    /**
     * 
     * @type {string}
     * @memberof GeneratedImages
     */
    eta: string;
    /**
     * 
     * @type {ImageGenerationStatus}
     * @memberof GeneratedImages
     */
    status: ImageGenerationStatus;
    /**
     * 
     * @type {string}
     * @memberof GeneratedImages
     */
    generationId: string;
    /**
     * 
     * @type {boolean}
     * @memberof GeneratedImages
     */
    seenByUser: boolean;
    /**
     * 
     * @type {ArtStyle}
     * @memberof GeneratedImages
     */
    artStyle: ArtStyle;
}


/**
 * @export
 */
export const GeneratedImagesTypeEnum = {
    GeneratedImages: 'generatedImages',
    GeneratedVideos: 'generatedVideos'
} as const;
export type GeneratedImagesTypeEnum = typeof GeneratedImagesTypeEnum[keyof typeof GeneratedImagesTypeEnum];


/**
 * Check if a given object implements the GeneratedImages interface.
 */
export function instanceOfGeneratedImages(value: object): value is GeneratedImages {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('chatbot' in value) || value['chatbot'] === undefined) return false;
    if (!('eta' in value) || value['eta'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('generationId' in value) || value['generationId'] === undefined) return false;
    if (!('seenByUser' in value) || value['seenByUser'] === undefined) return false;
    if (!('artStyle' in value) || value['artStyle'] === undefined) return false;
    return true;
}

export function GeneratedImagesFromJSON(json: any): GeneratedImages {
    return GeneratedImagesFromJSONTyped(json, false);
}

export function GeneratedImagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratedImages {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'url': json['url'],
        'createdAt': (new Date(json['created_at'])),
        'chatbot': ChatbotPreviewFromJSON(json['chatbot']),
        'postDetails': json['post_details'] == null ? undefined : PostDetailsFromJSON(json['post_details']),
        'eta': json['eta'],
        'status': ImageGenerationStatusFromJSON(json['status']),
        'generationId': json['generation_id'],
        'seenByUser': json['seen_by_user'],
        'artStyle': ArtStyleFromJSON(json['art_style']),
    };
}

  export function GeneratedImagesToJSON(json: any): GeneratedImages {
      return GeneratedImagesToJSONTyped(json, false);
  }

  export function GeneratedImagesToJSONTyped(value?: GeneratedImages | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'url': value['url'],
        'created_at': ((value['createdAt']).toISOString()),
        'chatbot': ChatbotPreviewToJSON(value['chatbot']),
        'post_details': PostDetailsToJSON(value['postDetails']),
        'eta': value['eta'],
        'status': ImageGenerationStatusToJSON(value['status']),
        'generation_id': value['generationId'],
        'seen_by_user': value['seenByUser'],
        'art_style': ArtStyleToJSON(value['artStyle']),
    };
}

