/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatbotInfo } from './ChatbotInfo';
import {
    ChatbotInfoFromJSON,
    ChatbotInfoFromJSONTyped,
    ChatbotInfoToJSON,
    ChatbotInfoToJSONTyped,
} from './ChatbotInfo';
import type { PostDetails } from './PostDetails';
import {
    PostDetailsFromJSON,
    PostDetailsFromJSONTyped,
    PostDetailsToJSON,
    PostDetailsToJSONTyped,
} from './PostDetails';
import type { ChatMessageDetail } from './ChatMessageDetail';
import {
    ChatMessageDetailFromJSON,
    ChatMessageDetailFromJSONTyped,
    ChatMessageDetailToJSON,
    ChatMessageDetailToJSONTyped,
} from './ChatMessageDetail';
import type { ConversationSettings } from './ConversationSettings';
import {
    ConversationSettingsFromJSON,
    ConversationSettingsFromJSONTyped,
    ConversationSettingsToJSON,
    ConversationSettingsToJSONTyped,
} from './ConversationSettings';

/**
 * 
 * @export
 * @interface GetConversationResponse
 */
export interface GetConversationResponse {
    /**
     * 
     * @type {ChatbotInfo}
     * @memberof GetConversationResponse
     */
    chatbotInfo: ChatbotInfo;
    /**
     * 
     * @type {Array<ChatMessageDetail>}
     * @memberof GetConversationResponse
     */
    messages: Array<ChatMessageDetail>;
    /**
     * 
     * @type {boolean}
     * @memberof GetConversationResponse
     */
    isPublic: boolean;
    /**
     * 
     * @type {ConversationSettings}
     * @memberof GetConversationResponse
     */
    settings: ConversationSettings;
    /**
     * 
     * @type {string}
     * @memberof GetConversationResponse
     */
    conversationId: string;
    /**
     * 
     * @type {PostDetails}
     * @memberof GetConversationResponse
     */
    postDetails: PostDetails | null;
    /**
     * 
     * @type {string}
     * @memberof GetConversationResponse
     */
    paginationToken?: string | null;
}

/**
 * Check if a given object implements the GetConversationResponse interface.
 */
export function instanceOfGetConversationResponse(value: object): value is GetConversationResponse {
    if (!('chatbotInfo' in value) || value['chatbotInfo'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    if (!('settings' in value) || value['settings'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('postDetails' in value) || value['postDetails'] === undefined) return false;
    return true;
}

export function GetConversationResponseFromJSON(json: any): GetConversationResponse {
    return GetConversationResponseFromJSONTyped(json, false);
}

export function GetConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chatbotInfo': ChatbotInfoFromJSON(json['chatbot_info']),
        'messages': ((json['messages'] as Array<any>).map(ChatMessageDetailFromJSON)),
        'isPublic': json['is_public'],
        'settings': ConversationSettingsFromJSON(json['settings']),
        'conversationId': json['conversation_id'],
        'postDetails': PostDetailsFromJSON(json['post_details']),
        'paginationToken': json['pagination_token'] == null ? undefined : json['pagination_token'],
    };
}

  export function GetConversationResponseToJSON(json: any): GetConversationResponse {
      return GetConversationResponseToJSONTyped(json, false);
  }

  export function GetConversationResponseToJSONTyped(value?: GetConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chatbot_info': ChatbotInfoToJSON(value['chatbotInfo']),
        'messages': ((value['messages'] as Array<any>).map(ChatMessageDetailToJSON)),
        'is_public': value['isPublic'],
        'settings': ConversationSettingsToJSON(value['settings']),
        'conversation_id': value['conversationId'],
        'post_details': PostDetailsToJSON(value['postDetails']),
        'pagination_token': value['paginationToken'],
    };
}

