/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneratedAudioItem } from './GeneratedAudioItem';
import {
    GeneratedAudioItemFromJSON,
    GeneratedAudioItemFromJSONTyped,
    GeneratedAudioItemToJSON,
    GeneratedAudioItemToJSONTyped,
} from './GeneratedAudioItem';

/**
 * 
 * @export
 * @interface GetGeneratedAudioResponse
 */
export interface GetGeneratedAudioResponse {
    /**
     * 
     * @type {Array<GeneratedAudioItem>}
     * @memberof GetGeneratedAudioResponse
     */
    items: Array<GeneratedAudioItem>;
    /**
     * 
     * @type {string}
     * @memberof GetGeneratedAudioResponse
     */
    paginationToken?: string | null;
}

/**
 * Check if a given object implements the GetGeneratedAudioResponse interface.
 */
export function instanceOfGetGeneratedAudioResponse(value: object): value is GetGeneratedAudioResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GetGeneratedAudioResponseFromJSON(json: any): GetGeneratedAudioResponse {
    return GetGeneratedAudioResponseFromJSONTyped(json, false);
}

export function GetGeneratedAudioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGeneratedAudioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GeneratedAudioItemFromJSON)),
        'paginationToken': json['pagination_token'] == null ? undefined : json['pagination_token'],
    };
}

  export function GetGeneratedAudioResponseToJSON(json: any): GetGeneratedAudioResponse {
      return GetGeneratedAudioResponseToJSONTyped(json, false);
  }

  export function GetGeneratedAudioResponseToJSONTyped(value?: GetGeneratedAudioResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GeneratedAudioItemToJSON)),
        'pagination_token': value['paginationToken'],
    };
}

