/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetIdentityChatbotResponse
 */
export interface GetIdentityChatbotResponse {
    /**
     * 
     * @type {string}
     * @memberof GetIdentityChatbotResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof GetIdentityChatbotResponse
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetIdentityChatbotResponse
     */
    gender: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetIdentityChatbotResponse
     */
    bio: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetIdentityChatbotResponse
     */
    greetings: string | null;
}

/**
 * Check if a given object implements the GetIdentityChatbotResponse interface.
 */
export function instanceOfGetIdentityChatbotResponse(value: object): value is GetIdentityChatbotResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('bio' in value) || value['bio'] === undefined) return false;
    if (!('greetings' in value) || value['greetings'] === undefined) return false;
    return true;
}

export function GetIdentityChatbotResponseFromJSON(json: any): GetIdentityChatbotResponse {
    return GetIdentityChatbotResponseFromJSONTyped(json, false);
}

export function GetIdentityChatbotResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIdentityChatbotResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'name': json['name'],
        'gender': json['gender'],
        'bio': json['bio'],
        'greetings': json['greetings'],
    };
}

  export function GetIdentityChatbotResponseToJSON(json: any): GetIdentityChatbotResponse {
      return GetIdentityChatbotResponseToJSONTyped(json, false);
  }

  export function GetIdentityChatbotResponseToJSONTyped(value?: GetIdentityChatbotResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'name': value['name'],
        'gender': value['gender'],
        'bio': value['bio'],
        'greetings': value['greetings'],
    };
}

