/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstanceTypeUrlResponse } from './InstanceTypeUrlResponse';
import {
    InstanceTypeUrlResponseFromJSON,
    InstanceTypeUrlResponseFromJSONTyped,
    InstanceTypeUrlResponseToJSON,
    InstanceTypeUrlResponseToJSONTyped,
} from './InstanceTypeUrlResponse';

/**
 * 
 * @export
 * @interface GetInstancesDBVastAiListResponse
 */
export interface GetInstancesDBVastAiListResponse {
    /**
     * 
     * @type {Array<InstanceTypeUrlResponse>}
     * @memberof GetInstancesDBVastAiListResponse
     */
    missingInVastai: Array<InstanceTypeUrlResponse>;
    /**
     * 
     * @type {Array<InstanceTypeUrlResponse>}
     * @memberof GetInstancesDBVastAiListResponse
     */
    missingInDb: Array<InstanceTypeUrlResponse>;
}

/**
 * Check if a given object implements the GetInstancesDBVastAiListResponse interface.
 */
export function instanceOfGetInstancesDBVastAiListResponse(value: object): value is GetInstancesDBVastAiListResponse {
    if (!('missingInVastai' in value) || value['missingInVastai'] === undefined) return false;
    if (!('missingInDb' in value) || value['missingInDb'] === undefined) return false;
    return true;
}

export function GetInstancesDBVastAiListResponseFromJSON(json: any): GetInstancesDBVastAiListResponse {
    return GetInstancesDBVastAiListResponseFromJSONTyped(json, false);
}

export function GetInstancesDBVastAiListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInstancesDBVastAiListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'missingInVastai': ((json['missing_in_vastai'] as Array<any>).map(InstanceTypeUrlResponseFromJSON)),
        'missingInDb': ((json['missing_in_db'] as Array<any>).map(InstanceTypeUrlResponseFromJSON)),
    };
}

  export function GetInstancesDBVastAiListResponseToJSON(json: any): GetInstancesDBVastAiListResponse {
      return GetInstancesDBVastAiListResponseToJSONTyped(json, false);
  }

  export function GetInstancesDBVastAiListResponseToJSONTyped(value?: GetInstancesDBVastAiListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'missing_in_vastai': ((value['missingInVastai'] as Array<any>).map(InstanceTypeUrlResponseToJSON)),
        'missing_in_db': ((value['missingInDb'] as Array<any>).map(InstanceTypeUrlResponseToJSON)),
    };
}

