/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoraName } from './LoraName';
import {
    LoraNameFromJSON,
    LoraNameFromJSONTyped,
    LoraNameToJSON,
    LoraNameToJSONTyped,
} from './LoraName';

/**
 * 
 * @export
 * @interface GetImageGenerationTagsResponse
 */
export interface GetImageGenerationTagsResponse {
    /**
     * 
     * @type {string}
     * @memberof GetImageGenerationTagsResponse
     */
    tags: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageGenerationTagsResponse
     */
    downloadUrl: string;
    /**
     * 
     * @type {string}
     * @memberof GetImageGenerationTagsResponse
     */
    chatbotName: string | null;
    /**
     * 
     * @type {Array<LoraName>}
     * @memberof GetImageGenerationTagsResponse
     */
    loras: Array<LoraName>;
}

/**
 * Check if a given object implements the GetImageGenerationTagsResponse interface.
 */
export function instanceOfGetImageGenerationTagsResponse(value: object): value is GetImageGenerationTagsResponse {
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('downloadUrl' in value) || value['downloadUrl'] === undefined) return false;
    if (!('chatbotName' in value) || value['chatbotName'] === undefined) return false;
    if (!('loras' in value) || value['loras'] === undefined) return false;
    return true;
}

export function GetImageGenerationTagsResponseFromJSON(json: any): GetImageGenerationTagsResponse {
    return GetImageGenerationTagsResponseFromJSONTyped(json, false);
}

export function GetImageGenerationTagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetImageGenerationTagsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'],
        'downloadUrl': json['download_url'],
        'chatbotName': json['chatbotName'],
        'loras': ((json['loras'] as Array<any>).map(LoraNameFromJSON)),
    };
}

  export function GetImageGenerationTagsResponseToJSON(json: any): GetImageGenerationTagsResponse {
      return GetImageGenerationTagsResponseToJSONTyped(json, false);
  }

  export function GetImageGenerationTagsResponseToJSONTyped(value?: GetImageGenerationTagsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'],
        'download_url': value['downloadUrl'],
        'chatbotName': value['chatbotName'],
        'loras': ((value['loras'] as Array<any>).map(LoraNameToJSON)),
    };
}

