/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GiftCodeType = {
    _100: 'tokens_100',
    _200: 'tokens_200',
    _500: 'tokens_500',
    _1200: 'tokens_1200'
} as const;
export type GiftCodeType = typeof GiftCodeType[keyof typeof GiftCodeType];


export function instanceOfGiftCodeType(value: any): boolean {
    for (const key in GiftCodeType) {
        if (Object.prototype.hasOwnProperty.call(GiftCodeType, key)) {
            if (GiftCodeType[key as keyof typeof GiftCodeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GiftCodeTypeFromJSON(json: any): GiftCodeType {
    return GiftCodeTypeFromJSONTyped(json, false);
}

export function GiftCodeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GiftCodeType {
    return json as GiftCodeType;
}

export function GiftCodeTypeToJSON(value?: GiftCodeType | null): any {
    return value as any;
}

export function GiftCodeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): GiftCodeType {
    return value as GiftCodeType;
}

