/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoLoraName } from './VideoLoraName';
import {
    VideoLoraNameFromJSON,
    VideoLoraNameFromJSONTyped,
    VideoLoraNameToJSON,
    VideoLoraNameToJSONTyped,
} from './VideoLoraName';

/**
 * 
 * @export
 * @interface ImageToVideoPayload
 */
export interface ImageToVideoPayload {
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoPayload
     */
    chatbotId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoPayload
     */
    inputImageId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoPayload
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoPayload
     */
    requestId: string;
    /**
     * 
     * @type {number}
     * @memberof ImageToVideoPayload
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoPayload
     */
    prompt: string;
    /**
     * 
     * @type {Array<VideoLoraName>}
     * @memberof ImageToVideoPayload
     */
    loras: Array<VideoLoraName>;
}

/**
 * Check if a given object implements the ImageToVideoPayload interface.
 */
export function instanceOfImageToVideoPayload(value: object): value is ImageToVideoPayload {
    if (!('chatbotId' in value) || value['chatbotId'] === undefined) return false;
    if (!('inputImageId' in value) || value['inputImageId'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('loras' in value) || value['loras'] === undefined) return false;
    return true;
}

export function ImageToVideoPayloadFromJSON(json: any): ImageToVideoPayload {
    return ImageToVideoPayloadFromJSONTyped(json, false);
}

export function ImageToVideoPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageToVideoPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'chatbotId': json['chatbot_id'],
        'inputImageId': json['input_image_id'],
        'clientId': json['client_id'],
        'requestId': json['request_id'],
        'duration': json['duration'],
        'prompt': json['prompt'],
        'loras': ((json['loras'] as Array<any>).map(VideoLoraNameFromJSON)),
    };
}

  export function ImageToVideoPayloadToJSON(json: any): ImageToVideoPayload {
      return ImageToVideoPayloadToJSONTyped(json, false);
  }

  export function ImageToVideoPayloadToJSONTyped(value?: ImageToVideoPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chatbot_id': value['chatbotId'],
        'input_image_id': value['inputImageId'],
        'client_id': value['clientId'],
        'request_id': value['requestId'],
        'duration': value['duration'],
        'prompt': value['prompt'],
        'loras': ((value['loras'] as Array<any>).map(VideoLoraNameToJSON)),
    };
}

