/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageContent
 */
export interface ImageContent {
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ImageContent
     */
    url: string;
}

/**
 * Check if a given object implements the ImageContent interface.
 */
export function instanceOfImageContent(value: object): value is ImageContent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ImageContentFromJSON(json: any): ImageContent {
    return ImageContentFromJSONTyped(json, false);
}

export function ImageContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageContent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
    };
}

  export function ImageContentToJSON(json: any): ImageContent {
      return ImageContentToJSONTyped(json, false);
  }

  export function ImageContentToJSONTyped(value?: ImageContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
    };
}

