/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageToVideoRecommendationPayload
 */
export interface ImageToVideoRecommendationPayload {
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRecommendationPayload
     */
    chatbotId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRecommendationPayload
     */
    inputImageId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRecommendationPayload
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRecommendationPayload
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToVideoRecommendationPayload
     */
    prompt: string;
}

/**
 * Check if a given object implements the ImageToVideoRecommendationPayload interface.
 */
export function instanceOfImageToVideoRecommendationPayload(value: object): value is ImageToVideoRecommendationPayload {
    if (!('chatbotId' in value) || value['chatbotId'] === undefined) return false;
    if (!('inputImageId' in value) || value['inputImageId'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function ImageToVideoRecommendationPayloadFromJSON(json: any): ImageToVideoRecommendationPayload {
    return ImageToVideoRecommendationPayloadFromJSONTyped(json, false);
}

export function ImageToVideoRecommendationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageToVideoRecommendationPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'chatbotId': json['chatbot_id'],
        'inputImageId': json['input_image_id'],
        'clientId': json['client_id'],
        'requestId': json['request_id'],
        'prompt': json['prompt'],
    };
}

  export function ImageToVideoRecommendationPayloadToJSON(json: any): ImageToVideoRecommendationPayload {
      return ImageToVideoRecommendationPayloadToJSONTyped(json, false);
  }

  export function ImageToVideoRecommendationPayloadToJSONTyped(value?: ImageToVideoRecommendationPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chatbot_id': value['chatbotId'],
        'input_image_id': value['inputImageId'],
        'client_id': value['clientId'],
        'request_id': value['requestId'],
        'prompt': value['prompt'],
    };
}

