/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ImageSendingMode = {
    Dynamic: 'dynamic',
    Request: 'request',
    Off: 'off'
} as const;
export type ImageSendingMode = typeof ImageSendingMode[keyof typeof ImageSendingMode];


export function instanceOfImageSendingMode(value: any): boolean {
    for (const key in ImageSendingMode) {
        if (Object.prototype.hasOwnProperty.call(ImageSendingMode, key)) {
            if (ImageSendingMode[key as keyof typeof ImageSendingMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ImageSendingModeFromJSON(json: any): ImageSendingMode {
    return ImageSendingModeFromJSONTyped(json, false);
}

export function ImageSendingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageSendingMode {
    return json as ImageSendingMode;
}

export function ImageSendingModeToJSON(value?: ImageSendingMode | null): any {
    return value as any;
}

export function ImageSendingModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ImageSendingMode {
    return value as ImageSendingMode;
}

