/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicUserPreview } from './PublicUserPreview';
import {
    PublicUserPreviewFromJSON,
    PublicUserPreviewFromJSONTyped,
    PublicUserPreviewToJSON,
    PublicUserPreviewToJSONTyped,
} from './PublicUserPreview';
import type { PostType } from './PostType';
import {
    PostTypeFromJSON,
    PostTypeFromJSONTyped,
    PostTypeToJSON,
    PostTypeToJSONTyped,
} from './PostType';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';
import type { WallPost } from './WallPost';
import {
    WallPostFromJSON,
    WallPostFromJSONTyped,
    WallPostToJSON,
    WallPostToJSONTyped,
} from './WallPost';

/**
 * 
 * @export
 * @interface LikePostNotification
 */
export interface LikePostNotification {
    /**
     * 
     * @type {NotificationType}
     * @memberof LikePostNotification
     */
    notificationType?: NotificationType;
    /**
     * 
     * @type {boolean}
     * @memberof LikePostNotification
     */
    isRead: boolean;
    /**
     * 
     * @type {Date}
     * @memberof LikePostNotification
     */
    createdAt: Date;
    /**
     * 
     * @type {PublicUserPreview}
     * @memberof LikePostNotification
     */
    sender?: PublicUserPreview | null;
    /**
     * 
     * @type {WallPost}
     * @memberof LikePostNotification
     */
    post: WallPost;
    /**
     * 
     * @type {number}
     * @memberof LikePostNotification
     */
    totalCount: number;
    /**
     * 
     * @type {string}
     * @memberof LikePostNotification
     */
    chatbotName: string;
    /**
     * 
     * @type {PostType}
     * @memberof LikePostNotification
     */
    type: PostType;
}



/**
 * Check if a given object implements the LikePostNotification interface.
 */
export function instanceOfLikePostNotification(value: object): value is LikePostNotification {
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('post' in value) || value['post'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('chatbotName' in value) || value['chatbotName'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function LikePostNotificationFromJSON(json: any): LikePostNotification {
    return LikePostNotificationFromJSONTyped(json, false);
}

export function LikePostNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikePostNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationType': json['notification_type'] == null ? undefined : NotificationTypeFromJSON(json['notification_type']),
        'isRead': json['is_read'],
        'createdAt': (new Date(json['created_at'])),
        'sender': json['sender'] == null ? undefined : PublicUserPreviewFromJSON(json['sender']),
        'post': WallPostFromJSON(json['post']),
        'totalCount': json['total_count'],
        'chatbotName': json['chatbot_name'],
        'type': PostTypeFromJSON(json['type']),
    };
}

  export function LikePostNotificationToJSON(json: any): LikePostNotification {
      return LikePostNotificationToJSONTyped(json, false);
  }

  export function LikePostNotificationToJSONTyped(value?: LikePostNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notification_type': NotificationTypeToJSON(value['notificationType']),
        'is_read': value['isRead'],
        'created_at': ((value['createdAt']).toISOString()),
        'sender': PublicUserPreviewToJSON(value['sender']),
        'post': WallPostToJSON(value['post']),
        'total_count': value['totalCount'],
        'chatbot_name': value['chatbotName'],
        'type': PostTypeToJSON(value['type']),
    };
}

