/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssistantChatSessionDetail } from './AssistantChatSessionDetail';
import {
    AssistantChatSessionDetailFromJSON,
    AssistantChatSessionDetailFromJSONTyped,
    AssistantChatSessionDetailToJSON,
    AssistantChatSessionDetailToJSONTyped,
} from './AssistantChatSessionDetail';

/**
 * 
 * @export
 * @interface ListAssistantChatSessionsResponse
 */
export interface ListAssistantChatSessionsResponse {
    /**
     * 
     * @type {Array<AssistantChatSessionDetail>}
     * @memberof ListAssistantChatSessionsResponse
     */
    sessions: Array<AssistantChatSessionDetail>;
    /**
     * 
     * @type {string}
     * @memberof ListAssistantChatSessionsResponse
     */
    paginationToken?: string | null;
}

/**
 * Check if a given object implements the ListAssistantChatSessionsResponse interface.
 */
export function instanceOfListAssistantChatSessionsResponse(value: object): value is ListAssistantChatSessionsResponse {
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    return true;
}

export function ListAssistantChatSessionsResponseFromJSON(json: any): ListAssistantChatSessionsResponse {
    return ListAssistantChatSessionsResponseFromJSONTyped(json, false);
}

export function ListAssistantChatSessionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAssistantChatSessionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': ((json['sessions'] as Array<any>).map(AssistantChatSessionDetailFromJSON)),
        'paginationToken': json['pagination_token'] == null ? undefined : json['pagination_token'],
    };
}

  export function ListAssistantChatSessionsResponseToJSON(json: any): ListAssistantChatSessionsResponse {
      return ListAssistantChatSessionsResponseToJSONTyped(json, false);
  }

  export function ListAssistantChatSessionsResponseToJSONTyped(value?: ListAssistantChatSessionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': ((value['sessions'] as Array<any>).map(AssistantChatSessionDetailToJSON)),
        'pagination_token': value['paginationToken'],
    };
}

