/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationListItem } from './ConversationListItem';
import {
    ConversationListItemFromJSON,
    ConversationListItemFromJSONTyped,
    ConversationListItemToJSON,
    ConversationListItemToJSONTyped,
} from './ConversationListItem';

/**
 * 
 * @export
 * @interface ListConversationsResponse
 */
export interface ListConversationsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListConversationsResponse
     */
    paginationToken?: string | null;
    /**
     * 
     * @type {Array<ConversationListItem>}
     * @memberof ListConversationsResponse
     */
    conversations: Array<ConversationListItem>;
}

/**
 * Check if a given object implements the ListConversationsResponse interface.
 */
export function instanceOfListConversationsResponse(value: object): value is ListConversationsResponse {
    if (!('conversations' in value) || value['conversations'] === undefined) return false;
    return true;
}

export function ListConversationsResponseFromJSON(json: any): ListConversationsResponse {
    return ListConversationsResponseFromJSONTyped(json, false);
}

export function ListConversationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConversationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'paginationToken': json['pagination_token'] == null ? undefined : json['pagination_token'],
        'conversations': ((json['conversations'] as Array<any>).map(ConversationListItemFromJSON)),
    };
}

  export function ListConversationsResponseToJSON(json: any): ListConversationsResponse {
      return ListConversationsResponseToJSONTyped(json, false);
  }

  export function ListConversationsResponseToJSONTyped(value?: ListConversationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination_token': value['paginationToken'],
        'conversations': ((value['conversations'] as Array<any>).map(ConversationListItemToJSON)),
    };
}

