/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemoryChat
 */
export interface MemoryChat {
    /**
     * 
     * @type {string}
     * @memberof MemoryChat
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryChat
     */
    memory: string;
}

/**
 * Check if a given object implements the MemoryChat interface.
 */
export function instanceOfMemoryChat(value: object): value is MemoryChat {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    return true;
}

export function MemoryChatFromJSON(json: any): MemoryChat {
    return MemoryChatFromJSONTyped(json, false);
}

export function MemoryChatFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryChat {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'memory': json['memory'],
    };
}

  export function MemoryChatToJSON(json: any): MemoryChat {
      return MemoryChatToJSONTyped(json, false);
  }

  export function MemoryChatToJSONTyped(value?: MemoryChat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'memory': value['memory'],
    };
}

