/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemoryUpdateReponse
 */
export interface MemoryUpdateReponse {
    /**
     * 
     * @type {number}
     * @memberof MemoryUpdateReponse
     */
    memoryCharCount: number;
}

/**
 * Check if a given object implements the MemoryUpdateReponse interface.
 */
export function instanceOfMemoryUpdateReponse(value: object): value is MemoryUpdateReponse {
    if (!('memoryCharCount' in value) || value['memoryCharCount'] === undefined) return false;
    return true;
}

export function MemoryUpdateReponseFromJSON(json: any): MemoryUpdateReponse {
    return MemoryUpdateReponseFromJSONTyped(json, false);
}

export function MemoryUpdateReponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryUpdateReponse {
    if (json == null) {
        return json;
    }
    return {
        
        'memoryCharCount': json['memory_char_count'],
    };
}

  export function MemoryUpdateReponseToJSON(json: any): MemoryUpdateReponse {
      return MemoryUpdateReponseToJSONTyped(json, false);
  }

  export function MemoryUpdateReponseToJSONTyped(value?: MemoryUpdateReponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memory_char_count': value['memoryCharCount'],
    };
}

