/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationMessageFeedback } from './ConversationMessageFeedback';
import {
    ConversationMessageFeedbackFromJSON,
    ConversationMessageFeedbackFromJSONTyped,
    ConversationMessageFeedbackToJSON,
    ConversationMessageFeedbackToJSONTyped,
} from './ConversationMessageFeedback';

/**
 * 
 * @export
 * @interface PatchChatMessageRequest
 */
export interface PatchChatMessageRequest {
    /**
     * 
     * @type {ConversationMessageFeedback}
     * @memberof PatchChatMessageRequest
     */
    feedback?: ConversationMessageFeedback | null;
}



/**
 * Check if a given object implements the PatchChatMessageRequest interface.
 */
export function instanceOfPatchChatMessageRequest(value: object): value is PatchChatMessageRequest {
    return true;
}

export function PatchChatMessageRequestFromJSON(json: any): PatchChatMessageRequest {
    return PatchChatMessageRequestFromJSONTyped(json, false);
}

export function PatchChatMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchChatMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'feedback': json['feedback'] == null ? undefined : ConversationMessageFeedbackFromJSON(json['feedback']),
    };
}

  export function PatchChatMessageRequestToJSON(json: any): PatchChatMessageRequest {
      return PatchChatMessageRequestToJSONTyped(json, false);
  }

  export function PatchChatMessageRequestToJSONTyped(value?: PatchChatMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feedback': ConversationMessageFeedbackToJSON(value['feedback']),
    };
}

