/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagData } from './TagData';
import {
    TagDataFromJSON,
    TagDataFromJSONTyped,
    TagDataToJSON,
    TagDataToJSONTyped,
} from './TagData';

/**
 * 
 * @export
 * @interface PatchCustomChatbotRequest
 */
export interface PatchCustomChatbotRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchCustomChatbotRequest
     */
    displayName: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchCustomChatbotRequest
     */
    profilePictureId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchCustomChatbotRequest
     */
    profileVideoId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchCustomChatbotRequest
     */
    bio: string | null;
    /**
     * 
     * @type {Array<TagData>}
     * @memberof PatchCustomChatbotRequest
     */
    tags: Array<TagData> | null;
}

/**
 * Check if a given object implements the PatchCustomChatbotRequest interface.
 */
export function instanceOfPatchCustomChatbotRequest(value: object): value is PatchCustomChatbotRequest {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('profilePictureId' in value) || value['profilePictureId'] === undefined) return false;
    if (!('profileVideoId' in value) || value['profileVideoId'] === undefined) return false;
    if (!('bio' in value) || value['bio'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function PatchCustomChatbotRequestFromJSON(json: any): PatchCustomChatbotRequest {
    return PatchCustomChatbotRequestFromJSONTyped(json, false);
}

export function PatchCustomChatbotRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchCustomChatbotRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'],
        'profilePictureId': json['profile_picture_id'],
        'profileVideoId': json['profile_video_id'],
        'bio': json['bio'],
        'tags': (json['tags'] == null ? null : (json['tags'] as Array<any>).map(TagDataFromJSON)),
    };
}

  export function PatchCustomChatbotRequestToJSON(json: any): PatchCustomChatbotRequest {
      return PatchCustomChatbotRequestToJSONTyped(json, false);
  }

  export function PatchCustomChatbotRequestToJSONTyped(value?: PatchCustomChatbotRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'profile_picture_id': value['profilePictureId'],
        'profile_video_id': value['profileVideoId'],
        'bio': value['bio'],
        'tags': (value['tags'] == null ? null : (value['tags'] as Array<any>).map(TagDataToJSON)),
    };
}

