/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SharedContentType } from './SharedContentType';
import {
    SharedContentTypeFromJSON,
    SharedContentTypeFromJSONTyped,
    SharedContentTypeToJSON,
    SharedContentTypeToJSONTyped,
} from './SharedContentType';

/**
 * 
 * @export
 * @interface PostShareGetTagsRequest
 */
export interface PostShareGetTagsRequest {
    /**
     * 
     * @type {SharedContentType}
     * @memberof PostShareGetTagsRequest
     */
    sharableContentType: SharedContentType;
}



/**
 * Check if a given object implements the PostShareGetTagsRequest interface.
 */
export function instanceOfPostShareGetTagsRequest(value: object): value is PostShareGetTagsRequest {
    if (!('sharableContentType' in value) || value['sharableContentType'] === undefined) return false;
    return true;
}

export function PostShareGetTagsRequestFromJSON(json: any): PostShareGetTagsRequest {
    return PostShareGetTagsRequestFromJSONTyped(json, false);
}

export function PostShareGetTagsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostShareGetTagsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sharableContentType': SharedContentTypeFromJSON(json['sharable_content_type']),
    };
}

  export function PostShareGetTagsRequestToJSON(json: any): PostShareGetTagsRequest {
      return PostShareGetTagsRequestToJSONTyped(json, false);
  }

  export function PostShareGetTagsRequestToJSONTyped(value?: PostShareGetTagsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sharable_content_type': SharedContentTypeToJSON(value['sharableContentType']),
    };
}

