/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImagenResponse
 */
export interface PostImagenResponse {
    /**
     * 
     * @type {string}
     * @memberof PostImagenResponse
     */
    eta: string;
}

/**
 * Check if a given object implements the PostImagenResponse interface.
 */
export function instanceOfPostImagenResponse(value: object): value is PostImagenResponse {
    if (!('eta' in value) || value['eta'] === undefined) return false;
    return true;
}

export function PostImagenResponseFromJSON(json: any): PostImagenResponse {
    return PostImagenResponseFromJSONTyped(json, false);
}

export function PostImagenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImagenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'eta': json['eta'],
    };
}

  export function PostImagenResponseToJSON(json: any): PostImagenResponse {
      return PostImagenResponseToJSONTyped(json, false);
  }

  export function PostImagenResponseToJSONTyped(value?: PostImagenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eta': value['eta'],
    };
}

