/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostDonateResponse
 */
export interface PostDonateResponse {
    /**
     * 
     * @type {string}
     * @memberof PostDonateResponse
     */
    donationId: string;
    /**
     * 
     * @type {number}
     * @memberof PostDonateResponse
     */
    newBalance: number;
}

/**
 * Check if a given object implements the PostDonateResponse interface.
 */
export function instanceOfPostDonateResponse(value: object): value is PostDonateResponse {
    if (!('donationId' in value) || value['donationId'] === undefined) return false;
    if (!('newBalance' in value) || value['newBalance'] === undefined) return false;
    return true;
}

export function PostDonateResponseFromJSON(json: any): PostDonateResponse {
    return PostDonateResponseFromJSONTyped(json, false);
}

export function PostDonateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDonateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'donationId': json['donation_id'],
        'newBalance': json['new_balance'],
    };
}

  export function PostDonateResponseToJSON(json: any): PostDonateResponse {
      return PostDonateResponseToJSONTyped(json, false);
  }

  export function PostDonateResponseToJSONTyped(value?: PostDonateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'donation_id': value['donationId'],
        'new_balance': value['newBalance'],
    };
}

