/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharacterBuilderSuggestionField } from './CharacterBuilderSuggestionField';
import {
    CharacterBuilderSuggestionFieldFromJSON,
    CharacterBuilderSuggestionFieldFromJSONTyped,
    CharacterBuilderSuggestionFieldToJSON,
    CharacterBuilderSuggestionFieldToJSONTyped,
} from './CharacterBuilderSuggestionField';

/**
 * 
 * @export
 * @interface PostAdvancedCharacterBuilderSuggestionResponse
 */
export interface PostAdvancedCharacterBuilderSuggestionResponse {
    /**
     * 
     * @type {CharacterBuilderSuggestionField}
     * @memberof PostAdvancedCharacterBuilderSuggestionResponse
     */
    fieldName: CharacterBuilderSuggestionField;
    /**
     * 
     * @type {string}
     * @memberof PostAdvancedCharacterBuilderSuggestionResponse
     */
    suggestion: string;
}



/**
 * Check if a given object implements the PostAdvancedCharacterBuilderSuggestionResponse interface.
 */
export function instanceOfPostAdvancedCharacterBuilderSuggestionResponse(value: object): value is PostAdvancedCharacterBuilderSuggestionResponse {
    if (!('fieldName' in value) || value['fieldName'] === undefined) return false;
    if (!('suggestion' in value) || value['suggestion'] === undefined) return false;
    return true;
}

export function PostAdvancedCharacterBuilderSuggestionResponseFromJSON(json: any): PostAdvancedCharacterBuilderSuggestionResponse {
    return PostAdvancedCharacterBuilderSuggestionResponseFromJSONTyped(json, false);
}

export function PostAdvancedCharacterBuilderSuggestionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdvancedCharacterBuilderSuggestionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fieldName': CharacterBuilderSuggestionFieldFromJSON(json['field_name']),
        'suggestion': json['suggestion'],
    };
}

  export function PostAdvancedCharacterBuilderSuggestionResponseToJSON(json: any): PostAdvancedCharacterBuilderSuggestionResponse {
      return PostAdvancedCharacterBuilderSuggestionResponseToJSONTyped(json, false);
  }

  export function PostAdvancedCharacterBuilderSuggestionResponseToJSONTyped(value?: PostAdvancedCharacterBuilderSuggestionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field_name': CharacterBuilderSuggestionFieldToJSON(value['fieldName']),
        'suggestion': value['suggestion'],
    };
}

