/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostVerifyPublicUsernameResponse
 */
export interface PostVerifyPublicUsernameResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PostVerifyPublicUsernameResponse
     */
    available: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostVerifyPublicUsernameResponse
     */
    reason?: string | null;
}

/**
 * Check if a given object implements the PostVerifyPublicUsernameResponse interface.
 */
export function instanceOfPostVerifyPublicUsernameResponse(value: object): value is PostVerifyPublicUsernameResponse {
    if (!('available' in value) || value['available'] === undefined) return false;
    return true;
}

export function PostVerifyPublicUsernameResponseFromJSON(json: any): PostVerifyPublicUsernameResponse {
    return PostVerifyPublicUsernameResponseFromJSONTyped(json, false);
}

export function PostVerifyPublicUsernameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVerifyPublicUsernameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

  export function PostVerifyPublicUsernameResponseToJSON(json: any): PostVerifyPublicUsernameResponse {
      return PostVerifyPublicUsernameResponseToJSONTyped(json, false);
  }

  export function PostVerifyPublicUsernameResponseToJSONTyped(value?: PostVerifyPublicUsernameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
        'reason': value['reason'],
    };
}

