/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostRatingRequest
 */
export interface PostRatingRequest {
    /**
     * 
     * @type {number}
     * @memberof PostRatingRequest
     */
    girls: number;
    /**
     * 
     * @type {number}
     * @memberof PostRatingRequest
     */
    anime: number;
    /**
     * 
     * @type {number}
     * @memberof PostRatingRequest
     */
    enoughContent: number;
    /**
     * 
     * @type {number}
     * @memberof PostRatingRequest
     */
    chat: number;
    /**
     * 
     * @type {string}
     * @memberof PostRatingRequest
     */
    other: string;
}

/**
 * Check if a given object implements the PostRatingRequest interface.
 */
export function instanceOfPostRatingRequest(value: object): value is PostRatingRequest {
    if (!('girls' in value) || value['girls'] === undefined) return false;
    if (!('anime' in value) || value['anime'] === undefined) return false;
    if (!('enoughContent' in value) || value['enoughContent'] === undefined) return false;
    if (!('chat' in value) || value['chat'] === undefined) return false;
    if (!('other' in value) || value['other'] === undefined) return false;
    return true;
}

export function PostRatingRequestFromJSON(json: any): PostRatingRequest {
    return PostRatingRequestFromJSONTyped(json, false);
}

export function PostRatingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRatingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'girls': json['girls'],
        'anime': json['anime'],
        'enoughContent': json['enoughContent'],
        'chat': json['chat'],
        'other': json['other'],
    };
}

  export function PostRatingRequestToJSON(json: any): PostRatingRequest {
      return PostRatingRequestToJSONTyped(json, false);
  }

  export function PostRatingRequestToJSONTyped(value?: PostRatingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'girls': value['girls'],
        'anime': value['anime'],
        'enoughContent': value['enoughContent'],
        'chat': value['chat'],
        'other': value['other'],
    };
}

