/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostDetails
 */
export interface PostDetails {
    /**
     * 
     * @type {string}
     * @memberof PostDetails
     */
    postId: string;
    /**
     * 
     * @type {number}
     * @memberof PostDetails
     */
    likes: number;
    /**
     * 
     * @type {boolean}
     * @memberof PostDetails
     */
    likedByUser: boolean;
}

/**
 * Check if a given object implements the PostDetails interface.
 */
export function instanceOfPostDetails(value: object): value is PostDetails {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('likes' in value) || value['likes'] === undefined) return false;
    if (!('likedByUser' in value) || value['likedByUser'] === undefined) return false;
    return true;
}

export function PostDetailsFromJSON(json: any): PostDetails {
    return PostDetailsFromJSONTyped(json, false);
}

export function PostDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['post_id'],
        'likes': json['likes'],
        'likedByUser': json['liked_by_user'],
    };
}

  export function PostDetailsToJSON(json: any): PostDetails {
      return PostDetailsToJSONTyped(json, false);
  }

  export function PostDetailsToJSONTyped(value?: PostDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post_id': value['postId'],
        'likes': value['likes'],
        'liked_by_user': value['likedByUser'],
    };
}

