/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostResendEmailRequest
 */
export interface PostResendEmailRequest {
    /**
     * The email of the user
     * @type {string}
     * @memberof PostResendEmailRequest
     */
    email: string;
}

/**
 * Check if a given object implements the PostResendEmailRequest interface.
 */
export function instanceOfPostResendEmailRequest(value: object): value is PostResendEmailRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function PostResendEmailRequestFromJSON(json: any): PostResendEmailRequest {
    return PostResendEmailRequestFromJSONTyped(json, false);
}

export function PostResendEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostResendEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

  export function PostResendEmailRequestToJSON(json: any): PostResendEmailRequest {
      return PostResendEmailRequestToJSONTyped(json, false);
  }

  export function PostResendEmailRequestToJSONTyped(value?: PostResendEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

