/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssistantChatRoute } from './AssistantChatRoute';
import {
    AssistantChatRouteFromJSON,
    AssistantChatRouteFromJSONTyped,
    AssistantChatRouteToJSON,
    AssistantChatRouteToJSONTyped,
} from './AssistantChatRoute';

/**
 * 
 * @export
 * @interface PostAssistantChatMessageRequest
 */
export interface PostAssistantChatMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof PostAssistantChatMessageRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof PostAssistantChatMessageRequest
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof PostAssistantChatMessageRequest
     */
    query: string;
    /**
     * 
     * @type {string}
     * @memberof PostAssistantChatMessageRequest
     */
    episodeId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PostAssistantChatMessageRequest
     */
    debug?: boolean | null;
    /**
     * Assistant chat backend route
     * @type {AssistantChatRoute}
     * @memberof PostAssistantChatMessageRequest
     */
    route?: AssistantChatRoute;
}



/**
 * Check if a given object implements the PostAssistantChatMessageRequest interface.
 */
export function instanceOfPostAssistantChatMessageRequest(value: object): value is PostAssistantChatMessageRequest {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function PostAssistantChatMessageRequestFromJSON(json: any): PostAssistantChatMessageRequest {
    return PostAssistantChatMessageRequestFromJSONTyped(json, false);
}

export function PostAssistantChatMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAssistantChatMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'requestId': json['request_id'],
        'query': json['query'],
        'episodeId': json['episode_id'] == null ? undefined : json['episode_id'],
        'debug': json['debug'] == null ? undefined : json['debug'],
        'route': json['route'] == null ? undefined : AssistantChatRouteFromJSON(json['route']),
    };
}

  export function PostAssistantChatMessageRequestToJSON(json: any): PostAssistantChatMessageRequest {
      return PostAssistantChatMessageRequestToJSONTyped(json, false);
  }

  export function PostAssistantChatMessageRequestToJSONTyped(value?: PostAssistantChatMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'request_id': value['requestId'],
        'query': value['query'],
        'episode_id': value['episodeId'],
        'debug': value['debug'],
        'route': AssistantChatRouteToJSON(value['route']),
    };
}

