/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentReportReason } from './ContentReportReason';
import {
    ContentReportReasonFromJSON,
    ContentReportReasonFromJSONTyped,
    ContentReportReasonToJSON,
    ContentReportReasonToJSONTyped,
} from './ContentReportReason';

/**
 * 
 * @export
 * @interface PostReportRequest
 */
export interface PostReportRequest {
    /**
     * 
     * @type {Array<ContentReportReason>}
     * @memberof PostReportRequest
     */
    reason: Array<ContentReportReason>;
}

/**
 * Check if a given object implements the PostReportRequest interface.
 */
export function instanceOfPostReportRequest(value: object): value is PostReportRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function PostReportRequestFromJSON(json: any): PostReportRequest {
    return PostReportRequestFromJSONTyped(json, false);
}

export function PostReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': ((json['reason'] as Array<any>).map(ContentReportReasonFromJSON)),
    };
}

  export function PostReportRequestToJSON(json: any): PostReportRequest {
      return PostReportRequestToJSONTyped(json, false);
  }

  export function PostReportRequestToJSONTyped(value?: PostReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': ((value['reason'] as Array<any>).map(ContentReportReasonToJSON)),
    };
}

