/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FantasyRace } from './FantasyRace';
import {
    FantasyRaceFromJSON,
    FantasyRaceFromJSONTyped,
    FantasyRaceToJSON,
    FantasyRaceToJSONTyped,
} from './FantasyRace';
import type { SpecialFeatures } from './SpecialFeatures';
import {
    SpecialFeaturesFromJSON,
    SpecialFeaturesFromJSONTyped,
    SpecialFeaturesToJSON,
    SpecialFeaturesToJSONTyped,
} from './SpecialFeatures';
import type { Ethnicity } from './Ethnicity';
import {
    EthnicityFromJSON,
    EthnicityFromJSONTyped,
    EthnicityToJSON,
    EthnicityToJSONTyped,
} from './Ethnicity';
import type { ArtStyle } from './ArtStyle';
import {
    ArtStyleFromJSON,
    ArtStyleFromJSONTyped,
    ArtStyleToJSON,
    ArtStyleToJSONTyped,
} from './ArtStyle';
import type { FurryVisualType } from './FurryVisualType';
import {
    FurryVisualTypeFromJSON,
    FurryVisualTypeFromJSONTyped,
    FurryVisualTypeToJSON,
    FurryVisualTypeToJSONTyped,
} from './FurryVisualType';
import type { RoleplayType } from './RoleplayType';
import {
    RoleplayTypeFromJSON,
    RoleplayTypeFromJSONTyped,
    RoleplayTypeToJSON,
    RoleplayTypeToJSONTyped,
} from './RoleplayType';
import type { VisualType } from './VisualType';
import {
    VisualTypeFromJSON,
    VisualTypeFromJSONTyped,
    VisualTypeToJSON,
    VisualTypeToJSONTyped,
} from './VisualType';
import type { SeduceDifficulty } from './SeduceDifficulty';
import {
    SeduceDifficultyFromJSON,
    SeduceDifficultyFromJSONTyped,
    SeduceDifficultyToJSON,
    SeduceDifficultyToJSONTyped,
} from './SeduceDifficulty';
import type { AvatarLooksV2 } from './AvatarLooksV2';
import {
    AvatarLooksV2FromJSON,
    AvatarLooksV2FromJSONTyped,
    AvatarLooksV2ToJSON,
    AvatarLooksV2ToJSONTyped,
} from './AvatarLooksV2';

/**
 * 
 * @export
 * @interface PostCustomChatbotV2Payload
 */
export interface PostCustomChatbotV2Payload {
    /**
     * 
     * @type {number}
     * @memberof PostCustomChatbotV2Payload
     */
    age: number;
    /**
     * 
     * @type {Array<SpecialFeatures>}
     * @memberof PostCustomChatbotV2Payload
     */
    specialFeatures: Array<SpecialFeatures>;
    /**
     * 
     * @type {ArtStyle}
     * @memberof PostCustomChatbotV2Payload
     */
    artStyle: ArtStyle;
    /**
     * 
     * @type {Ethnicity}
     * @memberof PostCustomChatbotV2Payload
     */
    ethnicity?: Ethnicity | null;
    /**
     * 
     * @type {FantasyRace}
     * @memberof PostCustomChatbotV2Payload
     */
    fantasyRace?: FantasyRace | null;
    /**
     * 
     * @type {VisualType}
     * @memberof PostCustomChatbotV2Payload
     */
    visualType?: VisualType | null;
    /**
     * 
     * @type {FurryVisualType}
     * @memberof PostCustomChatbotV2Payload
     */
    furryVisualType?: FurryVisualType | null;
    /**
     * 
     * @type {RoleplayType}
     * @memberof PostCustomChatbotV2Payload
     */
    roleplayType?: RoleplayType | null;
    /**
     * 
     * @type {AvatarLooksV2}
     * @memberof PostCustomChatbotV2Payload
     */
    looks: AvatarLooksV2;
    /**
     * 
     * @type {SeduceDifficulty}
     * @memberof PostCustomChatbotV2Payload
     */
    difficulty: SeduceDifficulty;
    /**
     * 
     * @type {string}
     * @memberof PostCustomChatbotV2Payload
     */
    scenario: string;
    /**
     * 
     * @type {string}
     * @memberof PostCustomChatbotV2Payload
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof PostCustomChatbotV2Payload
     */
    referenceAudioId?: string;
    /**
     * 
     * @type {string}
     * @memberof PostCustomChatbotV2Payload
     */
    userId?: string | null;
}



/**
 * Check if a given object implements the PostCustomChatbotV2Payload interface.
 */
export function instanceOfPostCustomChatbotV2Payload(value: object): value is PostCustomChatbotV2Payload {
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('specialFeatures' in value) || value['specialFeatures'] === undefined) return false;
    if (!('artStyle' in value) || value['artStyle'] === undefined) return false;
    if (!('looks' in value) || value['looks'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('scenario' in value) || value['scenario'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    return true;
}

export function PostCustomChatbotV2PayloadFromJSON(json: any): PostCustomChatbotV2Payload {
    return PostCustomChatbotV2PayloadFromJSONTyped(json, false);
}

export function PostCustomChatbotV2PayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCustomChatbotV2Payload {
    if (json == null) {
        return json;
    }
    return {
        
        'age': json['age'],
        'specialFeatures': ((json['special_features'] as Array<any>).map(SpecialFeaturesFromJSON)),
        'artStyle': ArtStyleFromJSON(json['art_style']),
        'ethnicity': json['ethnicity'] == null ? undefined : EthnicityFromJSON(json['ethnicity']),
        'fantasyRace': json['fantasy_race'] == null ? undefined : FantasyRaceFromJSON(json['fantasy_race']),
        'visualType': json['visual_type'] == null ? undefined : VisualTypeFromJSON(json['visual_type']),
        'furryVisualType': json['furry_visual_type'] == null ? undefined : FurryVisualTypeFromJSON(json['furry_visual_type']),
        'roleplayType': json['roleplay_type'] == null ? undefined : RoleplayTypeFromJSON(json['roleplay_type']),
        'looks': AvatarLooksV2FromJSON(json['looks']),
        'difficulty': SeduceDifficultyFromJSON(json['difficulty']),
        'scenario': json['scenario'],
        'clientId': json['client_id'],
        'referenceAudioId': json['reference_audio_id'] == null ? undefined : json['reference_audio_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

  export function PostCustomChatbotV2PayloadToJSON(json: any): PostCustomChatbotV2Payload {
      return PostCustomChatbotV2PayloadToJSONTyped(json, false);
  }

  export function PostCustomChatbotV2PayloadToJSONTyped(value?: PostCustomChatbotV2Payload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'age': value['age'],
        'special_features': ((value['specialFeatures'] as Array<any>).map(SpecialFeaturesToJSON)),
        'art_style': ArtStyleToJSON(value['artStyle']),
        'ethnicity': EthnicityToJSON(value['ethnicity']),
        'fantasy_race': FantasyRaceToJSON(value['fantasyRace']),
        'visual_type': VisualTypeToJSON(value['visualType']),
        'furry_visual_type': FurryVisualTypeToJSON(value['furryVisualType']),
        'roleplay_type': RoleplayTypeToJSON(value['roleplayType']),
        'looks': AvatarLooksV2ToJSON(value['looks']),
        'difficulty': SeduceDifficultyToJSON(value['difficulty']),
        'scenario': value['scenario'],
        'client_id': value['clientId'],
        'reference_audio_id': value['referenceAudioId'],
        'user_id': value['userId'],
    };
}

