/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BadgePreview } from './BadgePreview';
import {
    BadgePreviewFromJSON,
    BadgePreviewFromJSONTyped,
    BadgePreviewToJSON,
    BadgePreviewToJSONTyped,
} from './BadgePreview';

/**
 * 
 * @export
 * @interface PublicUserPreview
 */
export interface PublicUserPreview {
    /**
     * 
     * @type {string}
     * @memberof PublicUserPreview
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof PublicUserPreview
     */
    publicUsername: string;
    /**
     * 
     * @type {string}
     * @memberof PublicUserPreview
     */
    avatarUrl: string | null;
    /**
     * 
     * @type {BadgePreview}
     * @memberof PublicUserPreview
     */
    selectedBadge: BadgePreview | null;
}

/**
 * Check if a given object implements the PublicUserPreview interface.
 */
export function instanceOfPublicUserPreview(value: object): value is PublicUserPreview {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('publicUsername' in value) || value['publicUsername'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    if (!('selectedBadge' in value) || value['selectedBadge'] === undefined) return false;
    return true;
}

export function PublicUserPreviewFromJSON(json: any): PublicUserPreview {
    return PublicUserPreviewFromJSONTyped(json, false);
}

export function PublicUserPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicUserPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'publicUsername': json['public_username'],
        'avatarUrl': json['avatar_url'],
        'selectedBadge': BadgePreviewFromJSON(json['selected_badge']),
    };
}

  export function PublicUserPreviewToJSON(json: any): PublicUserPreview {
      return PublicUserPreviewToJSONTyped(json, false);
  }

  export function PublicUserPreviewToJSONTyped(value?: PublicUserPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'public_username': value['publicUsername'],
        'avatar_url': value['avatarUrl'],
        'selected_badge': BadgePreviewToJSON(value['selectedBadge']),
    };
}

