/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutPublicUserRequest
 */
export interface PutPublicUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PutPublicUserRequest
     */
    publicUsername: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutPublicUserRequest
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutPublicUserRequest
     */
    generatedPictureId?: string | null;
}

/**
 * Check if a given object implements the PutPublicUserRequest interface.
 */
export function instanceOfPutPublicUserRequest(value: object): value is PutPublicUserRequest {
    if (!('publicUsername' in value) || value['publicUsername'] === undefined) return false;
    return true;
}

export function PutPublicUserRequestFromJSON(json: any): PutPublicUserRequest {
    return PutPublicUserRequestFromJSONTyped(json, false);
}

export function PutPublicUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutPublicUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'publicUsername': json['public_username'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'generatedPictureId': json['generated_picture_id'] == null ? undefined : json['generated_picture_id'],
    };
}

  export function PutPublicUserRequestToJSON(json: any): PutPublicUserRequest {
      return PutPublicUserRequestToJSONTyped(json, false);
  }

  export function PutPublicUserRequestToJSONTyped(value?: PutPublicUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_username': value['publicUsername'],
        'bio': value['bio'],
        'generated_picture_id': value['generatedPictureId'],
    };
}

