/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReorderEpisodesItem
 */
export interface ReorderEpisodesItem {
    /**
     * 
     * @type {string}
     * @memberof ReorderEpisodesItem
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ReorderEpisodesItem
     */
    episodeOrder: number;
}

/**
 * Check if a given object implements the ReorderEpisodesItem interface.
 */
export function instanceOfReorderEpisodesItem(value: object): value is ReorderEpisodesItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('episodeOrder' in value) || value['episodeOrder'] === undefined) return false;
    return true;
}

export function ReorderEpisodesItemFromJSON(json: any): ReorderEpisodesItem {
    return ReorderEpisodesItemFromJSONTyped(json, false);
}

export function ReorderEpisodesItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderEpisodesItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'episodeOrder': json['episode_order'],
    };
}

  export function ReorderEpisodesItemToJSON(json: any): ReorderEpisodesItem {
      return ReorderEpisodesItemToJSONTyped(json, false);
  }

  export function ReorderEpisodesItemToJSONTyped(value?: ReorderEpisodesItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'episode_order': value['episodeOrder'],
    };
}

