/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendCustomMemoracekRequest
 */
export interface SendCustomMemoracekRequest {
    /**
     * 
     * @type {string}
     * @memberof SendCustomMemoracekRequest
     */
    text: string;
}

/**
 * Check if a given object implements the SendCustomMemoracekRequest interface.
 */
export function instanceOfSendCustomMemoracekRequest(value: object): value is SendCustomMemoracekRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SendCustomMemoracekRequestFromJSON(json: any): SendCustomMemoracekRequest {
    return SendCustomMemoracekRequestFromJSONTyped(json, false);
}

export function SendCustomMemoracekRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendCustomMemoracekRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

  export function SendCustomMemoracekRequestToJSON(json: any): SendCustomMemoracekRequest {
      return SendCustomMemoracekRequestToJSONTyped(json, false);
  }

  export function SendCustomMemoracekRequestToJSONTyped(value?: SendCustomMemoracekRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

