/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface SexualOrientation
 */
export interface SexualOrientation {
}

/**
 * Check if a given object implements the SexualOrientation interface.
 */
export function instanceOfSexualOrientation(value: object): value is SexualOrientation {
    return true;
}

export function SexualOrientationFromJSON(json: any): SexualOrientation {
    return SexualOrientationFromJSONTyped(json, false);
}

export function SexualOrientationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SexualOrientation {
    return json;
}

  export function SexualOrientationToJSON(json: any): SexualOrientation {
      return SexualOrientationToJSONTyped(json, false);
  }

  export function SexualOrientationToJSONTyped(value?: SexualOrientation | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

