/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryCreatorEpisode } from './StoryCreatorEpisode';
import {
    StoryCreatorEpisodeFromJSON,
    StoryCreatorEpisodeFromJSONTyped,
    StoryCreatorEpisodeToJSON,
    StoryCreatorEpisodeToJSONTyped,
} from './StoryCreatorEpisode';

/**
 * 
 * @export
 * @interface StoryCreatorStoryWithEpisodes
 */
export interface StoryCreatorStoryWithEpisodes {
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorStoryWithEpisodes
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorStoryWithEpisodes
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorStoryWithEpisodes
     */
    coverImage?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StoryCreatorStoryWithEpisodes
     */
    newerVersionExists?: boolean | null;
    /**
     * 
     * @type {Array<StoryCreatorEpisode>}
     * @memberof StoryCreatorStoryWithEpisodes
     */
    episodes: Array<StoryCreatorEpisode>;
}

/**
 * Check if a given object implements the StoryCreatorStoryWithEpisodes interface.
 */
export function instanceOfStoryCreatorStoryWithEpisodes(value: object): value is StoryCreatorStoryWithEpisodes {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('episodes' in value) || value['episodes'] === undefined) return false;
    return true;
}

export function StoryCreatorStoryWithEpisodesFromJSON(json: any): StoryCreatorStoryWithEpisodes {
    return StoryCreatorStoryWithEpisodesFromJSONTyped(json, false);
}

export function StoryCreatorStoryWithEpisodesFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorStoryWithEpisodes {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'newerVersionExists': json['newer_version_exists'] == null ? undefined : json['newer_version_exists'],
        'episodes': ((json['episodes'] as Array<any>).map(StoryCreatorEpisodeFromJSON)),
    };
}

  export function StoryCreatorStoryWithEpisodesToJSON(json: any): StoryCreatorStoryWithEpisodes {
      return StoryCreatorStoryWithEpisodesToJSONTyped(json, false);
  }

  export function StoryCreatorStoryWithEpisodesToJSONTyped(value?: StoryCreatorStoryWithEpisodes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'cover_image': value['coverImage'],
        'newer_version_exists': value['newerVersionExists'],
        'episodes': ((value['episodes'] as Array<any>).map(StoryCreatorEpisodeToJSON)),
    };
}

