/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryCreatorStory } from './StoryCreatorStory';
import {
    StoryCreatorStoryFromJSON,
    StoryCreatorStoryFromJSONTyped,
    StoryCreatorStoryToJSON,
    StoryCreatorStoryToJSONTyped,
} from './StoryCreatorStory';

/**
 * 
 * @export
 * @interface StoryCreatorStoryListResponse
 */
export interface StoryCreatorStoryListResponse {
    /**
     * 
     * @type {Array<StoryCreatorStory>}
     * @memberof StoryCreatorStoryListResponse
     */
    items: Array<StoryCreatorStory>;
}

/**
 * Check if a given object implements the StoryCreatorStoryListResponse interface.
 */
export function instanceOfStoryCreatorStoryListResponse(value: object): value is StoryCreatorStoryListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function StoryCreatorStoryListResponseFromJSON(json: any): StoryCreatorStoryListResponse {
    return StoryCreatorStoryListResponseFromJSONTyped(json, false);
}

export function StoryCreatorStoryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorStoryListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(StoryCreatorStoryFromJSON)),
    };
}

  export function StoryCreatorStoryListResponseToJSON(json: any): StoryCreatorStoryListResponse {
      return StoryCreatorStoryListResponseToJSONTyped(json, false);
  }

  export function StoryCreatorStoryListResponseToJSONTyped(value?: StoryCreatorStoryListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(StoryCreatorStoryToJSON)),
    };
}

