/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryVisibility } from './StoryVisibility';
import {
    StoryVisibilityFromJSON,
    StoryVisibilityFromJSONTyped,
    StoryVisibilityToJSON,
    StoryVisibilityToJSONTyped,
} from './StoryVisibility';
import type { UserStoryProgressType } from './UserStoryProgressType';
import {
    UserStoryProgressTypeFromJSON,
    UserStoryProgressTypeFromJSONTyped,
    UserStoryProgressTypeToJSON,
    UserStoryProgressTypeToJSONTyped,
} from './UserStoryProgressType';

/**
 * 
 * @export
 * @interface StoryCreatorStory
 */
export interface StoryCreatorStory {
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorStory
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorStory
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorStory
     */
    coverImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorStory
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorStory
     */
    ownerId: string;
    /**
     * 
     * @type {number}
     * @memberof StoryCreatorStory
     */
    rating?: number | null;
    /**
     * 
     * @type {UserStoryProgressType}
     * @memberof StoryCreatorStory
     */
    progress?: UserStoryProgressType | null;
    /**
     * 
     * @type {boolean}
     * @memberof StoryCreatorStory
     */
    newerVersionExists?: boolean | null;
    /**
     * 
     * @type {StoryVisibility}
     * @memberof StoryCreatorStory
     */
    visibility: StoryVisibility;
    /**
     * 
     * @type {number}
     * @memberof StoryCreatorStory
     */
    publicEpisodesCount: number;
    /**
     * 
     * @type {number}
     * @memberof StoryCreatorStory
     */
    publicPanelsCount: number;
}



/**
 * Check if a given object implements the StoryCreatorStory interface.
 */
export function instanceOfStoryCreatorStory(value: object): value is StoryCreatorStory {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('publicEpisodesCount' in value) || value['publicEpisodesCount'] === undefined) return false;
    if (!('publicPanelsCount' in value) || value['publicPanelsCount'] === undefined) return false;
    return true;
}

export function StoryCreatorStoryFromJSON(json: any): StoryCreatorStory {
    return StoryCreatorStoryFromJSONTyped(json, false);
}

export function StoryCreatorStoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorStory {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'id': json['id'],
        'ownerId': json['owner_id'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'progress': json['progress'] == null ? undefined : UserStoryProgressTypeFromJSON(json['progress']),
        'newerVersionExists': json['newer_version_exists'] == null ? undefined : json['newer_version_exists'],
        'visibility': StoryVisibilityFromJSON(json['visibility']),
        'publicEpisodesCount': json['public_episodes_count'],
        'publicPanelsCount': json['public_panels_count'],
    };
}

  export function StoryCreatorStoryToJSON(json: any): StoryCreatorStory {
      return StoryCreatorStoryToJSONTyped(json, false);
  }

  export function StoryCreatorStoryToJSONTyped(value?: StoryCreatorStory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'cover_image': value['coverImage'],
        'id': value['id'],
        'owner_id': value['ownerId'],
        'rating': value['rating'],
        'progress': UserStoryProgressTypeToJSON(value['progress']),
        'newer_version_exists': value['newerVersionExists'],
        'visibility': StoryVisibilityToJSON(value['visibility']),
        'public_episodes_count': value['publicEpisodesCount'],
        'public_panels_count': value['publicPanelsCount'],
    };
}

