/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryCreatorImportActorRequest
 */
export interface StoryCreatorImportActorRequest {
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorImportActorRequest
     */
    chatbotId: string;
}

/**
 * Check if a given object implements the StoryCreatorImportActorRequest interface.
 */
export function instanceOfStoryCreatorImportActorRequest(value: object): value is StoryCreatorImportActorRequest {
    if (!('chatbotId' in value) || value['chatbotId'] === undefined) return false;
    return true;
}

export function StoryCreatorImportActorRequestFromJSON(json: any): StoryCreatorImportActorRequest {
    return StoryCreatorImportActorRequestFromJSONTyped(json, false);
}

export function StoryCreatorImportActorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorImportActorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chatbotId': json['chatbot_id'],
    };
}

  export function StoryCreatorImportActorRequestToJSON(json: any): StoryCreatorImportActorRequest {
      return StoryCreatorImportActorRequestToJSONTyped(json, false);
  }

  export function StoryCreatorImportActorRequestToJSONTyped(value?: StoryCreatorImportActorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chatbot_id': value['chatbotId'],
    };
}

