/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryCreatorPanel } from './StoryCreatorPanel';
import {
    StoryCreatorPanelFromJSON,
    StoryCreatorPanelFromJSONTyped,
    StoryCreatorPanelToJSON,
    StoryCreatorPanelToJSONTyped,
} from './StoryCreatorPanel';
import type { StoryCreatorEpisode } from './StoryCreatorEpisode';
import {
    StoryCreatorEpisodeFromJSON,
    StoryCreatorEpisodeFromJSONTyped,
    StoryCreatorEpisodeToJSON,
    StoryCreatorEpisodeToJSONTyped,
} from './StoryCreatorEpisode';

/**
 * 
 * @export
 * @interface StoryCreatorEpisodeWithPanelsResponse
 */
export interface StoryCreatorEpisodeWithPanelsResponse {
    /**
     * 
     * @type {StoryCreatorEpisode}
     * @memberof StoryCreatorEpisodeWithPanelsResponse
     */
    episode: StoryCreatorEpisode;
    /**
     * 
     * @type {Array<StoryCreatorPanel>}
     * @memberof StoryCreatorEpisodeWithPanelsResponse
     */
    panels: Array<StoryCreatorPanel>;
}

/**
 * Check if a given object implements the StoryCreatorEpisodeWithPanelsResponse interface.
 */
export function instanceOfStoryCreatorEpisodeWithPanelsResponse(value: object): value is StoryCreatorEpisodeWithPanelsResponse {
    if (!('episode' in value) || value['episode'] === undefined) return false;
    if (!('panels' in value) || value['panels'] === undefined) return false;
    return true;
}

export function StoryCreatorEpisodeWithPanelsResponseFromJSON(json: any): StoryCreatorEpisodeWithPanelsResponse {
    return StoryCreatorEpisodeWithPanelsResponseFromJSONTyped(json, false);
}

export function StoryCreatorEpisodeWithPanelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorEpisodeWithPanelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'episode': StoryCreatorEpisodeFromJSON(json['episode']),
        'panels': ((json['panels'] as Array<any>).map(StoryCreatorPanelFromJSON)),
    };
}

  export function StoryCreatorEpisodeWithPanelsResponseToJSON(json: any): StoryCreatorEpisodeWithPanelsResponse {
      return StoryCreatorEpisodeWithPanelsResponseToJSONTyped(json, false);
  }

  export function StoryCreatorEpisodeWithPanelsResponseToJSONTyped(value?: StoryCreatorEpisodeWithPanelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episode': StoryCreatorEpisodeToJSON(value['episode']),
        'panels': ((value['panels'] as Array<any>).map(StoryCreatorPanelToJSON)),
    };
}

