/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActorRole } from './ActorRole';
import {
    ActorRoleFromJSON,
    ActorRoleFromJSONTyped,
    ActorRoleToJSON,
    ActorRoleToJSONTyped,
} from './ActorRole';

/**
 * 
 * @export
 * @interface StoryBuilderActor
 */
export interface StoryBuilderActor {
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderActor
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderActor
     */
    storyId: string;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderActor
     */
    displayName: string;
    /**
     * 
     * @type {ActorRole}
     * @memberof StoryBuilderActor
     */
    role: ActorRole;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderActor
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderActor
     */
    chatbotId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderActor
     */
    referenceAudioId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StoryBuilderActor
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof StoryBuilderActor
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the StoryBuilderActor interface.
 */
export function instanceOfStoryBuilderActor(value: object): value is StoryBuilderActor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('storyId' in value) || value['storyId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function StoryBuilderActorFromJSON(json: any): StoryBuilderActor {
    return StoryBuilderActorFromJSONTyped(json, false);
}

export function StoryBuilderActorFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryBuilderActor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'storyId': json['story_id'],
        'displayName': json['display_name'],
        'role': ActorRoleFromJSON(json['role']),
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'chatbotId': json['chatbot_id'] == null ? undefined : json['chatbot_id'],
        'referenceAudioId': json['reference_audio_id'] == null ? undefined : json['reference_audio_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function StoryBuilderActorToJSON(json: any): StoryBuilderActor {
      return StoryBuilderActorToJSONTyped(json, false);
  }

  export function StoryBuilderActorToJSONTyped(value?: StoryBuilderActor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'story_id': value['storyId'],
        'display_name': value['displayName'],
        'role': ActorRoleToJSON(value['role']),
        'avatar': value['avatar'],
        'chatbot_id': value['chatbotId'],
        'reference_audio_id': value['referenceAudioId'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

