/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryBuilderStory } from './StoryBuilderStory';
import {
    StoryBuilderStoryFromJSON,
    StoryBuilderStoryFromJSONTyped,
    StoryBuilderStoryToJSON,
    StoryBuilderStoryToJSONTyped,
} from './StoryBuilderStory';
import type { StoryBuilderEpisode } from './StoryBuilderEpisode';
import {
    StoryBuilderEpisodeFromJSON,
    StoryBuilderEpisodeFromJSONTyped,
    StoryBuilderEpisodeToJSON,
    StoryBuilderEpisodeToJSONTyped,
} from './StoryBuilderEpisode';
import type { StoryBuilderPanel } from './StoryBuilderPanel';
import {
    StoryBuilderPanelFromJSON,
    StoryBuilderPanelFromJSONTyped,
    StoryBuilderPanelToJSON,
    StoryBuilderPanelToJSONTyped,
} from './StoryBuilderPanel';
import type { StoryBuilderActor } from './StoryBuilderActor';
import {
    StoryBuilderActorFromJSON,
    StoryBuilderActorFromJSONTyped,
    StoryBuilderActorToJSON,
    StoryBuilderActorToJSONTyped,
} from './StoryBuilderActor';

/**
 * 
 * @export
 * @interface StoryBuilderCreateStoryResponse
 */
export interface StoryBuilderCreateStoryResponse {
    /**
     * 
     * @type {StoryBuilderStory}
     * @memberof StoryBuilderCreateStoryResponse
     */
    story: StoryBuilderStory;
    /**
     * 
     * @type {StoryBuilderEpisode}
     * @memberof StoryBuilderCreateStoryResponse
     */
    episode: StoryBuilderEpisode;
    /**
     * 
     * @type {StoryBuilderPanel}
     * @memberof StoryBuilderCreateStoryResponse
     */
    panel: StoryBuilderPanel;
    /**
     * 
     * @type {Array<StoryBuilderActor>}
     * @memberof StoryBuilderCreateStoryResponse
     */
    actors: Array<StoryBuilderActor>;
}

/**
 * Check if a given object implements the StoryBuilderCreateStoryResponse interface.
 */
export function instanceOfStoryBuilderCreateStoryResponse(value: object): value is StoryBuilderCreateStoryResponse {
    if (!('story' in value) || value['story'] === undefined) return false;
    if (!('episode' in value) || value['episode'] === undefined) return false;
    if (!('panel' in value) || value['panel'] === undefined) return false;
    if (!('actors' in value) || value['actors'] === undefined) return false;
    return true;
}

export function StoryBuilderCreateStoryResponseFromJSON(json: any): StoryBuilderCreateStoryResponse {
    return StoryBuilderCreateStoryResponseFromJSONTyped(json, false);
}

export function StoryBuilderCreateStoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryBuilderCreateStoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'story': StoryBuilderStoryFromJSON(json['story']),
        'episode': StoryBuilderEpisodeFromJSON(json['episode']),
        'panel': StoryBuilderPanelFromJSON(json['panel']),
        'actors': ((json['actors'] as Array<any>).map(StoryBuilderActorFromJSON)),
    };
}

  export function StoryBuilderCreateStoryResponseToJSON(json: any): StoryBuilderCreateStoryResponse {
      return StoryBuilderCreateStoryResponseToJSONTyped(json, false);
  }

  export function StoryBuilderCreateStoryResponseToJSONTyped(value?: StoryBuilderCreateStoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'story': StoryBuilderStoryToJSON(value['story']),
        'episode': StoryBuilderEpisodeToJSON(value['episode']),
        'panel': StoryBuilderPanelToJSON(value['panel']),
        'actors': ((value['actors'] as Array<any>).map(StoryBuilderActorToJSON)),
    };
}

