/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryCreatorActor } from './StoryCreatorActor';
import {
    StoryCreatorActorFromJSON,
    StoryCreatorActorFromJSONTyped,
    StoryCreatorActorToJSON,
    StoryCreatorActorToJSONTyped,
} from './StoryCreatorActor';

/**
 * 
 * @export
 * @interface StoryCreatorActorResponse
 */
export interface StoryCreatorActorResponse {
    /**
     * 
     * @type {StoryCreatorActor}
     * @memberof StoryCreatorActorResponse
     */
    actor: StoryCreatorActor;
}

/**
 * Check if a given object implements the StoryCreatorActorResponse interface.
 */
export function instanceOfStoryCreatorActorResponse(value: object): value is StoryCreatorActorResponse {
    if (!('actor' in value) || value['actor'] === undefined) return false;
    return true;
}

export function StoryCreatorActorResponseFromJSON(json: any): StoryCreatorActorResponse {
    return StoryCreatorActorResponseFromJSONTyped(json, false);
}

export function StoryCreatorActorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorActorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'actor': StoryCreatorActorFromJSON(json['actor']),
    };
}

  export function StoryCreatorActorResponseToJSON(json: any): StoryCreatorActorResponse {
      return StoryCreatorActorResponseToJSONTyped(json, false);
  }

  export function StoryCreatorActorResponseToJSONTyped(value?: StoryCreatorActorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actor': StoryCreatorActorToJSON(value['actor']),
    };
}

