/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryBuilderPanel } from './StoryBuilderPanel';
import {
    StoryBuilderPanelFromJSON,
    StoryBuilderPanelFromJSONTyped,
    StoryBuilderPanelToJSON,
    StoryBuilderPanelToJSONTyped,
} from './StoryBuilderPanel';

/**
 * 
 * @export
 * @interface StoryBuilderPanelResponse
 */
export interface StoryBuilderPanelResponse {
    /**
     * 
     * @type {StoryBuilderPanel}
     * @memberof StoryBuilderPanelResponse
     */
    panel: StoryBuilderPanel;
}

/**
 * Check if a given object implements the StoryBuilderPanelResponse interface.
 */
export function instanceOfStoryBuilderPanelResponse(value: object): value is StoryBuilderPanelResponse {
    if (!('panel' in value) || value['panel'] === undefined) return false;
    return true;
}

export function StoryBuilderPanelResponseFromJSON(json: any): StoryBuilderPanelResponse {
    return StoryBuilderPanelResponseFromJSONTyped(json, false);
}

export function StoryBuilderPanelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryBuilderPanelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'panel': StoryBuilderPanelFromJSON(json['panel']),
    };
}

  export function StoryBuilderPanelResponseToJSON(json: any): StoryBuilderPanelResponse {
      return StoryBuilderPanelResponseToJSONTyped(json, false);
  }

  export function StoryBuilderPanelResponseToJSONTyped(value?: StoryBuilderPanelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'panel': StoryBuilderPanelToJSON(value['panel']),
    };
}

