/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryBuilderEpisode } from './StoryBuilderEpisode';
import {
    StoryBuilderEpisodeFromJSON,
    StoryBuilderEpisodeFromJSONTyped,
    StoryBuilderEpisodeToJSON,
    StoryBuilderEpisodeToJSONTyped,
} from './StoryBuilderEpisode';

/**
 * 
 * @export
 * @interface StoryBuilderEpisodeResponse
 */
export interface StoryBuilderEpisodeResponse {
    /**
     * 
     * @type {StoryBuilderEpisode}
     * @memberof StoryBuilderEpisodeResponse
     */
    episode: StoryBuilderEpisode;
}

/**
 * Check if a given object implements the StoryBuilderEpisodeResponse interface.
 */
export function instanceOfStoryBuilderEpisodeResponse(value: object): value is StoryBuilderEpisodeResponse {
    if (!('episode' in value) || value['episode'] === undefined) return false;
    return true;
}

export function StoryBuilderEpisodeResponseFromJSON(json: any): StoryBuilderEpisodeResponse {
    return StoryBuilderEpisodeResponseFromJSONTyped(json, false);
}

export function StoryBuilderEpisodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryBuilderEpisodeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'episode': StoryBuilderEpisodeFromJSON(json['episode']),
    };
}

  export function StoryBuilderEpisodeResponseToJSON(json: any): StoryBuilderEpisodeResponse {
      return StoryBuilderEpisodeResponseToJSONTyped(json, false);
  }

  export function StoryBuilderEpisodeResponseToJSONTyped(value?: StoryBuilderEpisodeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episode': StoryBuilderEpisodeToJSON(value['episode']),
    };
}

