/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryVisibility } from './StoryVisibility';
import {
    StoryVisibilityFromJSON,
    StoryVisibilityFromJSONTyped,
    StoryVisibilityToJSON,
    StoryVisibilityToJSONTyped,
} from './StoryVisibility';

/**
 * 
 * @export
 * @interface StoryBuilderUpdateStoryRequest
 */
export interface StoryBuilderUpdateStoryRequest {
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderUpdateStoryRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderUpdateStoryRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderUpdateStoryRequest
     */
    coverImage?: string | null;
    /**
     * 
     * @type {StoryVisibility}
     * @memberof StoryBuilderUpdateStoryRequest
     */
    visibility?: StoryVisibility | null;
}



/**
 * Check if a given object implements the StoryBuilderUpdateStoryRequest interface.
 */
export function instanceOfStoryBuilderUpdateStoryRequest(value: object): value is StoryBuilderUpdateStoryRequest {
    return true;
}

export function StoryBuilderUpdateStoryRequestFromJSON(json: any): StoryBuilderUpdateStoryRequest {
    return StoryBuilderUpdateStoryRequestFromJSONTyped(json, false);
}

export function StoryBuilderUpdateStoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryBuilderUpdateStoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'visibility': json['visibility'] == null ? undefined : StoryVisibilityFromJSON(json['visibility']),
    };
}

  export function StoryBuilderUpdateStoryRequestToJSON(json: any): StoryBuilderUpdateStoryRequest {
      return StoryBuilderUpdateStoryRequestToJSONTyped(json, false);
  }

  export function StoryBuilderUpdateStoryRequestToJSONTyped(value?: StoryBuilderUpdateStoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'cover_image': value['coverImage'],
        'visibility': StoryVisibilityToJSON(value['visibility']),
    };
}

