/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeVisibility } from './EpisodeVisibility';
import {
    EpisodeVisibilityFromJSON,
    EpisodeVisibilityFromJSONTyped,
    EpisodeVisibilityToJSON,
    EpisodeVisibilityToJSONTyped,
} from './EpisodeVisibility';

/**
 * 
 * @export
 * @interface StoryBuilderUpdateEpisodeRequest
 */
export interface StoryBuilderUpdateEpisodeRequest {
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderUpdateEpisodeRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderUpdateEpisodeRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderUpdateEpisodeRequest
     */
    coverImage?: string | null;
    /**
     * 
     * @type {EpisodeVisibility}
     * @memberof StoryBuilderUpdateEpisodeRequest
     */
    visibility?: EpisodeVisibility | null;
    /**
     * 
     * @type {number}
     * @memberof StoryBuilderUpdateEpisodeRequest
     */
    episodeIndex?: number | null;
}



/**
 * Check if a given object implements the StoryBuilderUpdateEpisodeRequest interface.
 */
export function instanceOfStoryBuilderUpdateEpisodeRequest(value: object): value is StoryBuilderUpdateEpisodeRequest {
    return true;
}

export function StoryBuilderUpdateEpisodeRequestFromJSON(json: any): StoryBuilderUpdateEpisodeRequest {
    return StoryBuilderUpdateEpisodeRequestFromJSONTyped(json, false);
}

export function StoryBuilderUpdateEpisodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryBuilderUpdateEpisodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'visibility': json['visibility'] == null ? undefined : EpisodeVisibilityFromJSON(json['visibility']),
        'episodeIndex': json['episode_index'] == null ? undefined : json['episode_index'],
    };
}

  export function StoryBuilderUpdateEpisodeRequestToJSON(json: any): StoryBuilderUpdateEpisodeRequest {
      return StoryBuilderUpdateEpisodeRequestToJSONTyped(json, false);
  }

  export function StoryBuilderUpdateEpisodeRequestToJSONTyped(value?: StoryBuilderUpdateEpisodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'cover_image': value['coverImage'],
        'visibility': EpisodeVisibilityToJSON(value['visibility']),
        'episode_index': value['episodeIndex'],
    };
}

