/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Story } from './Story';
import {
    StoryFromJSON,
    StoryFromJSONTyped,
    StoryToJSON,
    StoryToJSONTyped,
} from './Story';

/**
 * 
 * @export
 * @interface StoryListResponse
 */
export interface StoryListResponse {
    /**
     * 
     * @type {Array<Story>}
     * @memberof StoryListResponse
     */
    items: Array<Story>;
    /**
     * 
     * @type {number}
     * @memberof StoryListResponse
     */
    total: number;
}

/**
 * Check if a given object implements the StoryListResponse interface.
 */
export function instanceOfStoryListResponse(value: object): value is StoryListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function StoryListResponseFromJSON(json: any): StoryListResponse {
    return StoryListResponseFromJSONTyped(json, false);
}

export function StoryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(StoryFromJSON)),
        'total': json['total'],
    };
}

  export function StoryListResponseToJSON(json: any): StoryListResponse {
      return StoryListResponseToJSONTyped(json, false);
  }

  export function StoryListResponseToJSONTyped(value?: StoryListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(StoryToJSON)),
        'total': value['total'],
    };
}

