/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryCreatorCreateEpisodeInput
 */
export interface StoryCreatorCreateEpisodeInput {
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorCreateEpisodeInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorCreateEpisodeInput
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorCreateEpisodeInput
     */
    coverImage?: string | null;
}

/**
 * Check if a given object implements the StoryCreatorCreateEpisodeInput interface.
 */
export function instanceOfStoryCreatorCreateEpisodeInput(value: object): value is StoryCreatorCreateEpisodeInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function StoryCreatorCreateEpisodeInputFromJSON(json: any): StoryCreatorCreateEpisodeInput {
    return StoryCreatorCreateEpisodeInputFromJSONTyped(json, false);
}

export function StoryCreatorCreateEpisodeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorCreateEpisodeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
    };
}

  export function StoryCreatorCreateEpisodeInputToJSON(json: any): StoryCreatorCreateEpisodeInput {
      return StoryCreatorCreateEpisodeInputToJSONTyped(json, false);
  }

  export function StoryCreatorCreateEpisodeInputToJSONTyped(value?: StoryCreatorCreateEpisodeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'cover_image': value['coverImage'],
    };
}

