/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserEpisodeProgressType } from './UserEpisodeProgressType';
import {
    UserEpisodeProgressTypeFromJSON,
    UserEpisodeProgressTypeFromJSONTyped,
    UserEpisodeProgressTypeToJSON,
    UserEpisodeProgressTypeToJSONTyped,
} from './UserEpisodeProgressType';
import type { StoryCreatorEpisodePrice } from './StoryCreatorEpisodePrice';
import {
    StoryCreatorEpisodePriceFromJSON,
    StoryCreatorEpisodePriceFromJSONTyped,
    StoryCreatorEpisodePriceToJSON,
    StoryCreatorEpisodePriceToJSONTyped,
} from './StoryCreatorEpisodePrice';
import type { EpisodeCounts } from './EpisodeCounts';
import {
    EpisodeCountsFromJSON,
    EpisodeCountsFromJSONTyped,
    EpisodeCountsToJSON,
    EpisodeCountsToJSONTyped,
} from './EpisodeCounts';
import type { EpisodeVisibility } from './EpisodeVisibility';
import {
    EpisodeVisibilityFromJSON,
    EpisodeVisibilityFromJSONTyped,
    EpisodeVisibilityToJSON,
    EpisodeVisibilityToJSONTyped,
} from './EpisodeVisibility';
import type { EpisodeRating } from './EpisodeRating';
import {
    EpisodeRatingFromJSON,
    EpisodeRatingFromJSONTyped,
    EpisodeRatingToJSON,
    EpisodeRatingToJSONTyped,
} from './EpisodeRating';
import type { AccessType } from './AccessType';
import {
    AccessTypeFromJSON,
    AccessTypeFromJSONTyped,
    AccessTypeToJSON,
    AccessTypeToJSONTyped,
} from './AccessType';

/**
 * 
 * @export
 * @interface StoryCreatorEpisode
 */
export interface StoryCreatorEpisode {
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorEpisode
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorEpisode
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorEpisode
     */
    coverImage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCreatorEpisode
     */
    lockAfter?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorEpisode
     */
    episodeId: string;
    /**
     * 
     * @type {boolean}
     * @memberof StoryCreatorEpisode
     */
    newerVersionExists?: boolean | null;
    /**
     * 
     * @type {EpisodeVisibility}
     * @memberof StoryCreatorEpisode
     */
    visibility: EpisodeVisibility;
    /**
     * 
     * @type {number}
     * @memberof StoryCreatorEpisode
     */
    episodeIndex: number;
    /**
     * 
     * @type {number}
     * @memberof StoryCreatorEpisode
     */
    panelsCount: number;
    /**
     * 
     * @type {EpisodeRating}
     * @memberof StoryCreatorEpisode
     */
    rating?: EpisodeRating | null;
    /**
     * 
     * @type {AccessType}
     * @memberof StoryCreatorEpisode
     */
    accessType?: AccessType | null;
    /**
     * 
     * @type {UserEpisodeProgressType}
     * @memberof StoryCreatorEpisode
     */
    progress?: UserEpisodeProgressType | null;
    /**
     * 
     * @type {Array<StoryCreatorEpisodePrice>}
     * @memberof StoryCreatorEpisode
     */
    prices?: Array<StoryCreatorEpisodePrice> | null;
    /**
     * 
     * @type {EpisodeCounts}
     * @memberof StoryCreatorEpisode
     */
    counts: EpisodeCounts;
    /**
     * 
     * @type {Date}
     * @memberof StoryCreatorEpisode
     */
    lastSaved: Date;
}



/**
 * Check if a given object implements the StoryCreatorEpisode interface.
 */
export function instanceOfStoryCreatorEpisode(value: object): value is StoryCreatorEpisode {
    if (!('episodeId' in value) || value['episodeId'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('episodeIndex' in value) || value['episodeIndex'] === undefined) return false;
    if (!('panelsCount' in value) || value['panelsCount'] === undefined) return false;
    if (!('counts' in value) || value['counts'] === undefined) return false;
    if (!('lastSaved' in value) || value['lastSaved'] === undefined) return false;
    return true;
}

export function StoryCreatorEpisodeFromJSON(json: any): StoryCreatorEpisode {
    return StoryCreatorEpisodeFromJSONTyped(json, false);
}

export function StoryCreatorEpisodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorEpisode {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'lockAfter': json['lock_after'] == null ? undefined : json['lock_after'],
        'episodeId': json['episode_id'],
        'newerVersionExists': json['newer_version_exists'] == null ? undefined : json['newer_version_exists'],
        'visibility': EpisodeVisibilityFromJSON(json['visibility']),
        'episodeIndex': json['episode_index'],
        'panelsCount': json['panels_count'],
        'rating': json['rating'] == null ? undefined : EpisodeRatingFromJSON(json['rating']),
        'accessType': json['access_type'] == null ? undefined : AccessTypeFromJSON(json['access_type']),
        'progress': json['progress'] == null ? undefined : UserEpisodeProgressTypeFromJSON(json['progress']),
        'prices': json['prices'] == null ? undefined : ((json['prices'] as Array<any>).map(StoryCreatorEpisodePriceFromJSON)),
        'counts': EpisodeCountsFromJSON(json['counts']),
        'lastSaved': (new Date(json['last_saved'])),
    };
}

  export function StoryCreatorEpisodeToJSON(json: any): StoryCreatorEpisode {
      return StoryCreatorEpisodeToJSONTyped(json, false);
  }

  export function StoryCreatorEpisodeToJSONTyped(value?: StoryCreatorEpisode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'cover_image': value['coverImage'],
        'lock_after': value['lockAfter'],
        'episode_id': value['episodeId'],
        'newer_version_exists': value['newerVersionExists'],
        'visibility': EpisodeVisibilityToJSON(value['visibility']),
        'episode_index': value['episodeIndex'],
        'panels_count': value['panelsCount'],
        'rating': EpisodeRatingToJSON(value['rating']),
        'access_type': AccessTypeToJSON(value['accessType']),
        'progress': UserEpisodeProgressTypeToJSON(value['progress']),
        'prices': value['prices'] == null ? undefined : ((value['prices'] as Array<any>).map(StoryCreatorEpisodePriceToJSON)),
        'counts': EpisodeCountsToJSON(value['counts']),
        'last_saved': ((value['lastSaved']).toISOString()),
    };
}

