/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EpisodeVisibility } from './EpisodeVisibility';
import {
    EpisodeVisibilityFromJSON,
    EpisodeVisibilityFromJSONTyped,
    EpisodeVisibilityToJSON,
    EpisodeVisibilityToJSONTyped,
} from './EpisodeVisibility';

/**
 * 
 * @export
 * @interface StoryBuilderEpisode
 */
export interface StoryBuilderEpisode {
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderEpisode
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderEpisode
     */
    ownerId: string;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderEpisode
     */
    storyId: string;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderEpisode
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderEpisode
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryBuilderEpisode
     */
    coverImage?: string | null;
    /**
     * 
     * @type {EpisodeVisibility}
     * @memberof StoryBuilderEpisode
     */
    visibility: EpisodeVisibility;
    /**
     * 
     * @type {number}
     * @memberof StoryBuilderEpisode
     */
    episodeIndex: number;
    /**
     * 
     * @type {Date}
     * @memberof StoryBuilderEpisode
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof StoryBuilderEpisode
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the StoryBuilderEpisode interface.
 */
export function instanceOfStoryBuilderEpisode(value: object): value is StoryBuilderEpisode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('storyId' in value) || value['storyId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('episodeIndex' in value) || value['episodeIndex'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function StoryBuilderEpisodeFromJSON(json: any): StoryBuilderEpisode {
    return StoryBuilderEpisodeFromJSONTyped(json, false);
}

export function StoryBuilderEpisodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryBuilderEpisode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerId': json['owner_id'],
        'storyId': json['story_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'visibility': EpisodeVisibilityFromJSON(json['visibility']),
        'episodeIndex': json['episode_index'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function StoryBuilderEpisodeToJSON(json: any): StoryBuilderEpisode {
      return StoryBuilderEpisodeToJSONTyped(json, false);
  }

  export function StoryBuilderEpisodeToJSONTyped(value?: StoryBuilderEpisode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'owner_id': value['ownerId'],
        'story_id': value['storyId'],
        'title': value['title'],
        'description': value['description'],
        'cover_image': value['coverImage'],
        'visibility': EpisodeVisibilityToJSON(value['visibility']),
        'episode_index': value['episodeIndex'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

