/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoryCounts
 */
export interface StoryCounts {
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    episodesTotal?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    episodesPublic?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    episodesFree?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    episodesGated?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    episodesPurchased?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    episodesLocked?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    panelsTotal?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    panelsPublic?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    panelsFree?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    panelsGated?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    panelsPurchased?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StoryCounts
     */
    panelsLocked?: number | null;
}

/**
 * Check if a given object implements the StoryCounts interface.
 */
export function instanceOfStoryCounts(value: object): value is StoryCounts {
    return true;
}

export function StoryCountsFromJSON(json: any): StoryCounts {
    return StoryCountsFromJSONTyped(json, false);
}

export function StoryCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'episodesTotal': json['episodes_total'] == null ? undefined : json['episodes_total'],
        'episodesPublic': json['episodes_public'] == null ? undefined : json['episodes_public'],
        'episodesFree': json['episodes_free'] == null ? undefined : json['episodes_free'],
        'episodesGated': json['episodes_gated'] == null ? undefined : json['episodes_gated'],
        'episodesPurchased': json['episodes_purchased'] == null ? undefined : json['episodes_purchased'],
        'episodesLocked': json['episodes_locked'] == null ? undefined : json['episodes_locked'],
        'panelsTotal': json['panels_total'] == null ? undefined : json['panels_total'],
        'panelsPublic': json['panels_public'] == null ? undefined : json['panels_public'],
        'panelsFree': json['panels_free'] == null ? undefined : json['panels_free'],
        'panelsGated': json['panels_gated'] == null ? undefined : json['panels_gated'],
        'panelsPurchased': json['panels_purchased'] == null ? undefined : json['panels_purchased'],
        'panelsLocked': json['panels_locked'] == null ? undefined : json['panels_locked'],
    };
}

  export function StoryCountsToJSON(json: any): StoryCounts {
      return StoryCountsToJSONTyped(json, false);
  }

  export function StoryCountsToJSONTyped(value?: StoryCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episodes_total': value['episodesTotal'],
        'episodes_public': value['episodesPublic'],
        'episodes_free': value['episodesFree'],
        'episodes_gated': value['episodesGated'],
        'episodes_purchased': value['episodesPurchased'],
        'episodes_locked': value['episodesLocked'],
        'panels_total': value['panelsTotal'],
        'panels_public': value['panelsPublic'],
        'panels_free': value['panelsFree'],
        'panels_gated': value['panelsGated'],
        'panels_purchased': value['panelsPurchased'],
        'panels_locked': value['panelsLocked'],
    };
}

