/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActorRole } from './ActorRole';
import {
    ActorRoleFromJSON,
    ActorRoleFromJSONTyped,
    ActorRoleToJSON,
    ActorRoleToJSONTyped,
} from './ActorRole';

/**
 * 
 * @export
 * @interface StoryCreatorCreateActorRequest
 */
export interface StoryCreatorCreateActorRequest {
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorCreateActorRequest
     */
    displayName: string;
    /**
     * 
     * @type {ActorRole}
     * @memberof StoryCreatorCreateActorRequest
     */
    role: ActorRole;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorCreateActorRequest
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorCreateActorRequest
     */
    chatbotId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryCreatorCreateActorRequest
     */
    referenceAudioId?: string | null;
}



/**
 * Check if a given object implements the StoryCreatorCreateActorRequest interface.
 */
export function instanceOfStoryCreatorCreateActorRequest(value: object): value is StoryCreatorCreateActorRequest {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function StoryCreatorCreateActorRequestFromJSON(json: any): StoryCreatorCreateActorRequest {
    return StoryCreatorCreateActorRequestFromJSONTyped(json, false);
}

export function StoryCreatorCreateActorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryCreatorCreateActorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'],
        'role': ActorRoleFromJSON(json['role']),
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'chatbotId': json['chatbot_id'] == null ? undefined : json['chatbot_id'],
        'referenceAudioId': json['reference_audio_id'] == null ? undefined : json['reference_audio_id'],
    };
}

  export function StoryCreatorCreateActorRequestToJSON(json: any): StoryCreatorCreateActorRequest {
      return StoryCreatorCreateActorRequestToJSONTyped(json, false);
  }

  export function StoryCreatorCreateActorRequestToJSONTyped(value?: StoryCreatorCreateActorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'role': ActorRoleToJSON(value['role']),
        'avatar': value['avatar'],
        'chatbot_id': value['chatbotId'],
        'reference_audio_id': value['referenceAudioId'],
    };
}

