/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TagCategory = {
    BaseModel: 'base_model',
    HairColor: 'hair_color',
    BodyType: 'body_type',
    BreastSize: 'breast_size',
    AssSize: 'ass_size',
    SexPosition: 'sex_position',
    Gender: 'gender',
    Fetishes: 'fetishes',
    Ethnicity: 'ethnicity',
    Age: 'age',
    Lora: 'lora',
    Style: 'style',
    RoleplayType: 'roleplay_type',
    CharacterType: 'character_type'
} as const;
export type TagCategory = typeof TagCategory[keyof typeof TagCategory];


export function instanceOfTagCategory(value: any): boolean {
    for (const key in TagCategory) {
        if (Object.prototype.hasOwnProperty.call(TagCategory, key)) {
            if (TagCategory[key as keyof typeof TagCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TagCategoryFromJSON(json: any): TagCategory {
    return TagCategoryFromJSONTyped(json, false);
}

export function TagCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagCategory {
    return json as TagCategory;
}

export function TagCategoryToJSON(value?: TagCategory | null): any {
    return value as any;
}

export function TagCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): TagCategory {
    return value as TagCategory;
}

