/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagModel
 */
export interface TagModel {
    /**
     * 
     * @type {Date}
     * @memberof TagModel
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TagModel
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof TagModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TagModel
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof TagModel
     */
    category: string;
}

/**
 * Check if a given object implements the TagModel interface.
 */
export function instanceOfTagModel(value: object): value is TagModel {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function TagModelFromJSON(json: any): TagModel {
    return TagModelFromJSONTyped(json, false);
}

export function TagModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagModel {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'],
        'category': json['category'],
    };
}

  export function TagModelToJSON(json: any): TagModel {
      return TagModelToJSONTyped(json, false);
  }

  export function TagModelToJSONTyped(value?: TagModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'id': value['id'],
        'value': value['value'],
        'category': value['category'],
    };
}

