/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextToSpeechEnhanceRequest
 */
export interface TextToSpeechEnhanceRequest {
    /**
     * 
     * @type {string}
     * @memberof TextToSpeechEnhanceRequest
     */
    content: string;
}

/**
 * Check if a given object implements the TextToSpeechEnhanceRequest interface.
 */
export function instanceOfTextToSpeechEnhanceRequest(value: object): value is TextToSpeechEnhanceRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function TextToSpeechEnhanceRequestFromJSON(json: any): TextToSpeechEnhanceRequest {
    return TextToSpeechEnhanceRequestFromJSONTyped(json, false);
}

export function TextToSpeechEnhanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextToSpeechEnhanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

  export function TextToSpeechEnhanceRequestToJSON(json: any): TextToSpeechEnhanceRequest {
      return TextToSpeechEnhanceRequestToJSONTyped(json, false);
  }

  export function TextToSpeechEnhanceRequestToJSONTyped(value?: TextToSpeechEnhanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

