/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentType } from './ContentType';
import {
    ContentTypeFromJSON,
    ContentTypeFromJSONTyped,
    ContentTypeToJSON,
    ContentTypeToJSONTyped,
} from './ContentType';
import type { ScoreCategory } from './ScoreCategory';
import {
    ScoreCategoryFromJSON,
    ScoreCategoryFromJSONTyped,
    ScoreCategoryToJSON,
    ScoreCategoryToJSONTyped,
} from './ScoreCategory';
import type { AuraSubcategory } from './AuraSubcategory';
import {
    AuraSubcategoryFromJSON,
    AuraSubcategoryFromJSONTyped,
    AuraSubcategoryToJSON,
    AuraSubcategoryToJSONTyped,
} from './AuraSubcategory';

/**
 * 
 * @export
 * @interface UserScore
 */
export interface UserScore {
    /**
     * 
     * @type {ScoreCategory}
     * @memberof UserScore
     */
    category: ScoreCategory;
    /**
     * 
     * @type {AuraSubcategory}
     * @memberof UserScore
     */
    subcategory: AuraSubcategory | null;
    /**
     * 
     * @type {ContentType}
     * @memberof UserScore
     */
    contentType: ContentType | null;
    /**
     * 
     * @type {number}
     * @memberof UserScore
     */
    weekScore: number;
    /**
     * 
     * @type {number}
     * @memberof UserScore
     */
    monthScore: number;
    /**
     * 
     * @type {number}
     * @memberof UserScore
     */
    yearScore: number;
    /**
     * 
     * @type {number}
     * @memberof UserScore
     */
    totalScore: number;
}



/**
 * Check if a given object implements the UserScore interface.
 */
export function instanceOfUserScore(value: object): value is UserScore {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('subcategory' in value) || value['subcategory'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('weekScore' in value) || value['weekScore'] === undefined) return false;
    if (!('monthScore' in value) || value['monthScore'] === undefined) return false;
    if (!('yearScore' in value) || value['yearScore'] === undefined) return false;
    if (!('totalScore' in value) || value['totalScore'] === undefined) return false;
    return true;
}

export function UserScoreFromJSON(json: any): UserScore {
    return UserScoreFromJSONTyped(json, false);
}

export function UserScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserScore {
    if (json == null) {
        return json;
    }
    return {
        
        'category': ScoreCategoryFromJSON(json['category']),
        'subcategory': AuraSubcategoryFromJSON(json['subcategory']),
        'contentType': ContentTypeFromJSON(json['content_type']),
        'weekScore': json['week_score'],
        'monthScore': json['month_score'],
        'yearScore': json['year_score'],
        'totalScore': json['total_score'],
    };
}

  export function UserScoreToJSON(json: any): UserScore {
      return UserScoreToJSONTyped(json, false);
  }

  export function UserScoreToJSONTyped(value?: UserScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': ScoreCategoryToJSON(value['category']),
        'subcategory': AuraSubcategoryToJSON(value['subcategory']),
        'content_type': ContentTypeToJSON(value['contentType']),
        'week_score': value['weekScore'],
        'month_score': value['monthScore'],
        'year_score': value['yearScore'],
        'total_score': value['totalScore'],
    };
}

