/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserBadgeStatus } from './UserBadgeStatus';
import {
    UserBadgeStatusFromJSON,
    UserBadgeStatusFromJSONTyped,
    UserBadgeStatusToJSON,
    UserBadgeStatusToJSONTyped,
} from './UserBadgeStatus';
import type { TimedScoreType } from './TimedScoreType';
import {
    TimedScoreTypeFromJSON,
    TimedScoreTypeFromJSONTyped,
    TimedScoreTypeToJSON,
    TimedScoreTypeToJSONTyped,
} from './TimedScoreType';

/**
 * 
 * @export
 * @interface UserBadge
 */
export interface UserBadge {
    /**
     * 
     * @type {string}
     * @memberof UserBadge
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserBadge
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof UserBadge
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserBadge
     */
    description: string | null;
    /**
     * 
     * @type {TimedScoreType}
     * @memberof UserBadge
     */
    scoreType: TimedScoreType;
    /**
     * 
     * @type {number}
     * @memberof UserBadge
     */
    requiredRank: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserBadge
     */
    scoreThreshold: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserBadge
     */
    tokenPrice: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserBadge
     */
    tokenAward: number | null;
    /**
     * 
     * @type {UserBadgeStatus}
     * @memberof UserBadge
     */
    status: UserBadgeStatus;
}



/**
 * Check if a given object implements the UserBadge interface.
 */
export function instanceOfUserBadge(value: object): value is UserBadge {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('scoreType' in value) || value['scoreType'] === undefined) return false;
    if (!('requiredRank' in value) || value['requiredRank'] === undefined) return false;
    if (!('scoreThreshold' in value) || value['scoreThreshold'] === undefined) return false;
    if (!('tokenPrice' in value) || value['tokenPrice'] === undefined) return false;
    if (!('tokenAward' in value) || value['tokenAward'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UserBadgeFromJSON(json: any): UserBadge {
    return UserBadgeFromJSONTyped(json, false);
}

export function UserBadgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBadge {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
        'scoreType': TimedScoreTypeFromJSON(json['score_type']),
        'requiredRank': json['required_rank'],
        'scoreThreshold': json['score_threshold'],
        'tokenPrice': json['token_price'],
        'tokenAward': json['token_award'],
        'status': UserBadgeStatusFromJSON(json['status']),
    };
}

  export function UserBadgeToJSON(json: any): UserBadge {
      return UserBadgeToJSONTyped(json, false);
  }

  export function UserBadgeToJSONTyped(value?: UserBadge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'score_type': TimedScoreTypeToJSON(value['scoreType']),
        'required_rank': value['requiredRank'],
        'score_threshold': value['scoreThreshold'],
        'token_price': value['tokenPrice'],
        'token_award': value['tokenAward'],
        'status': UserBadgeStatusToJSON(value['status']),
    };
}

