/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserEpisodeProgressType = {
    Opened: 'opened',
    Finished: 'finished'
} as const;
export type UserEpisodeProgressType = typeof UserEpisodeProgressType[keyof typeof UserEpisodeProgressType];


export function instanceOfUserEpisodeProgressType(value: any): boolean {
    for (const key in UserEpisodeProgressType) {
        if (Object.prototype.hasOwnProperty.call(UserEpisodeProgressType, key)) {
            if (UserEpisodeProgressType[key as keyof typeof UserEpisodeProgressType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserEpisodeProgressTypeFromJSON(json: any): UserEpisodeProgressType {
    return UserEpisodeProgressTypeFromJSONTyped(json, false);
}

export function UserEpisodeProgressTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserEpisodeProgressType {
    return json as UserEpisodeProgressType;
}

export function UserEpisodeProgressTypeToJSON(value?: UserEpisodeProgressType | null): any {
    return value as any;
}

export function UserEpisodeProgressTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): UserEpisodeProgressType {
    return value as UserEpisodeProgressType;
}

