/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserBadgeStatus = {
    Claimed: 'claimed',
    ClaimableRequirementsReached: 'claimable_requirements_reached',
    ClaimableRequirementsNotReached: 'claimable_requirements_not_reached',
    NotClaimable: 'not_claimable'
} as const;
export type UserBadgeStatus = typeof UserBadgeStatus[keyof typeof UserBadgeStatus];


export function instanceOfUserBadgeStatus(value: any): boolean {
    for (const key in UserBadgeStatus) {
        if (Object.prototype.hasOwnProperty.call(UserBadgeStatus, key)) {
            if (UserBadgeStatus[key as keyof typeof UserBadgeStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserBadgeStatusFromJSON(json: any): UserBadgeStatus {
    return UserBadgeStatusFromJSONTyped(json, false);
}

export function UserBadgeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBadgeStatus {
    return json as UserBadgeStatus;
}

export function UserBadgeStatusToJSON(value?: UserBadgeStatus | null): any {
    return value as any;
}

export function UserBadgeStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): UserBadgeStatus {
    return value as UserBadgeStatus;
}

