/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoLoraName } from './VideoLoraName';
import {
    VideoLoraNameFromJSON,
    VideoLoraNameFromJSONTyped,
    VideoLoraNameToJSON,
    VideoLoraNameToJSONTyped,
} from './VideoLoraName';

/**
 * 
 * @export
 * @interface VideoMod
 */
export interface VideoMod {
    /**
     * 
     * @type {string}
     * @memberof VideoMod
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VideoMod
     */
    url: string;
    /**
     * 
     * @type {VideoLoraName}
     * @memberof VideoMod
     */
    lora: VideoLoraName;
}



/**
 * Check if a given object implements the VideoMod interface.
 */
export function instanceOfVideoMod(value: object): value is VideoMod {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('lora' in value) || value['lora'] === undefined) return false;
    return true;
}

export function VideoModFromJSON(json: any): VideoMod {
    return VideoModFromJSONTyped(json, false);
}

export function VideoModFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoMod {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'lora': VideoLoraNameFromJSON(json['lora']),
    };
}

  export function VideoModToJSON(json: any): VideoMod {
      return VideoModToJSONTyped(json, false);
  }

  export function VideoModToJSONTyped(value?: VideoMod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'lora': VideoLoraNameToJSON(value['lora']),
    };
}

