/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatbotPreview } from './ChatbotPreview';
import {
    ChatbotPreviewFromJSON,
    ChatbotPreviewFromJSONTyped,
    ChatbotPreviewToJSON,
    ChatbotPreviewToJSONTyped,
} from './ChatbotPreview';
import type { VideoContent } from './VideoContent';
import {
    VideoContentFromJSON,
    VideoContentFromJSONTyped,
    VideoContentToJSON,
    VideoContentToJSONTyped,
} from './VideoContent';
import type { SharedContentType } from './SharedContentType';
import {
    SharedContentTypeFromJSON,
    SharedContentTypeFromJSONTyped,
    SharedContentTypeToJSON,
    SharedContentTypeToJSONTyped,
} from './SharedContentType';
import type { ImageContent } from './ImageContent';
import {
    ImageContentFromJSON,
    ImageContentFromJSONTyped,
    ImageContentToJSON,
    ImageContentToJSONTyped,
} from './ImageContent';
import type { StoryPreview } from './StoryPreview';
import {
    StoryPreviewFromJSON,
    StoryPreviewFromJSONTyped,
    StoryPreviewToJSON,
    StoryPreviewToJSONTyped,
} from './StoryPreview';

/**
 * 
 * @export
 * @interface WallPost
 */
export interface WallPost {
    /**
     * 
     * @type {string}
     * @memberof WallPost
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WallPost
     */
    creatorId: string;
    /**
     * 
     * @type {ChatbotPreview}
     * @memberof WallPost
     */
    chatbot: ChatbotPreview | null;
    /**
     * 
     * @type {StoryPreview}
     * @memberof WallPost
     */
    story: StoryPreview | null;
    /**
     * 
     * @type {Array<ImageContent>}
     * @memberof WallPost
     */
    pictures: Array<ImageContent>;
    /**
     * 
     * @type {Array<VideoContent>}
     * @memberof WallPost
     */
    videos: Array<VideoContent>;
    /**
     * 
     * @type {number}
     * @memberof WallPost
     */
    likes: number;
    /**
     * 
     * @type {number}
     * @memberof WallPost
     */
    messageCount: number | null;
    /**
     * 
     * @type {string}
     * @memberof WallPost
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof WallPost
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof WallPost
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof WallPost
     */
    liked: boolean;
    /**
     * 
     * @type {SharedContentType}
     * @memberof WallPost
     */
    type: SharedContentType;
}



/**
 * Check if a given object implements the WallPost interface.
 */
export function instanceOfWallPost(value: object): value is WallPost {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creatorId' in value) || value['creatorId'] === undefined) return false;
    if (!('chatbot' in value) || value['chatbot'] === undefined) return false;
    if (!('story' in value) || value['story'] === undefined) return false;
    if (!('pictures' in value) || value['pictures'] === undefined) return false;
    if (!('videos' in value) || value['videos'] === undefined) return false;
    if (!('likes' in value) || value['likes'] === undefined) return false;
    if (!('messageCount' in value) || value['messageCount'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('liked' in value) || value['liked'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WallPostFromJSON(json: any): WallPost {
    return WallPostFromJSONTyped(json, false);
}

export function WallPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): WallPost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'creatorId': json['creator_id'],
        'chatbot': ChatbotPreviewFromJSON(json['chatbot']),
        'story': StoryPreviewFromJSON(json['story']),
        'pictures': ((json['pictures'] as Array<any>).map(ImageContentFromJSON)),
        'videos': ((json['videos'] as Array<any>).map(VideoContentFromJSON)),
        'likes': json['likes'],
        'messageCount': json['message_count'],
        'description': json['description'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'liked': json['liked'],
        'type': SharedContentTypeFromJSON(json['type']),
    };
}

  export function WallPostToJSON(json: any): WallPost {
      return WallPostToJSONTyped(json, false);
  }

  export function WallPostToJSONTyped(value?: WallPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'creator_id': value['creatorId'],
        'chatbot': ChatbotPreviewToJSON(value['chatbot']),
        'story': StoryPreviewToJSON(value['story']),
        'pictures': ((value['pictures'] as Array<any>).map(ImageContentToJSON)),
        'videos': ((value['videos'] as Array<any>).map(VideoContentToJSON)),
        'likes': value['likes'],
        'message_count': value['messageCount'],
        'description': value['description'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'liked': value['liked'],
        'type': SharedContentTypeToJSON(value['type']),
    };
}

