/* tslint:disable */
/* eslint-disable */
/**
 * AI Babe Public API
 * Lorem ipsum
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WanExtendVideoCompletionPayload
 */
export interface WanExtendVideoCompletionPayload {
    /**
     * 
     * @type {string}
     * @memberof WanExtendVideoCompletionPayload
     */
    videoId: string;
    /**
     * 
     * @type {string}
     * @memberof WanExtendVideoCompletionPayload
     */
    videoUrl: string;
}

/**
 * Check if a given object implements the WanExtendVideoCompletionPayload interface.
 */
export function instanceOfWanExtendVideoCompletionPayload(value: object): value is WanExtendVideoCompletionPayload {
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('videoUrl' in value) || value['videoUrl'] === undefined) return false;
    return true;
}

export function WanExtendVideoCompletionPayloadFromJSON(json: any): WanExtendVideoCompletionPayload {
    return WanExtendVideoCompletionPayloadFromJSONTyped(json, false);
}

export function WanExtendVideoCompletionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): WanExtendVideoCompletionPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['video_id'],
        'videoUrl': json['video_url'],
    };
}

  export function WanExtendVideoCompletionPayloadToJSON(json: any): WanExtendVideoCompletionPayload {
      return WanExtendVideoCompletionPayloadToJSONTyped(json, false);
  }

  export function WanExtendVideoCompletionPayloadToJSONTyped(value?: WanExtendVideoCompletionPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video_id': value['videoId'],
        'video_url': value['videoUrl'],
    };
}

